import type { QuestionSetInput } from "./types";

// Source: All questions & answer/AMVI_Std7_HC_English.pdf + AMVI_Std7_HC_Marathi.pdf
// Both PDFs share identical question numbering/options/answers (38 MCQs).
// HC = History & Civics (इतिहास व नागरिकशास्त्र), per the PDF's own header.
const data: QuestionSetInput = {
  standard: { code: "STD7", nameEn: "Standard 7", nameMr: "इयत्ता ७वी", sortOrder: 7 },
  subject: { code: "HC", nameEn: "History & Civics", nameMr: "इतिहास व नागरिकशास्त्र", sortOrder: 3 },
  questions: [
    {
      textEn: "How many types of historical sources are there?",
      textMr: "इतिहासाचे किती प्रकारचे साधनस्रोत आहेत?",
      explanationEn: "There are THREE types of historical sources: Material sources, Written sources, and Oral sources.",
      explanationMr: "इतिहासाचे तीन प्रकारचे साधनस्रोत आहेत: भौतिक साधनस्रोत, लिखित साधनस्रोत आणि तोंडी साधनस्रोत.",
      options: [
        { label: "A", textEn: "Two", textMr: "दोन", isCorrect: false },
        { label: "B", textEn: "Three", textMr: "तीन", isCorrect: true },
        { label: "C", textEn: "Four", textMr: "चार", isCorrect: false },
        { label: "D", textEn: "Five", textMr: "पाच", isCorrect: false },
      ],
    },
    {
      textEn: "What is a carving inscribed on stone or a wall called?",
      textMr: "दगड किंवा भिंतीवर कोरलेल्या लेखाला काय म्हणतात?",
      explanationEn: "A carving on stone or a wall is called an inscription. It is an important material source of history.",
      explanationMr: "दगड किंवा भिंतीवर कोरलेल्या लेखाला शिलालेख म्हणतात. हे इतिहासाचे महत्त्वाचे भौतिक साधनस्रोत आहे.",
      options: [
        { label: "A", textEn: "Inscription", textMr: "शिलालेख", isCorrect: true },
        { label: "B", textEn: "Copper plate", textMr: "ताम्रपट", isCorrect: false },
        { label: "C", textEn: "Manuscript", textMr: "हस्तलिखित", isCorrect: false },
        { label: "D", textEn: "Coin", textMr: "नाणे", isCorrect: false },
      ],
    },
    {
      textEn: "What are royal edicts inscribed on copper sheets called?",
      textMr: "तांब्याच्या पत्र्यावर कोरलेले राजाज्ञांना काय म्हणतात?",
      explanationEn: "Royal edicts and decisions inscribed on copper sheets are called copper plates (Tamrapal). These are written sources.",
      explanationMr: "तांब्याच्या पत्र्यावर कोरलेल्या राजाज्ञा व निर्णयांना ताम्रपट म्हणतात. हे लिखित साधनस्रोताचे उदाहरण आहे.",
      options: [
        { label: "A", textEn: "Stone inscription", textMr: "शिलालेख", isCorrect: false },
        { label: "B", textEn: "Copper plates", textMr: "ताम्रपट", isCorrect: true },
        { label: "C", textEn: "Tavarikh", textMr: "तावारीख", isCorrect: false },
        { label: "D", textEn: "Shakavali", textMr: "शकावळी", isCorrect: false },
      ],
    },
    {
      textEn: "Which language is important for studying medieval Indian history?",
      textMr: "मध्ययुगीन इतिहासाच्या अभ्यासासाठी कोणती भाषा महत्त्वाची आहे?",
      explanationEn: "For studying medieval history, writings in Devanagari, Arabic, Persian, Modi and other scripts are important.",
      explanationMr: "मध्ययुगीन इतिहासाच्या अभ्यासासाठी देवनागरी, अरबी, फारसी, मोडी अशा अनेक भाषांतील लिखाण महत्त्वाचे आहे.",
      options: [
        { label: "A", textEn: "Only Sanskrit", textMr: "फक्त संस्कृत", isCorrect: false },
        { label: "B", textEn: "Only Urdu", textMr: "फक्त उर्दू", isCorrect: false },
        { label: "C", textEn: "Devanagari, Arabic, Persian, Modi etc.", textMr: "देवनागरी, अरबी, फारसी, मोडी इ.", isCorrect: true },
        { label: "D", textEn: "Only English", textMr: "फक्त इंग्रजी", isCorrect: false },
      ],
    },
    {
      textEn: "Who founded the Mughal Empire?",
      textMr: "मोगल साम्राज्याची स्थापना कोणी केली?",
      explanationEn: "The Mughal Empire was founded by Babur. He defeated Ibrahim Lodi at the First Battle of Panipat (1526).",
      explanationMr: "मोगल साम्राज्याची स्थापना बाबर याने केली. पानिपतच्या पहिल्या लढाईत (१५२६) इब्राहीम लोदी याचा पराभव करून बाबरने मोगल सत्ता स्थापली.",
      options: [
        { label: "A", textEn: "Akbar", textMr: "अकबर", isCorrect: false },
        { label: "B", textEn: "Babur", textMr: "बाबर", isCorrect: true },
        { label: "C", textEn: "Humayun", textMr: "हुमायून", isCorrect: false },
        { label: "D", textEn: "Aurangzeb", textMr: "औरंगजेब", isCorrect: false },
      ],
    },
    {
      textEn: "Who founded the Adilshahi dynasty of Bijapur?",
      textMr: "विजापूरचे आदिलशाही घराण्याची स्थापना कोणी केली?",
      explanationEn: "The Adilshahi dynasty of Bijapur was founded by Yusuf Adilshah. It was one of the Deccan Sultanates.",
      explanationMr: "विजापूरच्या आदिलशाही घराण्याची स्थापना युसुफ आदिलशाह याने केली. हे दख्खन सल्तनतींपैकी एक होते.",
      options: [
        { label: "A", textEn: "Yusuf Adilshah", textMr: "युसुफ आदिलशाह", isCorrect: true },
        { label: "B", textEn: "Ibrahim Adilshah", textMr: "इब्राहीम आदिलशाह", isCorrect: false },
        { label: "C", textEn: "Ali Adilshah", textMr: "अलीआदिलशाह", isCorrect: false },
        { label: "D", textEn: "Malik Ahmad", textMr: "मलिक अहमद", isCorrect: false },
      ],
    },
    {
      textEn: "What religious reform movement did Emperor Akbar initiate?",
      textMr: "अकबर बादशाहने कोणते धर्म सुधारणेचे प्रयत्न केले?",
      explanationEn: "Akbar initiated 'Din-i-Ilahi', a new religion combining good elements from all religions.",
      explanationMr: "अकबराने 'दीन-ए-इलाही' हा नवीन धर्म सुरू करण्याचा प्रयत्न केला, ज्यात सर्व धर्मांतील चांगले विचार घेतले होते.",
      options: [
        { label: "A", textEn: "Bhakti Movement", textMr: "भक्ती चळवळ", isCorrect: false },
        { label: "B", textEn: "Din-i-Ilahi", textMr: "दीन-ए-इलाही", isCorrect: true },
        { label: "C", textEn: "Sufi Movement", textMr: "सूफी चळवळ", isCorrect: false },
        { label: "D", textEn: "Islam", textMr: "इस्लाम", isCorrect: false },
      ],
    },
    {
      textEn: "What was the significance of the Bhakti Movement?",
      textMr: "भक्ती चळवळीचे महत्त्व काय होते?",
      explanationEn: "The Bhakti Movement emphasized devotion to God beyond caste and religious discrimination. Saints like Tukaram, Dnyaneshwar and Kabir were key figures.",
      explanationMr: "भक्ती चळवळ जाती-धर्माच्या भेदभावाला नाकारून ईश्वराच्या निस्सीम भक्तीवर भर देणारी होती. संत तुकाराम, संत ज्ञानेश्वर, कबीर हे प्रमुख संत होते.",
      options: [
        { label: "A", textEn: "Only for Hindus", textMr: "केवळ हिंदूंसाठी होती", isCorrect: false },
        { label: "B", textEn: "Devotion to God beyond caste-religion", textMr: "जाती-धर्माच्या पलीकडे जाऊन ईश्वर भक्ती", isCorrect: true },
        { label: "C", textEn: "Only in Maharashtra", textMr: "फक्त महाराष्ट्रात होती", isCorrect: false },
        { label: "D", textEn: "For Muslims only", textMr: "मुस्लिमांसाठी होती", isCorrect: false },
      ],
    },
    {
      textEn: "Which book did Saint Dnyaneshwar write on the Bhagavad Gita?",
      textMr: "संत ज्ञानेश्वरांनी भगवद्गीतेवर कोणता ग्रंथ लिहिला?",
      explanationEn: "Saint Dnyaneshwar wrote 'Dnyaneshwari', a Marathi commentary on the Bhagavad Gita. It is a priceless treasure of Marathi literature.",
      explanationMr: "संत ज्ञानेश्वरांनी भगवद्गीतेवर 'ज्ञानेश्वरी' हा मराठी ग्रंथ लिहिला. हा ग्रंथ मराठी साहित्यातील अमूल्य ठेवा आहे.",
      options: [
        { label: "A", textEn: "Dasbodh", textMr: "दासबोध", isCorrect: false },
        { label: "B", textEn: "Dnyaneshwari", textMr: "ज्ञानेश्वरी", isCorrect: true },
        { label: "C", textEn: "Tukaram Gatha", textMr: "तुकाराम गाथा", isCorrect: false },
        { label: "D", textEn: "Eknathi Bhagavat", textMr: "एकनाथी भागवत", isCorrect: false },
      ],
    },
    {
      textEn: "What was the main message of Sufi saints?",
      textMr: "सूफी संतांचा मुख्य संदेश काय होता?",
      explanationEn: "The main message of Sufi saints was love for God, humanity, harmony among all religions, and unity.",
      explanationMr: "सूफी संतांचा मुख्य संदेश ईश्वरावरील प्रेम, मानवता, सर्व धर्मांमध्ये समन्वय आणि एकतेचा होता.",
      options: [
        { label: "A", textEn: "Following religion strictly", textMr: "धर्माचे पालन", isCorrect: false },
        { label: "B", textEn: "Love for God and humanity", textMr: "ईश्वर प्रेम व मानवता", isCorrect: true },
        { label: "C", textEn: "Establishing a kingdom", textMr: "राज्य स्थापना", isCorrect: false },
        { label: "D", textEn: "Waging war", textMr: "युद्ध करणे", isCorrect: false },
      ],
    },
    {
      textEn: "Who was the father of Chhatrapati Shivaji Maharaj?",
      textMr: "शिवाजी महाराजांचे वडील कोण होते?",
      explanationEn: "Shivaji Maharaj's father was Shahaji Bhosale, who served as a commander in the Adilshahi of Bijapur.",
      explanationMr: "शिवाजी महाराजांचे वडील शहाजी भोसले हे विजापूरच्या आदिलशाहीत सरदार होते.",
      options: [
        { label: "A", textEn: "Jijabai", textMr: "जिजाबाई", isCorrect: false },
        { label: "B", textEn: "Shahaji Bhosale", textMr: "शहाजी भोसले", isCorrect: true },
        { label: "C", textEn: "Maloji Bhosale", textMr: "मालोजी भोसले", isCorrect: false },
        { label: "D", textEn: "Dadaji Konddev", textMr: "दादाजी कोंडदेव", isCorrect: false },
      ],
    },
    {
      textEn: "What was the name of Shivaji Maharaj's mother?",
      textMr: "शिवाजी महाराजांच्या आईचे नाव काय होते?",
      explanationEn: "Shivaji Maharaj's mother was Jijabai. She inspired Shivaji Maharaj to establish Swaraj.",
      explanationMr: "शिवाजी महाराजांच्या आईचे नाव जिजाबाई होते. त्यांनी शिवाजी महाराजांना स्वराज्याची प्रेरणा दिली.",
      options: [
        { label: "A", textEn: "Tuljabhavani", textMr: "तुळजाभवानी", isCorrect: false },
        { label: "B", textEn: "Parvatibai", textMr: "पार्वतीबाई", isCorrect: false },
        { label: "C", textEn: "Jijabai", textMr: "जिजाबाई", isCorrect: true },
        { label: "D", textEn: "Saibai", textMr: "सईबाई", isCorrect: false },
      ],
    },
    {
      textEn: "At what age did Shivaji Maharaj take the oath to establish Swaraj?",
      textMr: "शिवाजी महाराजांनी स्वराज्याचा संकल्प किती वयात केला?",
      explanationEn: "At approximately 16 years of age, Shivaji Maharaj took an oath at Raireshwar temple to establish Swaraj.",
      explanationMr: "शिवाजी महाराजांनी वयाच्या सुमारे १६ व्या वर्षी रायरेश्वर मंदिरात स्वराज्य स्थापण्याची शपथ घेतली.",
      options: [
        { label: "A", textEn: "12 years", textMr: "१२ वर्षे", isCorrect: false },
        { label: "B", textEn: "16 years", textMr: "१६ वर्षे", isCorrect: true },
        { label: "C", textEn: "20 years", textMr: "२० वर्षे", isCorrect: false },
        { label: "D", textEn: "25 years", textMr: "२५ वर्षे", isCorrect: false },
      ],
    },
    {
      textEn: "Which was the first fort captured by Shivaji Maharaj?",
      textMr: "शिवाजी महाराजांनी प्रथम कोणता किल्ला जिंकला?",
      explanationEn: "Shivaji Maharaj first captured Torana fort (1647). This was the first major step in establishing Swaraj.",
      explanationMr: "शिवाजी महाराजांनी प्रथम तोरणा किल्ला जिंकला (१६४७). हा त्यांच्या स्वराज्य स्थापनेचा पहिला महत्त्वाचा टप्पा होता.",
      options: [
        { label: "A", textEn: "Rajgad", textMr: "राजगड", isCorrect: false },
        { label: "B", textEn: "Raigad", textMr: "रायगड", isCorrect: false },
        { label: "C", textEn: "Torana", textMr: "तोरणा", isCorrect: true },
        { label: "D", textEn: "Sinhagad", textMr: "सिंहगड", isCorrect: false },
      ],
    },
    {
      textEn: "Where was Afzal Khan killed?",
      textMr: "अफझलखानाचा वध कोठे झाला?",
      explanationEn: "Shivaji Maharaj killed Afzal Khan at Pratapgad (1659). This greatly strengthened Swaraj.",
      explanationMr: "शिवाजी महाराजांनी प्रतापगड येथे अफझलखानाचा वध केला (१६५९). यामुळे स्वराज्य अधिक बळकट झाले.",
      options: [
        { label: "A", textEn: "Raigad", textMr: "रायगड", isCorrect: false },
        { label: "B", textEn: "Pratapgad", textMr: "प्रतापगड", isCorrect: true },
        { label: "C", textEn: "Sinhagad", textMr: "सिंहगड", isCorrect: false },
        { label: "D", textEn: "Rajgad", textMr: "राजगड", isCorrect: false },
      ],
    },
    {
      textEn: "After the raid on Shaistakhan's camp, what did Shivaji Maharaj do?",
      textMr: "शाइस्ताखानाच्या छापेमारीनंतर शिवाजी महाराजांनी काय केले?",
      explanationEn: "In retaliation against Shaistakhan, Shivaji Maharaj raided Surat (1664), the wealthy Mughal trading port.",
      explanationMr: "शाइस्ताखानाच्या प्रतिशोधात शिवाजी महाराजांनी मोगलांची श्रीमंत व्यापारी बंदर असलेल्या सुरतेची लूट केली (१६६४).",
      options: [
        { label: "A", textEn: "Surrendered", textMr: "आत्मसमर्पण केले", isCorrect: false },
        { label: "B", textEn: "Raided Surat", textMr: "सुरतेची लूट केली", isCorrect: true },
        { label: "C", textEn: "Made treaty with Aurangzeb", textMr: "औरंगजेबाशी तह केला", isCorrect: false },
        { label: "D", textEn: "Left Maharashtra", textMr: "महाराष्ट्र सोडला", isCorrect: false },
      ],
    },
    {
      textEn: "When was the Treaty of Purandar signed?",
      textMr: "पुरंदरचा तह कधी झाला?",
      explanationEn: "The Treaty of Purandar was signed in 1665 between Shivaji Maharaj and Mughal commander Mirza Raja Jai Singh. Shivaji had to give up 23 forts.",
      explanationMr: "पुरंदरचा तह १६६५ मध्ये शिवाजी महाराज आणि मोगल सरदार मिर्झा राजे जयसिंग यांच्यात झाला. यात शिवाजींना २३ किल्ले द्यावे लागले.",
      options: [
        { label: "A", textEn: "1657", textMr: "१६५७", isCorrect: false },
        { label: "B", textEn: "1659", textMr: "१६५९", isCorrect: false },
        { label: "C", textEn: "1665", textMr: "१६६५", isCorrect: true },
        { label: "D", textEn: "1674", textMr: "१६७४", isCorrect: false },
      ],
    },
    {
      textEn: "How many ministers were there in Shivaji Maharaj's Ashtapradhan council?",
      textMr: "शिवाजी महाराजांच्या अष्टप्रधान मंडळात किती मंत्री होते?",
      explanationEn: "Shivaji Maharaj's Ashtapradhan council had eight ministers: Peshwa, Amatya, Sachiv, Mantri, Senapati, Sumant, Nyayadhish, and Panditrao.",
      explanationMr: "शिवाजी महाराजांच्या अष्टप्रधान मंडळात आठ मंत्री होते. पंतप्रधान (पेशवा), अमात्य, सचिव, मंत्री, सेनापती, सुमंत, न्यायाधीश आणि पंडितराव.",
      options: [
        { label: "A", textEn: "Four", textMr: "चार", isCorrect: false },
        { label: "B", textEn: "Six", textMr: "सहा", isCorrect: false },
        { label: "C", textEn: "Eight", textMr: "आठ", isCorrect: true },
        { label: "D", textEn: "Ten", textMr: "दहा", isCorrect: false },
      ],
    },
    {
      textEn: "What did Shivaji Maharaj emphasize?",
      textMr: "शिवाजी महाराजांनी कशावर भर दिला?",
      explanationEn: "Shivaji Maharaj emphasized the welfare of the people (rayat), just administration, and revenue reforms.",
      explanationMr: "शिवाजी महाराजांनी रयतेचे (जनतेचे) कल्याण, न्यायी प्रशासन आणि महसूल सुधारणा यांवर भर दिला.",
      options: [
        { label: "A", textEn: "Only military strength", textMr: "फक्त सैन्यशक्ती", isCorrect: false },
        { label: "B", textEn: "Welfare of people and administration", textMr: "रयतेचे कल्याण व प्रशासन", isCorrect: true },
        { label: "C", textEn: "Friendship with Mughals", textMr: "मोगलांशी मित्रता", isCorrect: false },
        { label: "D", textEn: "Spreading religion", textMr: "धर्म प्रसार", isCorrect: false },
      ],
    },
    {
      textEn: "Where was Chhatrapati Shivaji Maharaj's coronation held?",
      textMr: "शिवाजी महाराजांचा राज्याभिषेक कोठे झाला?",
      explanationEn: "Chhatrapati Shivaji Maharaj's coronation was held at Raigad fort on June 6, 1674. He received the title 'Chhatrapati'.",
      explanationMr: "शिवाजी महाराजांचा राज्याभिषेक ६ जून १६७४ रोजी रायगड किल्ल्यावर झाला. त्यांना 'छत्रपती' ही पदवी मिळाली.",
      options: [
        { label: "A", textEn: "Rajgad", textMr: "राजगड", isCorrect: false },
        { label: "B", textEn: "Pune", textMr: "पुणे", isCorrect: false },
        { label: "C", textEn: "Raigad", textMr: "रायगड", isCorrect: true },
        { label: "D", textEn: "Pratapgad", textMr: "प्रतापगड", isCorrect: false },
      ],
    },
    {
      textEn: "What was the significance of Shivaji Maharaj's navy?",
      textMr: "शिवाजी महाराजांचे आरमाराचे महत्त्व काय होते?",
      explanationEn: "Shivaji Maharaj built a strong navy. It was used to protect sea borders and fight enemies at sea.",
      explanationMr: "शिवाजी महाराजांनी मजबूत आरमार (नौदल) उभारले. हे समुद्री सीमांच्या संरक्षणासाठी आणि शत्रूंशी लढण्यासाठी उपयुक्त होते.",
      options: [
        { label: "A", textEn: "Only for trade", textMr: "फक्त व्यापारासाठी", isCorrect: false },
        { label: "B", textEn: "Protecting sea borders", textMr: "समुद्री सीमांचे संरक्षण", isCorrect: true },
        { label: "C", textEn: "Making friends with enemies", textMr: "शत्रूंशी मित्रता", isCorrect: false },
        { label: "D", textEn: "Crossing rivers", textMr: "नदी पार करणे", isCorrect: false },
      ],
    },
    {
      textEn: "Who captured Sambhaji Maharaj?",
      textMr: "संभाजी महाराजांना कोणी पकडले?",
      explanationEn: "Mughal commander Mukarrab Khan captured Sambhaji Maharaj. Aurangzeb then brutally executed him in 1689.",
      explanationMr: "मुकर्रब खान या मोगल सरदाराने संभाजी महाराजांना पकडले. त्यानंतर औरंगजेबाने त्यांना क्रूरपणे ठार मारले (१६८९).",
      options: [
        { label: "A", textEn: "Shaistakhan", textMr: "शाइस्ताखान", isCorrect: false },
        { label: "B", textEn: "Mughal commander Mukarrab Khan", textMr: "मोगल सरदार मुकर्रब खान", isCorrect: true },
        { label: "C", textEn: "Adilshah", textMr: "आदिलशाह", isCorrect: false },
        { label: "D", textEn: "Portuguese", textMr: "पोर्तुगीज", isCorrect: false },
      ],
    },
    {
      textEn: "Who took charge of Swaraj after Rajaram Maharaj?",
      textMr: "राजाराम महाराजांनंतर स्वराज्याचा भार कोणी सांभाळला?",
      explanationEn: "After the death of Rajaram Maharaj, his wife Tarabai took charge and defended Swaraj against the Mughals.",
      explanationMr: "राजाराम महाराजांच्या मृत्यूनंतर त्यांची पत्नी ताराबाईंनी मोगलांशी लढत स्वराज्याचे रक्षण केले.",
      options: [
        { label: "A", textEn: "Sambhaji Maharaj", textMr: "संभाजी महाराज", isCorrect: false },
        { label: "B", textEn: "Tarabai", textMr: "ताराबाई", isCorrect: true },
        { label: "C", textEn: "Yesubai", textMr: "येसूबाई", isCorrect: false },
        { label: "D", textEn: "Shahu Maharaj", textMr: "शाहू महाराज", isCorrect: false },
      ],
    },
    {
      textEn: "What was the significance of Balaji Vishwanath Peshwa?",
      textMr: "बाळाजी विश्वनाथ पेशवे यांचे महत्त्व काय होते?",
      explanationEn: "Balaji Vishwanath was the first Peshwa. He unified the Maratha Empire and laid the foundation of Peshwa power.",
      explanationMr: "बाळाजी विश्वनाथ हे पहिले पेशवे होते. त्यांनी मराठा साम्राज्याला एकसंध केले व पेशवाई सत्तेचा पाया घातला.",
      options: [
        { label: "A", textEn: "First Peshwa", textMr: "पहिले पेशवे होते", isCorrect: true },
        { label: "B", textEn: "Expanded Maratha Empire to North India", textMr: "मराठा साम्राज्य उत्तर भारतात विस्तारले", isCorrect: false },
        { label: "C", textEn: "Defeated Mughals", textMr: "मोगलांचा पराभव केला", isCorrect: false },
        { label: "D", textEn: "Won forts", textMr: "किल्ले जिंकले", isCorrect: false },
      ],
    },
    {
      textEn: "In which battle did Bajirao Peshwa defeat the Mughals?",
      textMr: "बाजीराव पेशवे यांनी कोणत्या युद्धात मोगलांना हरवले?",
      explanationEn: "Bajirao Peshwa made a daring raid on Delhi (1737), shaking the Mughal power significantly.",
      explanationMr: "बाजीराव पेशव्यांनी दिल्लीवर धाडसी छापा घातला (१७३७) आणि मोगल सत्तेला हादरवून सोडले.",
      options: [
        { label: "A", textEn: "Battle of Panipat", textMr: "पानिपतची लढाई", isCorrect: false },
        { label: "B", textEn: "Raid on Delhi", textMr: "दिल्लीवर छापा", isCorrect: true },
        { label: "C", textEn: "Battle of Kharda", textMr: "खर्द्याची लढाई", isCorrect: false },
        { label: "D", textEn: "Battle of Raigad", textMr: "रायगडची लढाई", isCorrect: false },
      ],
    },
    {
      textEn: "When was the Third Battle of Panipat fought?",
      textMr: "पानिपतची तिसरी लढाई कधी झाली?",
      explanationEn: "The Third Battle of Panipat was fought on January 14, 1761. The Marathas fought against Afghan ruler Ahmad Shah Abdali.",
      explanationMr: "पानिपतची तिसरी लढाई १४ जानेवारी १७६१ रोजी झाली. मराठे अफगाण सरदार अहमद शाह अब्दालीशी लढले.",
      options: [
        { label: "A", textEn: "1737", textMr: "१७३७", isCorrect: false },
        { label: "B", textEn: "1747", textMr: "१७४७", isCorrect: false },
        { label: "C", textEn: "1757", textMr: "१७५७", isCorrect: false },
        { label: "D", textEn: "1761", textMr: "१७६१", isCorrect: true },
      ],
    },
    {
      textEn: "What was the capital during the Peshwa period?",
      textMr: "पेशवाईत कोणती राजधानी होती?",
      explanationEn: "Pune was the capital during the Peshwa period. Shaniwarwada was the famous palace of the Peshwas.",
      explanationMr: "पेशवाईच्या काळात पुणे ही मराठा साम्राज्याची राजधानी होती. शनिवारवाडा हा पेशव्यांचा प्रसिद्ध राजवाडा होता.",
      options: [
        { label: "A", textEn: "Satara", textMr: "सातारा", isCorrect: false },
        { label: "B", textEn: "Nagpur", textMr: "नागपूर", isCorrect: false },
        { label: "C", textEn: "Pune", textMr: "पुणे", isCorrect: true },
        { label: "D", textEn: "Kolhapur", textMr: "कोल्हापूर", isCorrect: false },
      ],
    },
    {
      textEn: "What was the contribution of Madhavrao Peshwa?",
      textMr: "माधवराव पेशव्यांचे योगदान काय होते?",
      explanationEn: "Madhavrao Peshwa revived the Maratha Empire after the defeat at Panipat. He was a great administrator.",
      explanationMr: "माधवराव पेशव्यांनी पानिपतच्या पराभवानंतर मराठा साम्राज्याचे पुनरुज्जीवन केले. ते थोर प्रशासक होते.",
      options: [
        { label: "A", textEn: "Destruction of Maratha Empire", textMr: "मराठा साम्राज्याचा नाश", isCorrect: false },
        { label: "B", textEn: "Revival of Maratha Empire", textMr: "मराठा साम्राज्याचे पुनरुज्जीवन", isCorrect: true },
        { label: "C", textEn: "Friendship with British", textMr: "इंग्रजांशी मित्रता", isCorrect: false },
        { label: "D", textEn: "Lost wars", textMr: "युद्ध हरले", isCorrect: false },
      ],
    },
    {
      textEn: "What was the language used in daily life in medieval Maharashtra?",
      textMr: "मध्ययुगीन महाराष्ट्रात कोणती भाषा व्यवहाराची होती?",
      explanationEn: "In medieval Maharashtra, Marathi was the language of daily life. Marathi was written in the Modi script.",
      explanationMr: "मध्ययुगीन महाराष्ट्रात मराठी ही लोकांची दैनंदिन व्यवहाराची भाषा होती. मोडी लिपीत मराठी लिहिले जात असे.",
      options: [
        { label: "A", textEn: "Sanskrit", textMr: "संस्कृत", isCorrect: false },
        { label: "B", textEn: "Hindi", textMr: "हिंदी", isCorrect: false },
        { label: "C", textEn: "Marathi", textMr: "मराठी", isCorrect: true },
        { label: "D", textEn: "Persian", textMr: "फारसी", isCorrect: false },
      ],
    },
    {
      textEn: "Who wrote the Dasbodh?",
      textMr: "दासबोध हा ग्रंथ कोणी लिहिला?",
      explanationEn: "Dasbodh was written by Samarth Ramdas Swami, who was the spiritual guru of Shivaji Maharaj.",
      explanationMr: "दासबोध हा ग्रंथ समर्थ रामदास स्वामींनी लिहिला. हा शिवाजी महाराजांचे गुरू होते.",
      options: [
        { label: "A", textEn: "Sant Tukaram", textMr: "संत तुकाराम", isCorrect: false },
        { label: "B", textEn: "Samarth Ramdas", textMr: "समर्थ रामदास", isCorrect: true },
        { label: "C", textEn: "Sant Dnyaneshwar", textMr: "संत ज्ञानेश्वर", isCorrect: false },
        { label: "D", textEn: "Sant Eknath", textMr: "संत एकनाथ", isCorrect: false },
      ],
    },
    {
      textEn: "When did the Indian Constitution come into force?",
      textMr: "भारताची राज्यघटना कधी अंमलात आली?",
      explanationEn: "The Indian Constitution came into force on January 26, 1950. Hence January 26 is celebrated as Republic Day.",
      explanationMr: "भारताची राज्यघटना २६ जानेवारी १९५० रोजी अंमलात आली. म्हणून २६ जानेवारी हा 'प्रजासत्ताक दिन' म्हणून साजरा केला जातो.",
      options: [
        { label: "A", textEn: "15 August 1947", textMr: "१५ ऑगस्ट १९४७", isCorrect: false },
        { label: "B", textEn: "26 January 1950", textMr: "२६ जानेवारी १९५०", isCorrect: true },
        { label: "C", textEn: "26 November 1949", textMr: "२६ नोव्हेंबर १९४९", isCorrect: false },
        { label: "D", textEn: "15 January 1950", textMr: "१५ जानेवारी १९५०", isCorrect: false },
      ],
    },
    {
      textEn: "Who was the chairman of the Drafting Committee of the Constitution?",
      textMr: "राज्यघटनेचा मसुदा तयार करणाऱ्या समितीचे अध्यक्ष कोण होते?",
      explanationEn: "Dr. B.R. Ambedkar was the chairman of the Drafting Committee. He is called the 'Father of the Indian Constitution'.",
      explanationMr: "डॉ. बाबासाहेब आंबेडकर हे राज्यघटनेच्या मसुदा समितीचे अध्यक्ष होते. म्हणून त्यांना 'राज्यघटनेचे शिल्पकार' म्हणतात.",
      options: [
        { label: "A", textEn: "Jawaharlal Nehru", textMr: "जवाहरलाल नेहरू", isCorrect: false },
        { label: "B", textEn: "Mahatma Gandhi", textMr: "महात्मा गांधी", isCorrect: false },
        { label: "C", textEn: "Dr. B.R. Ambedkar", textMr: "डॉ. बाबासाहेब आंबेडकर", isCorrect: true },
        { label: "D", textEn: "Sardar Vallabhbhai Patel", textMr: "सरदार वल्लभभाई पटेल", isCorrect: false },
      ],
    },
    {
      textEn: "Which key values are enshrined in the Preamble of the Indian Constitution?",
      textMr: "भारतीय राज्यघटनेच्या प्रस्तावनेत कोणते प्रमुख तत्त्व आहेत?",
      explanationEn: "The Preamble of the Indian Constitution enshrines Justice, Liberty, Equality, and Fraternity as core values.",
      explanationMr: "भारतीय राज्यघटनेच्या प्रस्तावनेत न्याय (Justice), स्वातंत्र्य (Liberty), समता (Equality) आणि बंधुता (Fraternity) ही मूल्ये आहेत.",
      options: [
        { label: "A", textEn: "Justice, Liberty, Equality, Fraternity", textMr: "न्याय, स्वातंत्र्य, समता, बंधुता", isCorrect: true },
        { label: "B", textEn: "Only liberty", textMr: "केवळ स्वातंत्र्य", isCorrect: false },
        { label: "C", textEn: "Only equality", textMr: "केवळ समता", isCorrect: false },
        { label: "D", textEn: "Only justice", textMr: "फक्त न्याय", isCorrect: false },
      ],
    },
    {
      textEn: "India is described as what type of state in the Constitution?",
      textMr: "भारत हे कोणत्या प्रकारचे राज्य आहे?",
      explanationEn: "According to the Preamble, India is a Sovereign, Socialist, Secular, Democratic Republic.",
      explanationMr: "राज्यघटनेच्या प्रस्तावनेनुसार भारत हे सार्वभौम, समाजवादी, धर्मनिरपेक्ष, लोकशाही प्रजासत्ताक आहे.",
      options: [
        { label: "A", textEn: "Monarchy", textMr: "राजशाही", isCorrect: false },
        { label: "B", textEn: "Sovereign Socialist Secular Democratic Republic", textMr: "सार्वभौम समाजवादी धर्मनिरपेक्ष लोकशाही प्रजासत्ताक", isCorrect: true },
        { label: "C", textEn: "Theocracy", textMr: "धर्मशाही", isCorrect: false },
        { label: "D", textEn: "Dictatorship", textMr: "हुकूमशाही", isCorrect: false },
      ],
    },
    {
      textEn: "How many Fundamental Rights are there in the Indian Constitution?",
      textMr: "भारतीय राज्यघटनेत किती मूलभूत हक्क आहेत?",
      explanationEn: "There are SIX Fundamental Rights: Right to Equality, Right to Freedom, Right against Exploitation, Right to Freedom of Religion, Cultural and Educational Rights, Right to Constitutional Remedies.",
      explanationMr: "भारतीय राज्यघटनेत सहा मूलभूत हक्क आहेत: समानतेचा हक्क, स्वातंत्र्याचा हक्क, शोषणाविरुद्ध हक्क, धर्मस्वातंत्र्याचा हक्क, सांस्कृतिक व शैक्षणिक हक्क, घटनात्मक उपाययोजनांचा हक्क.",
      options: [
        { label: "A", textEn: "Four", textMr: "चार", isCorrect: false },
        { label: "B", textEn: "Five", textMr: "पाच", isCorrect: false },
        { label: "C", textEn: "Six", textMr: "सहा", isCorrect: true },
        { label: "D", textEn: "Seven", textMr: "सात", isCorrect: false },
      ],
    },
    {
      textEn: "Who protects Fundamental Rights?",
      textMr: "मूलभूत हक्कांचे रक्षण कोण करते?",
      explanationEn: "The Judiciary protects Fundamental Rights. Citizens can approach the Supreme Court or High Court if rights are violated.",
      explanationMr: "मूलभूत हक्कांचे रक्षण न्यायालय (Judiciary) करते. नागरिकांना हक्क मिळाला नाही तर ते सर्वोच्च न्यायालय किंवा उच्च न्यायालयात जाऊ शकतात.",
      options: [
        { label: "A", textEn: "Parliament", textMr: "संसद", isCorrect: false },
        { label: "B", textEn: "State Legislature", textMr: "राज्य विधिमंडळ", isCorrect: false },
        { label: "C", textEn: "Judiciary", textMr: "न्यायालय", isCorrect: true },
        { label: "D", textEn: "Police", textMr: "पोलीस", isCorrect: false },
      ],
    },
    {
      textEn: "To whom are the Directive Principles of State Policy applicable?",
      textMr: "मार्गदर्शक तत्त्वे (Directive Principles) कोणाला लागू होतात?",
      explanationEn: "Directive Principles are applicable to the government (state). They guide policy-making but are not enforceable by courts.",
      explanationMr: "मार्गदर्शक तत्त्वे सरकारला (राज्यास) लागू होतात. ती सरकारच्या धोरणनिर्मितीसाठी मार्गदर्शन करतात, परंतु न्यायालयात लागू करता येत नाहीत.",
      options: [
        { label: "A", textEn: "Citizens", textMr: "नागरिकांना", isCorrect: false },
        { label: "B", textEn: "Government", textMr: "सरकारला", isCorrect: true },
        { label: "C", textEn: "Judiciary", textMr: "न्यायालयाला", isCorrect: false },
        { label: "D", textEn: "Everyone", textMr: "सर्वांना", isCorrect: false },
      ],
    },
    {
      textEn: "What is the difference between Fundamental Rights and Directive Principles?",
      textMr: "मूलभूत हक्क आणि मार्गदर्शक तत्त्वांमध्ये काय फरक आहे?",
      explanationEn: "Fundamental Rights are justiciable (enforceable by courts), while Directive Principles are non-justiciable.",
      explanationMr: "मूलभूत हक्क न्यायालयात लागू करता येतात (Justiciable), तर मार्गदर्शक तत्त्वे न्यायालयात लागू करता येत नाहीत (Non-justiciable).",
      options: [
        { label: "A", textEn: "Both are enforceable", textMr: "दोन्ही न्यायालयात लागू करता येतात", isCorrect: false },
        { label: "B", textEn: "Fundamental Rights enforceable, Directives not", textMr: "मूलभूत हक्क न्यायालयात लागू, तत्त्वे नाहीत", isCorrect: true },
        { label: "C", textEn: "Both not enforceable", textMr: "दोन्ही लागू नाहीत", isCorrect: false },
        { label: "D", textEn: "Both for government", textMr: "दोन्ही सरकारसाठी आहेत", isCorrect: false },
      ],
    },
  ],
};

export default data;
