import type { QuestionSetInput } from "./types";

// Source: All questions & answer/AMVI_Std8_GS_English.pdf + AMVI_Std8_GS_Marathi.pdf
// Both PDFs share identical question numbering/options/answers (62 MCQs).
// Subject full name confirmed from PDF headers: "General Science" / "सामान्य विज्ञान".
const data: QuestionSetInput = {
  standard: { code: "STD8", nameEn: "Standard 8", nameMr: "इयत्ता ८वी", sortOrder: 8 },
  subject: { code: "GS", nameEn: "General Science", nameMr: "सामान्य विज्ञान", sortOrder: 1 },
  questions: [
    {
      textEn: "How many kingdoms did Whittaker divide living organisms into?",
      textMr: "व्हिटकर यांनी सजीवांना किती सृष्टींमध्ये विभागले?",
      explanationEn:
        "Robert Whittaker (1969) divided living organisms into 5 kingdoms: Monera, Protista, Fungi, Plantae and Animalia.",
      explanationMr:
        "रॉबर्ट व्हिटकर (१९६९) यांनी सजीवांना ५ सृष्टींमध्ये विभागले: मोनेरा, प्रोटिस्टा, बुरशी, वनस्पती आणि प्राणी.",
      options: [
        { label: "A", textEn: "Three", textMr: "तीन", isCorrect: false },
        { label: "B", textEn: "Five", textMr: "पाच", isCorrect: true },
        { label: "C", textEn: "Six", textMr: "सहा", isCorrect: false },
        { label: "D", textEn: "Four", textMr: "चार", isCorrect: false },
      ],
    },
    {
      textEn: "Which kingdom do bacteria belong to?",
      textMr: "जीवाणू (Bacteria) कोणत्या सृष्टीत येतात?",
      explanationEn: "Bacteria are prokaryotic (no nucleus) and belong to the kingdom Monera.",
      explanationMr: "जीवाणू हे प्रोकॅरियोटिक असतात म्हणजे त्यांना केंद्रक नसते. ते मोनेरा सृष्टीत येतात.",
      options: [
        { label: "A", textEn: "Protista", textMr: "प्रोटिस्टा", isCorrect: false },
        { label: "B", textEn: "Fungi", textMr: "बुरशी", isCorrect: false },
        { label: "C", textEn: "Monera", textMr: "मोनेरा", isCorrect: true },
        { label: "D", textEn: "Plantae", textMr: "वनस्पती", isCorrect: false },
      ],
    },
    {
      textEn: "From which fungus is the antibiotic penicillin obtained?",
      textMr: "पेनिसिलिन हे प्रतिजैविक कोणत्या बुरशीपासून मिळते?",
      explanationEn:
        "Penicillin, the first antibiotic, was discovered by Alexander Fleming in 1928 from the fungus Penicillium.",
      explanationMr:
        "पेनिसिलिअम या बुरशीपासून पेनिसिलिन हे पहिले प्रतिजैविक अलेक्झांडर फ्लेमिंग यांनी १९२८ मध्ये शोधले.",
      options: [
        { label: "A", textEn: "Aspergillus", textMr: "एस्परजिलस", isCorrect: false },
        { label: "B", textEn: "Penicillium", textMr: "पेनिसिलिअम", isCorrect: true },
        { label: "C", textEn: "Mucor", textMr: "म्यूकर", isCorrect: false },
        { label: "D", textEn: "Yeast", textMr: "यीस्ट", isCorrect: false },
      ],
    },
    {
      textEn: "Are viruses living or non-living?",
      textMr: "विषाणू (Virus) हे सजीव की निर्जीव?",
      explanationEn:
        "Viruses are non-living outside a host cell but show living characteristics inside a host cell — hence they exhibit properties of both.",
      explanationMr:
        "विषाणू हे पेशीबाहेर निर्जीव असतात पण सजीव पेशींमध्ये शिरल्यावर जिवंत वर्तन करतात. म्हणून ते दोन्ही गुणधर्म दाखवतात.",
      options: [
        { label: "A", textEn: "Living", textMr: "सजीव", isCorrect: false },
        { label: "B", textEn: "Non-living", textMr: "निर्जीव", isCorrect: false },
        { label: "C", textEn: "Neither", textMr: "दोन्ही नाही", isCorrect: false },
        { label: "D", textEn: "Both", textMr: "सजीव व निर्जीव दोन्ही", isCorrect: true },
      ],
    },
    {
      textEn: "Which kingdom does Amoeba belong to?",
      textMr: "अमीबा कोणत्या सृष्टीत येतो?",
      explanationEn: "Amoeba is a unicellular eukaryotic organism and belongs to the kingdom Protista.",
      explanationMr: "अमीबा हा एकपेशीय युकॅरियोटिक सजीव असून तो प्रोटिस्टा सृष्टीत येतो.",
      options: [
        { label: "A", textEn: "Monera", textMr: "मोनेरा", isCorrect: false },
        { label: "B", textEn: "Protista", textMr: "प्रोटिस्टा", isCorrect: true },
        { label: "C", textEn: "Fungi", textMr: "बुरशी", isCorrect: false },
        { label: "D", textEn: "Animalia", textMr: "प्राणी", isCorrect: false },
      ],
    },
    {
      textEn: "Which pathogen causes malaria?",
      textMr: "मलेरिया हा रोग कोणत्या रोगकारकामुळे होतो?",
      explanationEn: "Malaria is caused by Plasmodium, a protozoan parasite, spread by the female Anopheles mosquito.",
      explanationMr: "मलेरिया हा प्लास्मोडियम या प्रोटोझोआमुळे होतो. हा रोगकारक मादी अॅनॉफिलीस डासाद्वारे पसरतो.",
      options: [
        { label: "A", textEn: "Bacteria", textMr: "जीवाणू", isCorrect: false },
        { label: "B", textEn: "Virus", textMr: "विषाणू", isCorrect: false },
        { label: "C", textEn: "Plasmodium", textMr: "प्लास्मोडियम", isCorrect: true },
        { label: "D", textEn: "Fungi", textMr: "बुरशी", isCorrect: false },
      ],
    },
    {
      textEn: "Which bacterium causes tuberculosis (TB)?",
      textMr: "क्षयरोग (TB) कोणत्या जीवाणूमुळे होतो?",
      explanationEn: "Tuberculosis is caused by Mycobacterium tuberculosis. The BCG vaccine protects against this disease.",
      explanationMr: "क्षयरोग मायकोबॅक्टेरिअम ट्युबरक्युलोसिस या जीवाणूमुळे होतो. BCG लस या रोगापासून संरक्षण देते.",
      options: [
        { label: "A", textEn: "Streptococcus", textMr: "स्ट्रेप्टोकोकस", isCorrect: false },
        { label: "B", textEn: "Mycobacterium tuberculosis", textMr: "मायकोबॅक्टेरिअम ट्युबरक्युलोसिस", isCorrect: true },
        { label: "C", textEn: "Salmonella", textMr: "साल्मोनेला", isCorrect: false },
        { label: "D", textEn: "Vibrio", textMr: "विब्रिओ", isCorrect: false },
      ],
    },
    {
      textEn: "Which virus causes AIDS?",
      textMr: "AIDS हा रोग कोणत्या विषाणूमुळे होतो?",
      explanationEn: "AIDS is caused by the Human Immunodeficiency Virus (HIV), which weakens the immune system.",
      explanationMr: "AIDS हा Human Immunodeficiency Virus (HIV) मुळे होतो. हा विषाणू रोगप्रतिकारक शक्ती कमी करतो.",
      options: [
        { label: "A", textEn: "HIV", textMr: "HIV", isCorrect: true },
        { label: "B", textEn: "HBV", textMr: "HBV", isCorrect: false },
        { label: "C", textEn: "HPV", textMr: "HPV", isCorrect: false },
        { label: "D", textEn: "HCV", textMr: "HCV", isCorrect: false },
      ],
    },
    {
      textEn: "On which principle does vaccination work?",
      textMr: "लसीकरण (Vaccination) कोणत्या तत्त्वावर कार्य करते?",
      explanationEn:
        "Vaccination introduces dead or weakened pathogens to build immunity, so the body can fight future infections effectively.",
      explanationMr:
        "लसीकरण शरीरात मृत किंवा क्षीण रोगकारक घालून प्रतिकारशक्ती निर्माण करते, जेणेकरून भविष्यात खरा संसर्ग झाल्यास शरीर लढू शकते.",
      options: [
        { label: "A", textEn: "Antibiotics", textMr: "प्रतिजैविक", isCorrect: false },
        { label: "B", textEn: "Immunity", textMr: "प्रतिकारशक्ती", isCorrect: true },
        { label: "C", textEn: "Blood transfusion", textMr: "रक्त संक्रमण", isCorrect: false },
        { label: "D", textEn: "Surgery", textMr: "शस्त्रक्रिया", isCorrect: false },
      ],
    },
    {
      textEn: "What is cancer?",
      textMr: "कर्करोग (Cancer) म्हणजे काय?",
      explanationEn: "Cancer involves uncontrolled division of cells forming tumors called malignant tumors.",
      explanationMr: "कर्करोगात पेशी अनियंत्रितपणे विभाजित होतात व गाठी (tumors) बनतात. त्यांना घातक (malignant) म्हणतात.",
      options: [
        { label: "A", textEn: "Bacterial disease", textMr: "जीवाणूजन्य रोग", isCorrect: false },
        { label: "B", textEn: "Uncontrolled cell division", textMr: "अनियंत्रित पेशी विभाजन", isCorrect: true },
        { label: "C", textEn: "Blood disease", textMr: "रक्ताचा रोग", isCorrect: false },
        { label: "D", textEn: "Hormone imbalance", textMr: "हार्मोन असंतुलन", isCorrect: false },
      ],
    },
    {
      textEn: "Pressure = ?",
      textMr: "दाब (Pressure) = ?",
      explanationEn:
        "Pressure = Force ÷ Area. SI unit is Pascal (Pa). Smaller area means more pressure — as seen with a needle.",
      explanationMr: "दाब = बल ÷ क्षेत्रफळ. SI एकक पास्कल (Pa) आहे. क्षेत्रफळ जास्त तेव्हा दाब कमी, हे सुईचे उदाहरण दाखवते.",
      options: [
        { label: "A", textEn: "Force × Area", textMr: "बल × क्षेत्रफळ", isCorrect: false },
        { label: "B", textEn: "Force / Area", textMr: "बल / क्षेत्रफळ", isCorrect: true },
        { label: "C", textEn: "Area / Force", textMr: "क्षेत्रफळ / बल", isCorrect: false },
        { label: "D", textEn: "Force + Area", textMr: "बल + क्षेत्रफळ", isCorrect: false },
      ],
    },
    {
      textEn: "Which instrument measures atmospheric pressure?",
      textMr: "वायुमंडलीय दाब मोजण्याचे उपकरण कोणते?",
      explanationEn: "Barometer measures atmospheric pressure. At sea level the pressure is approximately 101325 Pa (1 atm).",
      explanationMr: "बॅरोमीटर हे वायुमंडलीय दाब मोजण्याचे उपकरण आहे. समुद्रसपाटीवर दाब सुमारे १०१३२५ Pa (१ atm) असतो.",
      options: [
        { label: "A", textEn: "Thermometer", textMr: "थर्मोमीटर", isCorrect: false },
        { label: "B", textEn: "Barometer", textMr: "बॅरोमीटर", isCorrect: true },
        { label: "C", textEn: "Anemometer", textMr: "अॅनिमोमीटर", isCorrect: false },
        { label: "D", textEn: "Hygrometer", textMr: "हायग्रोमीटर", isCorrect: false },
      ],
    },
    {
      textEn: "On what does liquid pressure depend?",
      textMr: "द्रवाचा दाब कशावर अवलंबून असतो?",
      explanationEn: "Liquid pressure is given by P = ρgh (density × gravity × depth). Greater depth and density → greater pressure.",
      explanationMr: "द्रवाचा दाब P = ρgh सूत्राने दिला जातो. (ρ = घनता, g = गुरुत्वीय प्रवेग, h = खोली) खोली व घनता जास्त तेव्हा दाब जास्त.",
      options: [
        { label: "A", textEn: "Temperature only", textMr: "फक्त तापमानावर", isCorrect: false },
        { label: "B", textEn: "Depth and density", textMr: "खोली व घनतेवर", isCorrect: true },
        { label: "C", textEn: "Colour", textMr: "रंगावर", isCorrect: false },
        { label: "D", textEn: "Shape", textMr: "आकारावर", isCorrect: false },
      ],
    },
    {
      textEn: "Which is an example of non-contact force?",
      textMr: "संपर्क बल (Contact force) व असंपर्क बल (Non-contact force) यातील उदाहरण कोणते?",
      explanationEn:
        "Magnetic force, gravity and electrostatic force are non-contact forces — they act without direct physical contact.",
      explanationMr:
        "चुंबकीय बल, गुरुत्वाकर्षण व स्थिर विद्युत बल ही असंपर्क बले आहेत — वस्तू थेट स्पर्श न करताही कार्य करतात.",
      options: [
        { label: "A", textEn: "Friction", textMr: "घर्षण", isCorrect: false },
        { label: "B", textEn: "Magnetic force", textMr: "चुंबकीय बल", isCorrect: true },
        { label: "C", textEn: "Tension", textMr: "तणाव", isCorrect: false },
        { label: "D", textEn: "Normal reaction", textMr: "सामान्य प्रतिक्रिया", isCorrect: false },
      ],
    },
    {
      textEn: "What is the unit of electrical resistance?",
      textMr: "विद्युत प्रतिरोध मोजण्याचे एकक कोणते?",
      explanationEn: "Ohm (Ω) is the SI unit of electrical resistance. Ohm's Law: V = IR (Voltage = Current × Resistance).",
      explanationMr: "ओहम (Ω) हे विद्युत प्रतिरोधाचे SI एकक आहे. ओहमचा नियम: V = IR (व्होल्टेज = प्रवाह × प्रतिरोध).",
      options: [
        { label: "A", textEn: "Volt", textMr: "व्होल्ट", isCorrect: false },
        { label: "B", textEn: "Ampere", textMr: "अँपिअर", isCorrect: false },
        { label: "C", textEn: "Ohm", textMr: "ओहम", isCorrect: true },
        { label: "D", textEn: "Watt", textMr: "वॅट", isCorrect: false },
      ],
    },
    {
      textEn: "What are the poles of a magnet?",
      textMr: "चुंबकाचे ध्रुव कोणते?",
      explanationEn: "Every magnet has a North (N) and South (S) pole. Like poles repel; unlike poles attract.",
      explanationMr: "प्रत्येक चुंबकाला उत्तर (N) व दक्षिण (S) असे दोन ध्रुव असतात. समान ध्रुव एकमेकांना दूर लोटतात, विरुद्ध ध्रुव आकर्षतात.",
      options: [
        { label: "A", textEn: "East and West", textMr: "पूर्व व पश्चिम", isCorrect: false },
        { label: "B", textEn: "North and South", textMr: "उत्तर व दक्षिण", isCorrect: true },
        { label: "C", textEn: "Positive and Negative", textMr: "धन व ऋण", isCorrect: false },
        { label: "D", textEn: "Up and Down", textMr: "वर व खाली", isCorrect: false },
      ],
    },
    {
      textEn: "On what principle does an electric bell work?",
      textMr: "विद्युत घंटा (Electric bell) कशाच्या तत्त्वावर काम करते?",
      explanationEn:
        "An electric bell works on the principle of an electromagnet — current creates a magnetic field that attracts the hammer.",
      explanationMr:
        "विद्युत घंटा विद्युत चुंबकाच्या तत्त्वावर काम करते. विद्युत प्रवाह वाहिल्यावर विद्युत चुंबक तयार होतो जो घणाला आकर्षतो.",
      options: [
        { label: "A", textEn: "Static electricity", textMr: "स्थिर विद्युत", isCorrect: false },
        { label: "B", textEn: "Electromagnet", textMr: "विद्युत चुंबक", isCorrect: true },
        { label: "C", textEn: "Solar energy", textMr: "सौर ऊर्जा", isCorrect: false },
        { label: "D", textEn: "Sound waves", textMr: "ध्वनी लहरी", isCorrect: false },
      ],
    },
    {
      textEn: "What is a fuse used for?",
      textMr: "फ्युज (Fuse) हे उपकरण कशासाठी वापरतात?",
      explanationEn: "A fuse is a safety device — it melts when excess current flows, breaking the circuit and protecting appliances.",
      explanationMr: "फ्युज हा एक सुरक्षा उपकरण आहे. जास्त विद्युत प्रवाह वाहिल्यास तो वितळतो व परिपथ तुटतो, यामुळे उपकरणे सुरक्षित राहतात.",
      options: [
        { label: "A", textEn: "To save electricity", textMr: "वीज वाचवण्यासाठी", isCorrect: false },
        { label: "B", textEn: "Protection from excess current", textMr: "जास्त विद्युत प्रवाहापासून सुरक्षेसाठी", isCorrect: true },
        { label: "C", textEn: "To increase resistance", textMr: "प्रतिरोध वाढवण्यासाठी", isCorrect: false },
        { label: "D", textEn: "To increase voltage", textMr: "व्होल्टेज वाढवण्यासाठी", isCorrect: false },
      ],
    },
    {
      textEn: "What is found in the nucleus of an atom?",
      textMr: "अणूच्या केंद्रकात काय असते?",
      explanationEn: "The nucleus contains protons (positive charge) and neutrons (neutral). Electrons (negative charge) orbit the nucleus.",
      explanationMr: "अणूच्या केंद्रकात प्रोटॉन (धनभार) व न्यूट्रॉन (उदासीन) असतात. इलेक्ट्रॉन (ऋणभार) केंद्रकाभोवती फिरतात.",
      options: [
        { label: "A", textEn: "Only electrons", textMr: "फक्त इलेक्ट्रॉन", isCorrect: false },
        { label: "B", textEn: "Protons and neutrons", textMr: "प्रोटॉन व न्यूट्रॉन", isCorrect: true },
        { label: "C", textEn: "Only protons", textMr: "फक्त प्रोटॉन", isCorrect: false },
        { label: "D", textEn: "Electrons and protons", textMr: "इलेक्ट्रॉन व प्रोटॉन", isCorrect: false },
      ],
    },
    {
      textEn: "What does atomic number mean?",
      textMr: "अणुक्रमांक (Atomic number) म्हणजे काय?",
      explanationEn: "Atomic number = number of protons = number of electrons in a neutral atom. It uniquely identifies the element.",
      explanationMr: "अणुक्रमांक = प्रोटॉनांची संख्या = उदासीन अणूत इलेक्ट्रॉनांची संख्या. हे मूलद्रव्याचे वैशिष्ट्य ठरवते.",
      options: [
        { label: "A", textEn: "Number of neutrons", textMr: "न्यूट्रॉनची संख्या", isCorrect: false },
        { label: "B", textEn: "Number of protons", textMr: "प्रोटॉनची संख्या", isCorrect: true },
        { label: "C", textEn: "Number of electrons", textMr: "इलेक्ट्रॉनची संख्या", isCorrect: false },
        { label: "D", textEn: "Mass of atom", textMr: "अणूचे वस्तुमान", isCorrect: false },
      ],
    },
    {
      textEn: "Who discovered radioactivity?",
      textMr: "रेडिओधर्मिता (Radioactivity) शोधणारे शास्त्रज्ञ कोण?",
      explanationEn: "Henri Becquerel discovered radioactivity in 1896. Marie and Pierre Curie later discovered radium and polonium.",
      explanationMr: "हेन्री बेकरेल यांनी १८९६ मध्ये रेडिओधर्मिता शोधली. मेरी व पियेर क्युरी यांनी रेडिअम व पोलोनिअम शोधले.",
      options: [
        { label: "A", textEn: "Marie Curie", textMr: "मेरी क्युरी", isCorrect: false },
        { label: "B", textEn: "Henri Becquerel", textMr: "हेन्री बेकरेल", isCorrect: true },
        { label: "C", textEn: "Rutherford", textMr: "रदरफोर्ड", isCorrect: false },
        { label: "D", textEn: "Einstein", textMr: "आईन्स्टाईन", isCorrect: false },
      ],
    },
    {
      textEn: "What are isotopes?",
      textMr: "समस्थानिके (Isotopes) म्हणजे काय?",
      explanationEn: "Isotopes have the same atomic number but different mass numbers. E.g. isotopes of hydrogen: ¹H, ²H, ³H.",
      explanationMr: "समस्थानिकांचा अणुक्रमांक सारखा असतो पण अणुभार (mass number) वेगळा असतो. उदा. हायड्रोजनचे समस्थानिके: ¹H, ²H, ³H.",
      options: [
        { label: "A", textEn: "Same atomic number, different mass number", textMr: "समान अणुक्रमांक, वेगळे अणुभार", isCorrect: true },
        { label: "B", textEn: "Different atomic number, same mass number", textMr: "वेगळे अणुक्रमांक, समान अणुभार", isCorrect: false },
        { label: "C", textEn: "Same all properties", textMr: "समान सर्व गुणधर्म", isCorrect: false },
        { label: "D", textEn: "Atoms of different elements", textMr: "वेगळ्या मूलद्रव्यांचे अणू", isCorrect: false },
      ],
    },
    {
      textEn: "What is a solution?",
      textMr: "द्रावण (Solution) म्हणजे काय?",
      explanationEn: "A solution is a homogeneous mixture where the solute is dissolved uniformly in the solvent.",
      explanationMr: "द्रावण हे एकसंध मिश्रण असते ज्यात विरघळणारा पदार्थ (solute) विलायक (solvent) मध्ये विरघळलेला असतो.",
      options: [
        { label: "A", textEn: "Pure substance", textMr: "शुद्ध पदार्थ", isCorrect: false },
        { label: "B", textEn: "Homogeneous mixture", textMr: "एकसंध मिश्रण", isCorrect: true },
        { label: "C", textEn: "Heterogeneous mixture", textMr: "विषमसंध मिश्रण", isCorrect: false },
        { label: "D", textEn: "Compound", textMr: "संयुग", isCorrect: false },
      ],
    },
    {
      textEn: "In which type of mixture is the Tyndall effect observed?",
      textMr: "टिंडल प्रभाव (Tyndall effect) कशामध्ये दिसतो?",
      explanationEn: "The Tyndall effect is seen in colloids and suspensions, where particles scatter a beam of light making it visible.",
      explanationMr: "टिंडल प्रभाव कोलॉइड व निलंबन यांमध्ये दिसतो. प्रकाश कण विखुरल्यामुळे हा प्रकाशाचा मार्ग दिसतो.",
      options: [
        { label: "A", textEn: "True solution", textMr: "खऱ्या द्रावणात", isCorrect: false },
        { label: "B", textEn: "Colloid", textMr: "कोलॉइड", isCorrect: false },
        { label: "C", textEn: "Suspension", textMr: "निलंबन", isCorrect: false },
        { label: "D", textEn: "Both b and c", textMr: "दोन्ही b व c", isCorrect: true },
      ],
    },
    {
      textEn: "What is distillation used for?",
      textMr: "ऊर्धपातन (Distillation) कशासाठी उपयोग होते?",
      explanationEn: "Distillation separates liquid mixtures by vaporising and condensing components based on different boiling points.",
      explanationMr: "ऊर्धपातन म्हणजे द्रव मिश्रणातील घटक उकळण्याच्या बिंदू वेगळे असल्यास वाफ करून व थंड करून वेगळे करणे.",
      options: [
        { label: "A", textEn: "Separating alloys", textMr: "मिश्र धातू वेगळे करण्यासाठी", isCorrect: false },
        { label: "B", textEn: "Separating liquid mixtures", textMr: "द्रव मिश्रणे वेगळे करण्यासाठी", isCorrect: true },
        { label: "C", textEn: "Separating solids", textMr: "घन पदार्थ वेगळे करण्यासाठी", isCorrect: false },
        { label: "D", textEn: "Separating colours", textMr: "रंग वेगळे करण्यासाठी", isCorrect: false },
      ],
    },
    {
      textEn: "Which of the following is a property of metals?",
      textMr: "खालीलपैकी कोणता गुणधर्म धातूंचा आहे?",
      explanationEn: "Metals are lustrous, ductile, malleable, and good conductors of heat and electricity.",
      explanationMr: "धातू चमकदार, तन्य (ताणता येतात) व घन (ठोका सहन करतात) असतात तसेच उष्णता व विद्युत यांचे सुचालक असतात.",
      options: [
        { label: "A", textEn: "Bad conductors of heat and electricity", textMr: "विद्युत व उष्णतेचे कुचालक", isCorrect: false },
        { label: "B", textEn: "Brittle", textMr: "ठिसूळ", isCorrect: false },
        { label: "C", textEn: "Lustrous and ductile", textMr: "चमकदार व तन्य", isCorrect: true },
        { label: "D", textEn: "Exist as gases", textMr: "वायू स्वरूपात असतात", isCorrect: false },
      ],
    },
    {
      textEn: "Which metal exists in liquid form at room temperature?",
      textMr: "कोणता धातू द्रव स्वरूपात असतो?",
      explanationEn: "Mercury is the only metal that exists as a liquid at room temperature. Its boiling point is 357°C.",
      explanationMr: "पारा (Mercury) हा एकमेव धातू आहे जो सामान्य तापमानात द्रव स्वरूपात असतो. त्याचा उत्कलन बिंदू ३५७°C आहे.",
      options: [
        { label: "A", textEn: "Sodium", textMr: "सोडिअम", isCorrect: false },
        { label: "B", textEn: "Iron", textMr: "लोखंड", isCorrect: false },
        { label: "C", textEn: "Mercury", textMr: "पारा", isCorrect: true },
        { label: "D", textEn: "Copper", textMr: "तांबे", isCorrect: false },
      ],
    },
    {
      textEn: "What is formed when iron rusts in air?",
      textMr: "हवेत लोखंड गंजण्याच्या प्रक्रियेत काय तयार होते?",
      explanationEn: "Rust = Fe₂O₃·xH₂O (hydrated ferric oxide). Iron rusts in the presence of both oxygen and moisture.",
      explanationMr: "गंज = Fe₂O₃·xH₂O (हायड्रेटेड फेरिक ऑक्साइड). ऑक्सिजन व आर्द्रतेच्या उपस्थितीत लोखंड गंजते.",
      options: [
        { label: "A", textEn: "Ferrous oxide", textMr: "फेरस ऑक्साइड", isCorrect: false },
        { label: "B", textEn: "Ferric oxide", textMr: "फेरिक ऑक्साइड", isCorrect: true },
        { label: "C", textEn: "Ferrous chloride", textMr: "फेरस क्लोराइड", isCorrect: false },
        { label: "D", textEn: "Iron carbide", textMr: "लोह कार्बाइड", isCorrect: false },
      ],
    },
    {
      textEn: "Diamond is an allotrope of which element?",
      textMr: "हिरा (Diamond) कशाचे अपरूप (Allotrope) आहे?",
      explanationEn: "Diamond and graphite are both allotropes of carbon. Diamond is the hardest natural substance; graphite conducts electricity.",
      explanationMr: "हिरा व ग्रॅफाइट हे दोन्ही कार्बनचे अपरूप आहेत. हिरा सर्वात कठीण नैसर्गिक पदार्थ आहे, ग्रॅफाइट वीजवाहक आहे.",
      options: [
        { label: "A", textEn: "Silicon", textMr: "सिलिकॉन", isCorrect: false },
        { label: "B", textEn: "Sulfur", textMr: "गंधक", isCorrect: false },
        { label: "C", textEn: "Carbon", textMr: "कार्बन", isCorrect: true },
        { label: "D", textEn: "Nitrogen", textMr: "नायट्रोजन", isCorrect: false },
      ],
    },
    {
      textEn: "Which gases cause acid rain?",
      textMr: "आम्ल पाऊस (Acid rain) कोणत्या वायूंमुळे होतो?",
      explanationEn: "Sulphur dioxide (SO₂) and nitrogen oxides (NOₓ) react with atmospheric moisture to form acid rain.",
      explanationMr: "सल्फर डायऑक्साइड (SO₂) व नायट्रोजन ऑक्साइड (NOₓ) हवेतील आर्द्रतेशी प्रतिक्रिया देऊन आम्ल पाऊस तयार करतात.",
      options: [
        { label: "A", textEn: "Oxygen and Nitrogen", textMr: "ऑक्सिजन व नायट्रोजन", isCorrect: false },
        { label: "B", textEn: "SO₂ and NOₓ", textMr: "SO₂ व NOₓ", isCorrect: true },
        { label: "C", textEn: "CO₂ and O₃", textMr: "CO₂ व O₃", isCorrect: false },
        { label: "D", textEn: "CH₄ and CO", textMr: "CH₄ व CO", isCorrect: false },
      ],
    },
    {
      textEn: "What causes damage to the ozone layer?",
      textMr: "ओझोन थराचे (Ozone layer) नुकसान कशामुळे होते?",
      explanationEn: "CFCs (Chlorofluorocarbons) destroy ozone molecules. The ozone layer protects Earth from UV radiation.",
      explanationMr: "CFC (क्लोरोफ्लुओरोकार्बन) हे वायू ओझोन रेणू नष्ट करतात. ओझोन थर अतिनील किरणांपासून संरक्षण देतो.",
      options: [
        { label: "A", textEn: "CO₂", textMr: "CO₂", isCorrect: false },
        { label: "B", textEn: "Chlorofluorocarbons (CFCs)", textMr: "CFC (क्लोरोफ्लुओरोकार्बन)", isCorrect: true },
        { label: "C", textEn: "SO₂", textMr: "SO₂", isCorrect: false },
        { label: "D", textEn: "CH₄", textMr: "CH₄", isCorrect: false },
      ],
    },
    {
      textEn: "What is the main cause of water pollution?",
      textMr: "जल प्रदूषणाचे मुख्य कारण कोणते?",
      explanationEn: "Industrial effluents, domestic sewage, agricultural chemicals and pesticides are major causes of water pollution.",
      explanationMr: "कारखान्यांचे सांडपाणी, घरगुती सांडपाणी, कृषी रासायनिक खते व कीटकनाशके जलप्रदूषणाची मुख्य कारणे आहेत.",
      options: [
        { label: "A", textEn: "Fishing", textMr: "मासेमारी", isCorrect: false },
        { label: "B", textEn: "Industrial effluents", textMr: "औद्योगिक सांडपाणी", isCorrect: true },
        { label: "C", textEn: "Tourism", textMr: "पर्यटन", isCorrect: false },
        { label: "D", textEn: "Wind speed", textMr: "वाऱ्याची गती", isCorrect: false },
      ],
    },
    {
      textEn: "What does the Richter scale measure?",
      textMr: "रिश्टर स्केल (Richter scale) कशाचे मोजमाप करते?",
      explanationEn: "The Richter scale measures the magnitude of earthquakes. A reading above 7 indicates a major earthquake.",
      explanationMr: "रिश्टर स्केल भूकंपाच्या तीव्रतेचे मोजमाप करते. ७ पेक्षा जास्त रिश्टर स्केल मोठ्या भूकंपाचे लक्षण आहे.",
      options: [
        { label: "A", textEn: "Intensity of storm", textMr: "वादळाची तीव्रता", isCorrect: false },
        { label: "B", textEn: "Intensity of earthquake", textMr: "भूकंपाची तीव्रता", isCorrect: true },
        { label: "C", textEn: "Flood level", textMr: "पुराची पातळी", isCorrect: false },
        { label: "D", textEn: "Volcanic eruption", textMr: "ज्वालामुखीचा उद्रेक", isCorrect: false },
      ],
    },
    {
      textEn: "What causes a tsunami?",
      textMr: "त्सुनामी (Tsunami) कशामुळे होते?",
      explanationEn: "Tsunamis are caused by underwater earthquakes, volcanic eruptions or landslides. 'Tsunami' is Japanese for 'harbour wave'.",
      explanationMr: "समुद्राखालील भूकंप, ज्वालामुखी उद्रेक किंवा भूस्खलनामुळे त्सुनामी होते. त्सुनामी या जपानी शब्दाचा अर्थ 'बंदर लहरी' असा आहे.",
      options: [
        { label: "A", textEn: "Strong winds", textMr: "जोरदार वारा", isCorrect: false },
        { label: "B", textEn: "Underwater earthquake", textMr: "समुद्राखालील भूकंप", isCorrect: true },
        { label: "C", textEn: "Heavy rainfall", textMr: "अतिवृष्टी", isCorrect: false },
        { label: "D", textEn: "Volcanic gases", textMr: "ज्वालामुखी वायू", isCorrect: false },
      ],
    },
    {
      textEn: "When was the National Disaster Management Authority (NDMA) established?",
      textMr: "राष्ट्रीय आपत्ती व्यवस्थापन प्राधिकरण (NDMA) कधी स्थापन झाले?",
      explanationEn: "NDMA was established in 2005 under the Disaster Management Act. The Prime Minister is its chairperson.",
      explanationMr: "NDMA ची स्थापना २००५ मध्ये आपत्ती व्यवस्थापन कायद्यांतर्गत झाली. पंतप्रधान हे त्याचे अध्यक्ष असतात.",
      options: [
        { label: "A", textEn: "2002", textMr: "२००२", isCorrect: false },
        { label: "B", textEn: "2005", textMr: "२००५", isCorrect: true },
        { label: "C", textEn: "2010", textMr: "२०१०", isCorrect: false },
        { label: "D", textEn: "1999", textMr: "१९९९", isCorrect: false },
      ],
    },
    {
      textEn: "Which organelle is called the powerhouse of the cell?",
      textMr: "पेशीचे शक्तीगृह (Powerhouse of cell) कोणाला म्हणतात?",
      explanationEn: "Mitochondria produce ATP energy through respiration, hence called the 'powerhouse of the cell'.",
      explanationMr: "माइटोकॉन्ड्रिया श्वसनाद्वारे ATP ऊर्जा तयार करतात म्हणून त्यांना 'पेशीचे शक्तीगृह' म्हणतात.",
      options: [
        { label: "A", textEn: "Nucleus", textMr: "केंद्रक", isCorrect: false },
        { label: "B", textEn: "Ribosome", textMr: "रायबोसोम", isCorrect: false },
        { label: "C", textEn: "Mitochondria", textMr: "माइटोकॉन्ड्रिया", isCorrect: true },
        { label: "D", textEn: "Golgi body", textMr: "गोल्गी संकुल", isCorrect: false },
      ],
    },
    {
      textEn: "Which organelle is present in plant cells but absent in animal cells?",
      textMr: "वनस्पती पेशीत असणारे पण प्राणी पेशीत नसणारे अंगक कोणते?",
      explanationEn: "Chloroplasts are found only in plant cells. They contain chlorophyll and are the site of photosynthesis.",
      explanationMr: "क्लोरोप्लास्ट फक्त वनस्पती पेशींमध्ये असतात. त्यात क्लोरोफिल असते व प्रकाश संश्लेषण होते.",
      options: [
        { label: "A", textEn: "Mitochondria", textMr: "माइटोकॉन्ड्रिया", isCorrect: false },
        { label: "B", textEn: "Nucleus", textMr: "केंद्रक", isCorrect: false },
        { label: "C", textEn: "Chloroplast", textMr: "क्लोरोप्लास्ट", isCorrect: true },
        { label: "D", textEn: "Ribosome", textMr: "रायबोसोम", isCorrect: false },
      ],
    },
    {
      textEn: "Who first observed cell structure?",
      textMr: "पेशीची रचना सर्वप्रथम कोणी पाहिली?",
      explanationEn: "Robert Hooke first observed cells in a cork slice in 1665 and named them 'cells'.",
      explanationMr: "रॉबर्ट हूक यांनी १६६५ मध्ये कॉर्कच्या तुकड्यात पेशी सर्वप्रथम पाहिल्या व त्यांना 'cell' हे नाव दिले.",
      options: [
        { label: "A", textEn: "Louis Pasteur", textMr: "लूईस पाश्चर", isCorrect: false },
        { label: "B", textEn: "Robert Hooke", textMr: "रॉबर्ट हूक", isCorrect: true },
        { label: "C", textEn: "Schleiden", textMr: "श्लायडेन", isCorrect: false },
        { label: "D", textEn: "Virchow", textMr: "विर्शो", isCorrect: false },
      ],
    },
    {
      textEn: "How many chambers does the human heart have?",
      textMr: "मानवी हृदयाला किती कप्पे (chambers) असतात?",
      explanationEn: "The human heart has four chambers: right and left atria, and right and left ventricles.",
      explanationMr: "मानवी हृदयाला चार कप्पे असतात: उजवे व डावे कर्णिका (Atria) आणि उजवे व डावे जठर (Ventricles).",
      options: [
        { label: "A", textEn: "Two", textMr: "दोन", isCorrect: false },
        { label: "B", textEn: "Three", textMr: "तीन", isCorrect: false },
        { label: "C", textEn: "Four", textMr: "चार", isCorrect: true },
        { label: "D", textEn: "Six", textMr: "सहा", isCorrect: false },
      ],
    },
    {
      textEn: "What is the pigment in red blood cells?",
      textMr: "रक्तातील लाल रक्तपेशींमधील रंगद्रव्य कोणते?",
      explanationEn: "Haemoglobin is an iron-containing protein that gives blood its red colour and carries oxygen.",
      explanationMr: "हिमोग्लोबिन हे लोहयुक्त प्रोटीन रक्तास लाल रंग देते व ऑक्सिजन वाहण्याचे काम करते.",
      options: [
        { label: "A", textEn: "Melanin", textMr: "मेलॅनिन", isCorrect: false },
        { label: "B", textEn: "Haemoglobin", textMr: "हिमोग्लोबिन", isCorrect: true },
        { label: "C", textEn: "Chlorophyll", textMr: "क्लोरोफिल", isCorrect: false },
        { label: "D", textEn: "Bilirubin", textMr: "बिलिरुबिन", isCorrect: false },
      ],
    },
    {
      textEn: "What is the largest gland in the human body?",
      textMr: "मानवातील सर्वात मोठी ग्रंथी (gland) कोणती?",
      explanationEn: "The liver is the largest organ and gland in the human body. Its main functions include bile production and detoxification.",
      explanationMr: "यकृत (Liver) हे मानवी शरीरातील सर्वात मोठे अवयव व ग्रंथी आहे. पित्त निर्मिती, विषाणुनाशन ही मुख्य कार्ये.",
      options: [
        { label: "A", textEn: "Pancreas", textMr: "स्वादुपिंड", isCorrect: false },
        { label: "B", textEn: "Spleen", textMr: "प्लीहा", isCorrect: false },
        { label: "C", textEn: "Liver", textMr: "यकृत", isCorrect: true },
        { label: "D", textEn: "Kidney", textMr: "वृक्क", isCorrect: false },
      ],
    },
    {
      textEn: "What is the pH value of an acid on the pH scale?",
      textMr: "pH स्केलवर आम्लाचे pH किती असते?",
      explanationEn: "pH < 7 = acidic, pH = 7 = neutral, pH > 7 = alkaline. Lemon juice pH ~2; blood pH ~7.4.",
      explanationMr: "pH < 7 = आम्लीय, pH = 7 = उदासीन, pH > 7 = आम्लारीय (क्षारीय). लिंबाचा रस pH ~2, रक्त pH ~7.4.",
      options: [
        { label: "A", textEn: "Greater than 7", textMr: "७ पेक्षा जास्त", isCorrect: false },
        { label: "B", textEn: "7", textMr: "७", isCorrect: false },
        { label: "C", textEn: "Less than 7", textMr: "७ पेक्षा कमी", isCorrect: true },
        { label: "D", textEn: "14", textMr: "१४", isCorrect: false },
      ],
    },
    {
      textEn: "What reaction occurs when an acid and base are mixed?",
      textMr: "आम्ल व आम्लारी एकत्र केल्यावर कोणती प्रक्रिया होते?",
      explanationEn: "Acid + Base → Salt + Water. This is called neutralisation. E.g. HCl + NaOH → NaCl + H₂O.",
      explanationMr: "आम्ल + आम्लारी → मीठ + पाणी. या प्रक्रियेला उदासिनीकरण म्हणतात. उदा. HCl + NaOH → NaCl + H₂O.",
      options: [
        { label: "A", textEn: "Oxidation", textMr: "ऑक्सिडेशन", isCorrect: false },
        { label: "B", textEn: "Neutralisation", textMr: "उदासिनीकरण", isCorrect: true },
        { label: "C", textEn: "Decomposition", textMr: "विघटन", isCorrect: false },
        { label: "D", textEn: "Combination", textMr: "संयोग", isCorrect: false },
      ],
    },
    {
      textEn: "From which source is the natural indicator litmus obtained?",
      textMr: "लिटमस (Litmus) हा नैसर्गिक निर्देशक कुठून मिळतो?",
      explanationEn: "Litmus is obtained from lichens. It turns red in acid and blue in base. Turmeric and red cabbage are also natural indicators.",
      explanationMr: "लिटमस हा लायकेनपासून मिळतो. आम्लात लाल, आम्लारीत निळा होतो. हळद व जांभळा कोबी हेही नैसर्गिक निर्देशक आहेत.",
      options: [
        { label: "A", textEn: "Roses", textMr: "गुलाबाची फुले", isCorrect: false },
        { label: "B", textEn: "Lichens", textMr: "लायकेन", isCorrect: true },
        { label: "C", textEn: "Turmeric", textMr: "हळद", isCorrect: false },
        { label: "D", textEn: "Cabbage", textMr: "कोबी", isCorrect: false },
      ],
    },
    {
      textEn: "Which of the following is a chemical change?",
      textMr: "खालीलपैकी कोणता बदल रासायनिक बदल आहे?",
      explanationEn: "In a chemical change, new substances form. Burning paper produces CO₂, H₂O and ash — it cannot revert to paper.",
      explanationMr: "रासायनिक बदलात नवीन पदार्थ तयार होतात. कागद जळल्यावर CO₂, H₂O, राख तयार होते — हे परत कागद बनत नाही.",
      options: [
        { label: "A", textEn: "Ice melting", textMr: "बर्फ वितळणे", isCorrect: false },
        { label: "B", textEn: "Paper burning", textMr: "कागद जळणे", isCorrect: true },
        { label: "C", textEn: "Glass breaking", textMr: "काच तुटणे", isCorrect: false },
        { label: "D", textEn: "Wax melting", textMr: "मेण वितळणे", isCorrect: false },
      ],
    },
    {
      textEn: "How is an ionic bond formed?",
      textMr: "आयनिक बंध (Ionic bond) कसा तयार होतो?",
      explanationEn: "Ionic bonds form between metals (electron donors) and non-metals (electron acceptors) by electron transfer. E.g. NaCl.",
      explanationMr: "आयनिक बंध धातू (इलेक्ट्रॉन देणारे) व अधातू (इलेक्ट्रॉन घेणारे) यांच्यात इलेक्ट्रॉन हस्तांतरणाने तयार होतो. उदा. NaCl.",
      options: [
        { label: "A", textEn: "Exchange of electrons", textMr: "इलेक्ट्रॉनांची देवाण-घेवाण", isCorrect: true },
        { label: "B", textEn: "Sharing of electrons", textMr: "इलेक्ट्रॉनांचे सहभाजन", isCorrect: false },
        { label: "C", textEn: "Metal-metal bond", textMr: "धातू धातू बंध", isCorrect: false },
        { label: "D", textEn: "Non-metal non-metal bond", textMr: "अधातू अधातू बंध", isCorrect: false },
      ],
    },
    {
      textEn: "What is the SI unit of heat?",
      textMr: "उष्णतेचे SI एकक कोणते?",
      explanationEn: "The SI unit of heat is Joule (J). 1 calorie = 4.18 J. The SI unit of temperature is Kelvin (K).",
      explanationMr: "उष्णतेचे SI एकक जूल (J) आहे. १ कॅलरी = ४.१८ जूल. तापमानाचे SI एकक केल्विन (K) आहे.",
      options: [
        { label: "A", textEn: "Calorie", textMr: "कॅलरी", isCorrect: false },
        { label: "B", textEn: "Joule", textMr: "जूल", isCorrect: true },
        { label: "C", textEn: "Degree", textMr: "डिग्री", isCorrect: false },
        { label: "D", textEn: "Watt", textMr: "वॅट", isCorrect: false },
      ],
    },
    {
      textEn: "What are the three methods of heat transfer?",
      textMr: "उष्णतेच्या प्रसाराच्या तीन पद्धती कोणत्या?",
      explanationEn: "Heat transfers via Conduction (solids), Convection (liquids/gases) and Radiation (vacuum/empty space).",
      explanationMr: "उष्णता वहन (Conduction — घन), संवहन (Convection — द्रव/वायू) व विकिरण (Radiation — निर्वात) या तीन पद्धतींनी पसरते.",
      options: [
        { label: "A", textEn: "Conduction, radiation, refraction", textMr: "संवहन, विकिरण, अपवर्तन", isCorrect: false },
        { label: "B", textEn: "Conduction, convection, radiation", textMr: "वहन, संवहन, विकिरण", isCorrect: true },
        { label: "C", textEn: "Radiation, reflection, refraction", textMr: "विकिरण, परावर्तन, अपवर्तन", isCorrect: false },
        { label: "D", textEn: "Convection, conduction, light", textMr: "संवहन, वहन, प्रकाश", isCorrect: false },
      ],
    },
    {
      textEn: "What is the approximate speed of sound in air?",
      textMr: "ध्वनीचा वेग हवेत साधारणपणे किती असतो?",
      explanationEn: "Speed of sound in air (20°C) is approximately 343 m/s. In water ~1500 m/s. Speed of light is 3×10⁸ m/s.",
      explanationMr: "ध्वनीचा वेग हवेत (२०°C) सुमारे ३४३ m/s असतो. पाण्यात ~१५०० m/s, घन पदार्थात अधिक. प्रकाशाचा वेग ३×१०⁸ m/s.",
      options: [
        { label: "A", textEn: "3×10⁸ m/s", textMr: "३ × १०⁸ m/s", isCorrect: false },
        { label: "B", textEn: "343 m/s", textMr: "३४३ m/s", isCorrect: true },
        { label: "C", textEn: "1500 m/s", textMr: "१५०० m/s", isCorrect: false },
        { label: "D", textEn: "10 m/s", textMr: "१० m/s", isCorrect: false },
      ],
    },
    {
      textEn: "What is the minimum distance of a reflecting surface to hear an echo?",
      textMr: "प्रतिध्वनी (Echo) ऐकण्यासाठी परावर्तक पृष्ठभाग किमान किती अंतरावर असावा?",
      explanationEn:
        "For an echo to be heard, the reflecting surface must be at least 17 metres away, as the human ear needs 0.1 seconds to distinguish sounds.",
      explanationMr: "प्रतिध्वनी ऐकण्यासाठी परावर्तक पृष्ठभाग किमान १७ मीटर दूर असावा कारण मानवी कान ०.१ सेकंदाने वेगळे आवाज ओळखतो.",
      options: [
        { label: "A", textEn: "5 metres", textMr: "५ मीटर", isCorrect: false },
        { label: "B", textEn: "17 metres", textMr: "१७ मीटर", isCorrect: true },
        { label: "C", textEn: "50 metres", textMr: "५० मीटर", isCorrect: false },
        { label: "D", textEn: "1 metre", textMr: "१ मीटर", isCorrect: false },
      ],
    },
    {
      textEn: "What is ultrasound?",
      textMr: "अल्ट्रासाऊंड (Ultrasound) म्हणजे काय?",
      explanationEn: "Human hearing range: 20–20,000 Hz. Ultrasound > 20,000 Hz. Used in medical sonography and SONAR.",
      explanationMr: "मानवी श्रवणक्षमता २०-२०,००० Hz. अल्ट्रासाऊंड > २०,००० Hz. वैद्यकीय सोनोग्राफी व SONAR मध्ये वापरतात.",
      options: [
        { label: "A", textEn: "Sound below 20 Hz", textMr: "२० Hz पेक्षा कमी ध्वनी", isCorrect: false },
        { label: "B", textEn: "Sound above 20,000 Hz", textMr: "२०,००० Hz पेक्षा जास्त ध्वनी", isCorrect: true },
        { label: "C", textEn: "Visible light", textMr: "दृश्यमान प्रकाश", isCorrect: false },
        { label: "D", textEn: "X-rays", textMr: "क्ष किरण", isCorrect: false },
      ],
    },
    {
      textEn: "What type of image is formed in a plane mirror?",
      textMr: "समतल आरशात प्रतिमा कशी असते?",
      explanationEn: "A plane mirror forms a virtual, erect, same-sized, laterally inverted image.",
      explanationMr: "समतल आरशात आभासी (virtual), सरळ (erect) व समान आकाराची बाजू-उलट (laterally inverted) प्रतिमा तयार होते.",
      options: [
        { label: "A", textEn: "Real, inverted", textMr: "वास्तव, उलट", isCorrect: false },
        { label: "B", textEn: "Virtual, erect", textMr: "आभासी, सरळ", isCorrect: true },
        { label: "C", textEn: "Real, erect", textMr: "वास्तव, सरळ", isCorrect: false },
        { label: "D", textEn: "Magnified, inverted", textMr: "मोठी, उलट", isCorrect: false },
      ],
    },
    {
      textEn: "Angle of reflection = ?",
      textMr: "परावर्तनाचा कोन (Angle of reflection) = ?",
      explanationEn: "Law of Reflection: angle of incidence = angle of reflection (both measured from the normal). Valid for all mirrors.",
      explanationMr: "परावर्तनाचा नियम: आपाती कोन = परावर्तनाचा कोन (दोन्ही लंबापासून मोजतात). हे समतल व वक्र आरशांसाठी लागू.",
      options: [
        { label: "A", textEn: "Angle of incidence", textMr: "आपाती कोन", isCorrect: true },
        { label: "B", textEn: "90° − angle of incidence", textMr: "९०° − आपाती कोन", isCorrect: false },
        { label: "C", textEn: "2 × angle of incidence", textMr: "आपाती कोन × २", isCorrect: false },
        { label: "D", textEn: "Zero", textMr: "शून्य", isCorrect: false },
      ],
    },
    {
      textEn: "Which mirror is used as a rear-view mirror in vehicles?",
      textMr: "वाहनांच्या मागील बाजूस पाहण्यासाठी कोणता आरसा वापरतात?",
      explanationEn: "Convex mirrors produce smaller images with a wider field of view, making them ideal for rear-view mirrors in vehicles.",
      explanationMr: "उत्तल आरशात (Convex mirror) प्रतिमा लहान व मोठ्या दृश्यक्षेत्रात दिसते म्हणून वाहनांमध्ये rear-view mirror म्हणून वापरतात.",
      options: [
        { label: "A", textEn: "Concave", textMr: "अवतल", isCorrect: false },
        { label: "B", textEn: "Convex", textMr: "उत्तल", isCorrect: true },
        { label: "C", textEn: "Plane", textMr: "समतल", isCorrect: false },
        { label: "D", textEn: "Cylindrical", textMr: "बेलनाकार", isCorrect: false },
      ],
    },
    {
      textEn: "What type of polymer is nylon?",
      textMr: "नायलॉन (Nylon) कोणत्या प्रकारचे बहुवारिक (polymer) आहे?",
      explanationEn: "Nylon is a synthetic polymer — the first synthetic fibre. It is used in clothing, ropes and toothbrushes.",
      explanationMr: "नायलॉन हे संश्लेषित बहुवारिक आहे. हे पहिले संश्लेषित तंतू (fibre) आहे. कपडे, दोरी, टूथब्रश यात वापरतात.",
      options: [
        { label: "A", textEn: "Natural", textMr: "नैसर्गिक", isCorrect: false },
        { label: "B", textEn: "Synthetic", textMr: "संश्लेषित", isCorrect: true },
        { label: "C", textEn: "Semi-synthetic", textMr: "अर्ध-संश्लेषित", isCorrect: false },
        { label: "D", textEn: "Biological", textMr: "जैविक", isCorrect: false },
      ],
    },
    {
      textEn: "Glass is a mixture of which substances?",
      textMr: "काच (Glass) हे कशाचे मिश्रण आहे?",
      explanationEn: "Ordinary glass is made by fusing silica (SiO₂), soda (Na₂CO₃) and limestone (CaCO₃). Glass is an amorphous solid.",
      explanationMr: "साध्या काचेत सिलिका (SiO₂), सोडा (Na₂CO₃) व चुना (CaCO₃) यांचे मिश्रण वितळवून बनवतात. काच अनाकारी (amorphous) घन आहे.",
      options: [
        { label: "A", textEn: "Sand and water", textMr: "वाळू व पाणी", isCorrect: false },
        { label: "B", textEn: "Silica, soda, limestone", textMr: "सिलिका, सोडा, चुना", isCorrect: true },
        { label: "C", textEn: "Cement and sand", textMr: "सिमेंट व वाळू", isCorrect: false },
        { label: "D", textEn: "Plastic and glass", textMr: "प्लास्टिक व काच", isCorrect: false },
      ],
    },
    {
      textEn: "How does energy flow in a food chain?",
      textMr: "अन्न साखळीत (Food chain) ऊर्जेचा प्रवाह कसा होतो?",
      explanationEn: "Energy flows: Producers (plants) → Primary consumers → Secondary consumers → Tertiary consumers. ~10% energy passes to each level.",
      explanationMr: "ऊर्जेचा प्रवाह: उत्पादक (वनस्पती) → प्राथमिक ग्राहक → द्वितीय ग्राहक → तृतीय ग्राहक. प्रत्येक स्तरावर ~१०% ऊर्जा जाते.",
      options: [
        { label: "A", textEn: "Consumer → Producer", textMr: "ग्राहक → उत्पादक", isCorrect: false },
        { label: "B", textEn: "Producer → Consumer", textMr: "उत्पादक → ग्राहक", isCorrect: true },
        { label: "C", textEn: "Decomposer → Producer", textMr: "विघटक → उत्पादक", isCorrect: false },
        { label: "D", textEn: "Consumer → Decomposer", textMr: "ग्राहक → विघटक", isCorrect: false },
      ],
    },
    {
      textEn: "What does biodiversity mean?",
      textMr: "जैव-विविधता (Biodiversity) म्हणजे काय?",
      explanationEn: "Biodiversity refers to the variety of all living species on Earth, their genetic diversity, and the ecosystems they form.",
      explanationMr: "जैव-विविधता म्हणजे पृथ्वीवरील सर्व सजीव प्रजाती, त्यांचे अनुवांशिक वैविध्य व परिसंस्था यांचे विविधता.",
      options: [
        { label: "A", textEn: "Diversity of one species", textMr: "एकाच प्रजातीची विविधता", isCorrect: false },
        { label: "B", textEn: "Diversity of life species on Earth", textMr: "पृथ्वीवरील जीव-प्रजातींची विविधता", isCorrect: true },
        { label: "C", textEn: "Living in one ecosystem", textMr: "एकाच परिसंस्थेत वास", isCorrect: false },
        { label: "D", textEn: "Linguistic diversity", textMr: "भाषिक विविधता", isCorrect: false },
      ],
    },
    {
      textEn: "Which type of ecosystem has the highest biodiversity?",
      textMr: "कुठल्या प्रकारच्या परिसंस्थेत सर्वाधिक जैव-विविधता असते?",
      explanationEn: "Tropical rainforests have the highest biodiversity on Earth. The Amazon rainforest is the largest example.",
      explanationMr: "उष्णकटिबंधीय पर्जन्यवनात (Tropical Rainforest) जगातील सर्वाधिक जैव-विविधता असते. अमेझॉन वन हे सर्वात मोठे उदाहरण.",
      options: [
        { label: "A", textEn: "Desert", textMr: "वाळवंट", isCorrect: false },
        { label: "B", textEn: "Polar region", textMr: "ध्रुवीय प्रदेश", isCorrect: false },
        { label: "C", textEn: "Tropical rainforest", textMr: "उष्णकटिबंधीय पर्जन्यवन", isCorrect: true },
        { label: "D", textEn: "Mountain region", textMr: "पर्वतीय प्रदेश", isCorrect: false },
      ],
    },
    {
      textEn: "Which is the largest planet in the solar system?",
      textMr: "सूर्यमालेतील सर्वात मोठा ग्रह कोणता?",
      explanationEn: "Jupiter is the largest planet in the solar system. It is a gas giant with over 79 known moons.",
      explanationMr: "गुरू (Jupiter) हा सूर्यमालेतील सर्वात मोठा ग्रह आहे. तो वायू महाकाय असून त्याचे ७९ पेक्षा जास्त उपग्रह आहेत.",
      options: [
        { label: "A", textEn: "Earth", textMr: "पृथ्वी", isCorrect: false },
        { label: "B", textEn: "Saturn", textMr: "शनी", isCorrect: false },
        { label: "C", textEn: "Jupiter", textMr: "गुरू", isCorrect: true },
        { label: "D", textEn: "Neptune", textMr: "नेप्च्यून", isCorrect: false },
      ],
    },
    {
      textEn: "What happens when a star dies?",
      textMr: "तारा मेल्यावर त्याचे काय होते?",
      explanationEn: "Massive stars end in a supernova explosion forming a black hole or neutron star. Small stars become white dwarfs.",
      explanationMr: "मोठ्या ताऱ्याचा अंत सुपरनोव्हा स्फोटाने होतो व त्यातून कृष्णविवर (Black hole) किंवा न्यूट्रॉन तारा तयार होतो. लहान तारे श्वेत बटू बनतात.",
      options: [
        { label: "A", textEn: "Becomes Earth", textMr: "पृथ्वीत रूपांतर", isCorrect: false },
        { label: "B", textEn: "Black hole or neutron star", textMr: "कृष्णविवर किंवा न्यूट्रॉन तारा", isCorrect: true },
        { label: "C", textEn: "Becomes a planet", textMr: "ग्रह बनतो", isCorrect: false },
        { label: "D", textEn: "Disappears", textMr: "अदृश्य होतो", isCorrect: false },
      ],
    },
    {
      textEn: "What is a light year?",
      textMr: "प्रकाश वर्ष (Light year) म्हणजे काय?",
      explanationEn: "One light year = 9.46 × 10¹² km. It is a unit of distance, not time. Speed of light = 3 × 10⁸ m/s.",
      explanationMr: "एक प्रकाश वर्ष = ९.४६ × १०¹² किमी. हे अंतराचे एकक आहे, वेळाचे नाही. प्रकाशाचा वेग ३ × १०⁸ m/s आहे.",
      options: [
        { label: "A", textEn: "Unit of time", textMr: "वेळाचे एकक", isCorrect: false },
        { label: "B", textEn: "Distance light travels in one year", textMr: "प्रकाश एका वर्षात जितके अंतर जातो", isCorrect: true },
        { label: "C", textEn: "Age of a star", textMr: "ताऱ्याचे वय", isCorrect: false },
        { label: "D", textEn: "Unit of temperature", textMr: "तापमानाचे एकक", isCorrect: false },
      ],
    },
  ],
};

export default data;
