import type { QuestionSetInput } from "./types";

// Source: All questions & answer/AMVI_Std8_HC_English.pdf + AMVI_Std8_HC_Marathi.pdf
// Both PDFs share identical question numbering/options/answers (65 MCQs, History Ch 1-14 + Civics Ch 1-5).
const data: QuestionSetInput = {
  standard: { code: "STD8", nameEn: "Standard 8", nameMr: "इयत्ता ८वी", sortOrder: 8 },
  subject: { code: "HC", nameEn: "History & Civics", nameMr: "इतिहास व नागरिकशास्त्र", sortOrder: 3 },
  questions: [
    {
      textEn: "What does archaeology study?",
      textMr: "पुरातत्त्वशास्त्र कशाचा अभ्यास करते?",
      explanationEn: "Archaeology studies old objects, excavations, and remnants to unravel history.",
      explanationMr: "पुरातत्त्वशास्त्र हे जुन्या वस्तू, उत्खनन व अवशेषांचा अभ्यास करते आणि त्यातून इतिहास उलगडते.",
      options: [
        { label: "A", textEn: "Literature", textMr: "साहित्याचा", isCorrect: false },
        { label: "B", textEn: "Old objects and excavations", textMr: "जुन्या वस्तू व उत्खननाचा", isCorrect: true },
        { label: "C", textEn: "Geography", textMr: "भूगोलाचा", isCorrect: false },
        { label: "D", textEn: "Mathematics", textMr: "गणिताचा", isCorrect: false },
      ],
    },
    {
      textEn: "Caves and inscriptions are examples of which type of historical source?",
      textMr: "लेणी व शिलालेख हे इतिहासाच्या कोणत्या साधनांचे उदाहरण आहे?",
      explanationEn: "Caves, inscriptions, coins, and statues are types of archaeological sources.",
      explanationMr: "लेणी, शिलालेख, नाणी, मूर्ती इत्यादी पुरातत्त्वीय साधनांचे प्रकार आहेत.",
      options: [
        { label: "A", textEn: "Literary", textMr: "साहित्यिक", isCorrect: false },
        { label: "B", textEn: "Archaeological", textMr: "पुरातत्त्वीय", isCorrect: true },
        { label: "C", textEn: "Foreign", textMr: "परकीय", isCorrect: false },
        { label: "D", textEn: "Oral", textMr: "मौखिक", isCorrect: false },
      ],
    },
    {
      textEn: "What sources give names like Stone Age and Copper-Stone Age?",
      textMr: "अश्मयुग, ताम्रपाषाण युग या नावांमागे कोणती साधने आहेत?",
      explanationEn: "The tools and utensils used in that period give us the name of the age.",
      explanationMr: "त्या काळात वापरल्या जाणाऱ्या हत्यारे व भांड्यांवरून आपण त्या युगाचे नाव देतो.",
      options: [
        { label: "A", textEn: "Inscriptions", textMr: "शिलालेख", isCorrect: false },
        { label: "B", textEn: "Coins", textMr: "नाणी", isCorrect: false },
        { label: "C", textEn: "Tools and utensils", textMr: "हत्यारे व भांडी", isCorrect: true },
        { label: "D", textEn: "Copper plates", textMr: "ताम्रपट", isCorrect: false },
      ],
    },
    {
      textEn: "Accounts of foreign travelers are which type of historical source?",
      textMr: "परकीय प्रवाशांचे वृत्तांत इतिहासाचे कोणते साधन आहे?",
      explanationEn: "Accounts of foreign travelers like Megasthenes, Fa-hien, Huien-Tsang are examples of foreign sources.",
      explanationMr: "मेगॅस्थेनिस, फाह्यान, ह्युएनत्सांग यांसारख्या परकीय प्रवाशांचे वृत्तांत हे परकीय साधनांचे उदाहरण आहे.",
      options: [
        { label: "A", textEn: "Archaeological", textMr: "पुरातत्त्वीय", isCorrect: false },
        { label: "B", textEn: "Literary", textMr: "साहित्यिक", isCorrect: false },
        { label: "C", textEn: "Foreign", textMr: "परकीय", isCorrect: true },
        { label: "D", textEn: "Oral", textMr: "मौखिक", isCorrect: false },
      ],
    },
    {
      textEn: "Folk songs, folktales, and traditions are included in which source?",
      textMr: "लोकगीते, लोककथा व प्रथा यांचा समावेश कोणत्या साधनात होतो?",
      explanationEn: "Oral tradition includes folk songs, folktales, proverbs, and religious customs.",
      explanationMr: "मौखिक परंपरेत लोकगीते, लोककथा, म्हणी व धार्मिक प्रथा यांचा समावेश होतो.",
      options: [
        { label: "A", textEn: "Archaeological", textMr: "पुरातत्त्वीय", isCorrect: false },
        { label: "B", textEn: "Foreign", textMr: "परकीय", isCorrect: false },
        { label: "C", textEn: "Oral tradition", textMr: "मौखिक परंपरा", isCorrect: true },
        { label: "D", textEn: "Literary", textMr: "साहित्यिक", isCorrect: false },
      ],
    },
    {
      textEn: "When did Vasco da Gama first arrive in India?",
      textMr: "वास्को द गामा भारतात प्रथम केव्हा आला?",
      explanationEn: "Portuguese sailor Vasco da Gama reached Calicut port in 1498 AD, discovering the sea route between India and Europe.",
      explanationMr: "पोर्तुगीज नाविक वास्को द गामा इ.स. १४९८ मध्ये कालिकत बंदरात पोहोचला आणि भारत-युरोप सागरी मार्ग शोधला.",
      options: [
        { label: "A", textEn: "1492 AD", textMr: "इ.स. १४९२", isCorrect: false },
        { label: "B", textEn: "1498 AD", textMr: "इ.स. १४९८", isCorrect: true },
        { label: "C", textEn: "1510 AD", textMr: "इ.स. १५१०", isCorrect: false },
        { label: "D", textEn: "1600 AD", textMr: "इ.स. १६००", isCorrect: false },
      ],
    },
    {
      textEn: "Who established the East India Company?",
      textMr: "ईस्ट इंडिया कंपनीची स्थापना कोणी केली?",
      explanationEn: "The British established the East India Company in 1600 AD and began trading in India.",
      explanationMr: "इंग्रजांनी इ.स. १६०० मध्ये ईस्ट इंडिया कंपनीची स्थापना केली आणि भारतात व्यापार करण्यास सुरुवात केली.",
      options: [
        { label: "A", textEn: "Portuguese", textMr: "पोर्तुगीज", isCorrect: false },
        { label: "B", textEn: "French", textMr: "फ्रेंच", isCorrect: false },
        { label: "C", textEn: "British", textMr: "इंग्रज", isCorrect: true },
        { label: "D", textEn: "Dutch", textMr: "डच", isCorrect: false },
      ],
    },
    {
      textEn: "Where was the first British factory (trading post) established in India?",
      textMr: "भारतातील पहिली इंग्रज वखार कोठे स्थापन झाली?",
      explanationEn: "The British established their first factory at Surat in 1613 AD.",
      explanationMr: "इंग्रजांनी इ.स. १६१३ मध्ये सुरत येथे पहिली वखार स्थापन केली.",
      options: [
        { label: "A", textEn: "Mumbai", textMr: "मुंबई", isCorrect: false },
        { label: "B", textEn: "Surat", textMr: "सुरत", isCorrect: true },
        { label: "C", textEn: "Kolkata", textMr: "कोलकाता", isCorrect: false },
        { label: "D", textEn: "Madras", textMr: "मद्रास", isCorrect: false },
      ],
    },
    {
      textEn: "In which year did the Battle of Plassey take place?",
      textMr: "प्लासीची लढाई कोणत्या वर्षी झाली?",
      explanationEn: "The Battle of Plassey was fought in 1757 AD in which the British defeated the Nawab of Bengal and established political power in India.",
      explanationMr: "इ.स. १७५७ मध्ये प्लासीची लढाई झाली ज्यात इंग्रजांनी बंगालच्या नवाबाचा पराभव केला आणि भारतात राजकीय सत्ता प्रस्थापित केली.",
      options: [
        { label: "A", textEn: "1720 AD", textMr: "इ.स. १७२०", isCorrect: false },
        { label: "B", textEn: "1740 AD", textMr: "इ.स. १७४०", isCorrect: false },
        { label: "C", textEn: "1757 AD", textMr: "इ.स. १७५७", isCorrect: true },
        { label: "D", textEn: "1764 AD", textMr: "इ.स. १७६४", isCorrect: false },
      ],
    },
    {
      textEn: "Which European power controlled Goa?",
      textMr: "गोव्यावर कोणत्या युरोपियन सत्तेचा ताबा होता?",
      explanationEn: "The Portuguese conquered Goa in 1510 AD and ruled it until 1961 AD.",
      explanationMr: "पोर्तुगीजांनी इ.स. १५१० मध्ये गोवा जिंकले आणि इ.स. १९६१ पर्यंत त्यावर राज्य केले.",
      options: [
        { label: "A", textEn: "British", textMr: "इंग्रज", isCorrect: false },
        { label: "B", textEn: "French", textMr: "फ्रेंच", isCorrect: false },
        { label: "C", textEn: "Dutch", textMr: "डच", isCorrect: false },
        { label: "D", textEn: "Portuguese", textMr: "पोर्तुगीज", isCorrect: true },
      ],
    },
    {
      textEn: "Who introduced the Ryotwari system?",
      textMr: "रयतवारी पद्धत कोणी सुरू केली?",
      explanationEn: "Thomas Munro introduced the Ryotwari system in Madras province where farmers paid land revenue directly to the government.",
      explanationMr: "थॉमस मुन्रो यांनी मद्रास प्रांतात रयतवारी पद्धत सुरू केली ज्यात शेतकरी थेट सरकारला जमीन महसूल देत असे.",
      options: [
        { label: "A", textEn: "Cornwallis", textMr: "कॉर्नवॉलिस", isCorrect: false },
        { label: "B", textEn: "Thomas Munro", textMr: "थॉमस मुन्रो", isCorrect: true },
        { label: "C", textEn: "Warren Hastings", textMr: "वॉरन हेस्टिंग्ज", isCorrect: false },
        { label: "D", textEn: "Lord Dalhousie", textMr: "लॉर्ड डलहौसी", isCorrect: false },
      ],
    },
    {
      textEn: "Which Governor-General introduced the Permanent Settlement?",
      textMr: "कायमधारा पद्धत कोणत्या गव्हर्नर जनरलने सुरू केली?",
      explanationEn: "Lord Cornwallis introduced the Permanent Settlement in Bengal in 1793 AD.",
      explanationMr: "लॉर्ड कॉर्नवॉलिसने इ.स. १७९३ मध्ये बंगालमध्ये कायमधारा पद्धत सुरू केली.",
      options: [
        { label: "A", textEn: "Warren Hastings", textMr: "वॉरन हेस्टिंग्ज", isCorrect: false },
        { label: "B", textEn: "Lord Cornwallis", textMr: "लॉर्ड कॉर्नवॉलिस", isCorrect: true },
        { label: "C", textEn: "Lord Dalhousie", textMr: "लॉर्ड डलहौसी", isCorrect: false },
        { label: "D", textEn: "Lord Curzon", textMr: "लॉर्ड कर्झन", isCorrect: false },
      ],
    },
    {
      textEn: "What was the effect of British economic policies on Indian craftsmen?",
      textMr: "ब्रिटिशांच्या आर्थिक धोरणामुळे भारतीय कारागीरांवर काय परिणाम झाला?",
      explanationEn: "The British brought cheap machine-made cloth to India, which destroyed the livelihood of Indian weavers and craftsmen.",
      explanationMr: "ब्रिटिशांनी स्वस्त यंत्रनिर्मित कापड भारतात आणले, त्यामुळे भारतीय विणकर व कारागीर देशोधडीला लागले.",
      options: [
        { label: "A", textEn: "They got government jobs", textMr: "त्यांना सरकारी नोकऱ्या मिळाल्या", isCorrect: false },
        { label: "B", textEn: "Their industries were destroyed", textMr: "त्यांची उद्योगे नष्ट झाली", isCorrect: true },
        { label: "C", textEn: "Their income increased", textMr: "त्यांचे उत्पन्न वाढले", isCorrect: false },
        { label: "D", textEn: "They went abroad", textMr: "ते परदेशात गेले", isCorrect: false },
      ],
    },
    {
      textEn: "In which year did railways start in India?",
      textMr: "भारतात रेल्वेची सुरुवात कोणत्या वर्षी झाली?",
      explanationEn: "India's first railway ran from Mumbai to Thane in 1853 AD.",
      explanationMr: "भारतात पहिली रेल्वे इ.स. १८५३ मध्ये मुंबई ते ठाणे धावली.",
      options: [
        { label: "A", textEn: "1835 AD", textMr: "इ.स. १८३५", isCorrect: false },
        { label: "B", textEn: "1845 AD", textMr: "इ.स. १८४५", isCorrect: false },
        { label: "C", textEn: "1853 AD", textMr: "इ.स. १८५३", isCorrect: true },
        { label: "D", textEn: "1865 AD", textMr: "इ.स. १८६५", isCorrect: false },
      ],
    },
    {
      textEn: "Which language became standard in India due to Macaulay's education policy?",
      textMr: "मेकॉलेच्या शिक्षण धोरणाने भारतात कोणती भाषा प्रमाण बनली?",
      explanationEn: "Lord Macaulay introduced English-medium education in 1835 AD, making English the language of administration and education in India.",
      explanationMr: "लॉर्ड मेकॉलेने इ.स. १८३५ मध्ये इंग्रजी माध्यमातील शिक्षण लागू केले ज्यामुळे इंग्रजी भारतात प्रशासनाची व शिक्षणाची भाषा बनली.",
      options: [
        { label: "A", textEn: "Marathi", textMr: "मराठी", isCorrect: false },
        { label: "B", textEn: "Sanskrit", textMr: "संस्कृत", isCorrect: false },
        { label: "C", textEn: "English", textMr: "इंग्रजी", isCorrect: true },
        { label: "D", textEn: "Urdu", textMr: "उर्दू", isCorrect: false },
      ],
    },
    {
      textEn: "What was the immediate cause of the 1857 revolt?",
      textMr: "१८५७ च्या उठावाची तात्कालिक कारण काय होते?",
      explanationEn: "Rumors that Enfield rifle cartridges were greased with cow and pig fat caused soldiers to revolt.",
      explanationMr: "एनफिल्ड रायफलच्या काडतुसांना गाय व डुक्कर यांच्या चरबीचा वापर झाल्याच्या अफवेमुळे सैनिकांनी उठाव केला.",
      options: [
        { label: "A", textEn: "Land revenue", textMr: "जमीन महसूल", isCorrect: false },
        { label: "B", textEn: "Greased cartridges", textMr: "चरबीयुक्त काडतुसे", isCorrect: true },
        { label: "C", textEn: "Railway construction", textMr: "रेल्वे बांधणी", isCorrect: false },
        { label: "D", textEn: "English education", textMr: "इंग्रजी शिक्षण", isCorrect: false },
      ],
    },
    {
      textEn: "Where did the 1857 revolt begin?",
      textMr: "१८५७ च्या उठावाची सुरुवात कोठून झाली?",
      explanationEn: "The 1857 revolt began at Meerut on May 10, 1857.",
      explanationMr: "१८५७ च्या उठावाची सुरुवात १० मे १८५७ रोजी मेरठ येथून झाली.",
      options: [
        { label: "A", textEn: "Delhi", textMr: "दिल्ली", isCorrect: false },
        { label: "B", textEn: "Meerut", textMr: "मेरठ", isCorrect: true },
        { label: "C", textEn: "Lucknow", textMr: "लखनऊ", isCorrect: false },
        { label: "D", textEn: "Kanpur", textMr: "कानपूर", isCorrect: false },
      ],
    },
    {
      textEn: "In which revolt did Rani Lakshmibai of Jhansi participate?",
      textMr: "झाशीच्या राणी लक्ष्मीबाईने कोणत्या उठावात भाग घेतला?",
      explanationEn: "Rani Lakshmibai participated in the 1857 revolt and bravely fought against the British.",
      explanationMr: "राणी लक्ष्मीबाईने इ.स. १८५७ च्या उठावात सहभाग घेऊन इंग्रजांविरुद्ध शूरपणे लढा दिला.",
      options: [
        { label: "A", textEn: "1842 revolt", textMr: "इ.स. १८४२ चा उठाव", isCorrect: false },
        { label: "B", textEn: "1857 revolt", textMr: "इ.स. १८५७ चा उठाव", isCorrect: true },
        { label: "C", textEn: "1875 revolt", textMr: "इ.स. १८७५ चा उठाव", isCorrect: false },
        { label: "D", textEn: "1885 revolt", textMr: "इ.स. १८८५ चा उठाव", isCorrect: false },
      ],
    },
    {
      textEn: "After 1857, who took over the administration of India?",
      textMr: "१८५७ नंतर भारताचा कारभार कोणाकडे आला?",
      explanationEn: "After the 1857 revolt, the British government transferred administration of India from the East India Company directly to the British Crown.",
      explanationMr: "१८५७ च्या उठावानंतर इंग्रज सरकारने ईस्ट इंडिया कंपनीकडून भारताचा कारभार थेट ब्रिटिश राजमुकुटाकडे घेतला.",
      options: [
        { label: "A", textEn: "East India Company", textMr: "ईस्ट इंडिया कंपनी", isCorrect: false },
        { label: "B", textEn: "British Parliament", textMr: "ब्रिटिश संसद", isCorrect: false },
        { label: "C", textEn: "British Crown", textMr: "ब्रिटिश राजमुकुट (Crown)", isCorrect: true },
        { label: "D", textEn: "Mughal Emperor", textMr: "मुघल सम्राट", isCorrect: false },
      ],
    },
    {
      textEn: "Where did Nanasaheb Peshwa lead the revolt?",
      textMr: "नानासाहेब पेशवे यांनी कोठे उठाव केला?",
      explanationEn: "Nanasaheb Peshwa led the 1857 revolt at Kanpur.",
      explanationMr: "नानासाहेब पेशवे यांनी कानपूर येथे इ.स. १८५७ च्या उठावाचे नेतृत्व केले.",
      options: [
        { label: "A", textEn: "Jhansi", textMr: "झाशी", isCorrect: false },
        { label: "B", textEn: "Delhi", textMr: "दिल्ली", isCorrect: false },
        { label: "C", textEn: "Kanpur", textMr: "कानपूर", isCorrect: true },
        { label: "D", textEn: "Lucknow", textMr: "लखनऊ", isCorrect: false },
      ],
    },
    {
      textEn: "Which organization did Mahatma Jotirao Phule establish?",
      textMr: "महात्मा जोतीराव फुले यांनी कोणती संस्था स्थापन केली?",
      explanationEn: "Mahatma Phule established the Satyashodhak Samaj in 1873 AD to bring justice to lower castes and communities.",
      explanationMr: "महात्मा फुले यांनी इ.स. १८७३ मध्ये सत्यशोधक समाजाची स्थापना केली जेणेकरून खालच्या जाती-जमातींना न्याय मिळावा.",
      options: [
        { label: "A", textEn: "Brahmo Samaj", textMr: "ब्राह्मो समाज", isCorrect: false },
        { label: "B", textEn: "Arya Samaj", textMr: "आर्य समाज", isCorrect: false },
        { label: "C", textEn: "Satyashodhak Samaj", textMr: "सत्यशोधक समाज", isCorrect: true },
        { label: "D", textEn: "Prarthana Samaj", textMr: "प्रार्थना समाज", isCorrect: false },
      ],
    },
    {
      textEn: "For abolishing which practice did Raja Ram Mohan Roy strive?",
      textMr: "राजा राममोहन रॉय यांनी कोणती प्रथा बंद करण्यासाठी प्रयत्न केले?",
      explanationEn: "Raja Ram Mohan Roy campaigned against Sati and the practice was legally abolished in 1829 AD.",
      explanationMr: "राजा राममोहन रॉय यांनी सतीप्रथेविरुद्ध मोहीम उघडली आणि इ.स. १८२९ मध्ये ही प्रथा कायद्याने बंद करण्यात आली.",
      options: [
        { label: "A", textEn: "Child marriage", textMr: "बालविवाह", isCorrect: false },
        { label: "B", textEn: "Sati practice", textMr: "सतीप्रथा", isCorrect: true },
        { label: "C", textEn: "Caste discrimination", textMr: "जातिभेद", isCorrect: false },
        { label: "D", textEn: "Forced labour", textMr: "बेगारी", isCorrect: false },
      ],
    },
    {
      textEn: "Which organization did Swami Vivekananda establish?",
      textMr: "स्वामी विवेकानंद यांनी कोणत्या संस्थेची स्थापना केली?",
      explanationEn: "Swami Vivekananda established the Ramakrishna Mission in 1897 AD.",
      explanationMr: "स्वामी विवेकानंद यांनी इ.स. १८९७ मध्ये रामकृष्ण मिशनची स्थापना केली.",
      options: [
        { label: "A", textEn: "Ramakrishna Mission", textMr: "रामकृष्ण मिशन", isCorrect: true },
        { label: "B", textEn: "Brahmo Samaj", textMr: "ब्राह्मो समाज", isCorrect: false },
        { label: "C", textEn: "Arya Samaj", textMr: "आर्य समाज", isCorrect: false },
        { label: "D", textEn: "Dayananda Mission", textMr: "दयानंद मिशन", isCorrect: false },
      ],
    },
    {
      textEn: "In which field did Maharshi Dhondo Keshav Karve do important work?",
      textMr: "महर्षी धोंडो केशव कर्वे यांनी कोणत्या क्षेत्रात महत्त्वाचे कार्य केले?",
      explanationEn: "Maharshi Karve tirelessly worked for widow remarriage and women's education, establishing schools for women.",
      explanationMr: "महर्षी कर्वे यांनी विधवा पुनर्विवाह व स्त्री शिक्षणासाठी अथक कार्य केले आणि स्त्रियांसाठी विद्यालय उभारले.",
      options: [
        { label: "A", textEn: "Farmer reform", textMr: "शेतकरी सुधारणा", isCorrect: false },
        { label: "B", textEn: "Women's education", textMr: "स्त्री शिक्षण", isCorrect: true },
        { label: "C", textEn: "Industrial development", textMr: "औद्योगिक विकास", isCorrect: false },
        { label: "D", textEn: "Political reform", textMr: "राजकीय सुधारणा", isCorrect: false },
      ],
    },
    {
      textEn: "Which movement did Dr. Babasaheb Ambedkar build?",
      textMr: "डॉ. बाबासाहेब आंबेडकर यांनी कोणती चळवळ उभारली?",
      explanationEn: "Dr. Ambedkar built a movement for the abolition of untouchability and rights of Dalits, and became the architect of the Indian Constitution.",
      explanationMr: "डॉ. आंबेडकर यांनी अस्पृश्यतानिवारण व दलितांच्या हक्कांसाठी चळवळ उभारली आणि भारतीय राज्यघटनेचे शिल्पकार बनले.",
      options: [
        { label: "A", textEn: "Swaraj movement", textMr: "स्वराज्य चळवळ", isCorrect: false },
        { label: "B", textEn: "Dalit upliftment movement", textMr: "दलित उद्धार चळवळ", isCorrect: true },
        { label: "C", textEn: "Farmer's movement", textMr: "शेतकरी चळवळ", isCorrect: false },
        { label: "D", textEn: "Non-cooperation movement", textMr: "असहकार चळवळ", isCorrect: false },
      ],
    },
    {
      textEn: "In which year was the Indian National Congress established?",
      textMr: "भारतीय राष्ट्रीय काँग्रेसची स्थापना कोणत्या वर्षी झाली?",
      explanationEn: "The Indian National Congress was founded in 1885 AD by Allan Octavian Hume in Mumbai.",
      explanationMr: "भारतीय राष्ट्रीय काँग्रेसची स्थापना इ.स. १८८५ मध्ये अॅलन ऑक्टेव्हियन ह्यूम यांनी मुंबई येथे केली.",
      options: [
        { label: "A", textEn: "1875 AD", textMr: "इ.स. १८७५", isCorrect: false },
        { label: "B", textEn: "1885 AD", textMr: "इ.स. १८८५", isCorrect: true },
        { label: "C", textEn: "1895 AD", textMr: "इ.स. १८९५", isCorrect: false },
        { label: "D", textEn: "1905 AD", textMr: "इ.स. १९०५", isCorrect: false },
      ],
    },
    {
      textEn: "In which year did Bal Gangadhar Tilak give the slogan 'Swaraj is my birthright'?",
      textMr: "बाल गंगाधर टिळकांनी 'स्वराज्य हा माझा जन्मसिद्ध हक्क आहे' हे घोषवाक्य कोणत्या वर्षी दिले?",
      explanationEn: "Lokmanya Tilak gave the famous declaration 'Swaraj is my birthright and I shall have it' in 1907 AD.",
      explanationMr: "लोकमान्य टिळकांनी इ.स. १९०७ मध्ये 'स्वराज्य हा माझा जन्मसिद्ध हक्क आहे आणि तो मी मिळवणारच' असे प्रसिद्ध उद्गार काढले.",
      options: [
        { label: "A", textEn: "1895 AD", textMr: "इ.स. १८९५", isCorrect: false },
        { label: "B", textEn: "1905 AD", textMr: "इ.स. १९०५", isCorrect: false },
        { label: "C", textEn: "1907 AD", textMr: "इ.स. १९०७", isCorrect: true },
        { label: "D", textEn: "1915 AD", textMr: "इ.स. १९१५", isCorrect: false },
      ],
    },
    {
      textEn: "Which organization did Gopal Krishna Gokhale establish?",
      textMr: "गोपाळ कृष्ण गोखले यांनी कोणती संस्था स्थापन केली?",
      explanationEn: "Gopal Krishna Gokhale established the Servants of India Society in 1905 AD.",
      explanationMr: "गोपाळ कृष्ण गोखले यांनी इ.स. १९०५ मध्ये भारत सेवक समाजाची स्थापना केली.",
      options: [
        { label: "A", textEn: "Seva Sadan", textMr: "सेवा सदन", isCorrect: false },
        { label: "B", textEn: "Servants of India Society", textMr: "भारत सेवक समाज", isCorrect: true },
        { label: "C", textEn: "Deshbandhu Samaj", textMr: "देशबंधू समाज", isCorrect: false },
        { label: "D", textEn: "Swadeshi Samaj", textMr: "स्वदेशी समाज", isCorrect: false },
      ],
    },
    {
      textEn: "In which year was Bengal partitioned?",
      textMr: "बंगालची फाळणी कोणत्या वर्षी झाली?",
      explanationEn: "Lord Curzon partitioned Bengal in 1905 AD, causing widespread resentment across India.",
      explanationMr: "लॉर्ड कर्झनने इ.स. १९०५ मध्ये बंगालची फाळणी केली ज्यामुळे संपूर्ण भारतात तीव्र असंतोष निर्माण झाला.",
      options: [
        { label: "A", textEn: "1903 AD", textMr: "इ.स. १९०३", isCorrect: false },
        { label: "B", textEn: "1905 AD", textMr: "इ.स. १९०५", isCorrect: true },
        { label: "C", textEn: "1907 AD", textMr: "इ.स. १९०७", isCorrect: false },
        { label: "D", textEn: "1911 AD", textMr: "इ.स. १९११", isCorrect: false },
      ],
    },
    {
      textEn: "Who launched the Non-Cooperation Movement?",
      textMr: "असहकार चळवळ कोणी सुरू केली?",
      explanationEn: "Mahatma Gandhi launched the Non-Cooperation Movement in 1920 AD, calling on people to refuse cooperation with the British.",
      explanationMr: "महात्मा गांधींनी इ.स. १९२० मध्ये असहकार चळवळ सुरू केली आणि लोकांना इंग्रजांशी सहकार्य न करण्याचे आवाहन केले.",
      options: [
        { label: "A", textEn: "Lokmanya Tilak", textMr: "लोकमान्य टिळक", isCorrect: false },
        { label: "B", textEn: "Mahatma Gandhi", textMr: "महात्मा गांधी", isCorrect: true },
        { label: "C", textEn: "Subhash Chandra Bose", textMr: "सुभाषचंद्र बोस", isCorrect: false },
        { label: "D", textEn: "Jawaharlal Nehru", textMr: "जवाहरलाल नेहरू", isCorrect: false },
      ],
    },
    {
      textEn: "What happened at Chauri Chaura?",
      textMr: "चौरीचौरा येथे काय घटना घडली?",
      explanationEn: "In February 1922, an enraged mob set fire to a police station at Chauri Chaura (UP), which led Gandhiji to withdraw the Non-Cooperation Movement.",
      explanationMr: "फेब्रुवारी १९२२ मध्ये चौरीचौरा (उत्तर प्रदेश) येथे उत्तेजित जमावाने पोलीस ठाण्यास आग लावली त्यामुळे गांधीजींनी असहकार चळवळ मागे घेतली.",
      options: [
        { label: "A", textEn: "People burned railway", textMr: "जनतेने रेल्वे जाळली", isCorrect: false },
        { label: "B", textEn: "Mob set fire to a police station", textMr: "जमावाने पोलीस ठाण्यास आग लावली", isCorrect: true },
        { label: "C", textEn: "Factories were closed", textMr: "कारखाने बंद पाडले", isCorrect: false },
        { label: "D", textEn: "Port was closed", textMr: "बंदर बंद केले", isCorrect: false },
      ],
    },
    {
      textEn: "With which movement was the Khilafat movement linked in Non-Cooperation?",
      textMr: "असहकार चळवळीत खिलाफत चळवळ कशाशी जोडली गेली?",
      explanationEn: "Gandhiji linked the Khilafat movement of Muslims with the Non-Cooperation Movement, creating Hindu-Muslim unity.",
      explanationMr: "गांधीजींनी मुसलमानांची खिलाफत चळवळ आणि असहकार चळवळ यांना एकत्र जोडले ज्यामुळे हिंदू-मुस्लिम ऐक्य निर्माण झाले.",
      options: [
        { label: "A", textEn: "Swadeshi movement", textMr: "स्वदेशी चळवळ", isCorrect: false },
        { label: "B", textEn: "Non-cooperation movement", textMr: "असहकार चळवळ", isCorrect: true },
        { label: "C", textEn: "Civil disobedience", textMr: "सविनय कायदेभंग", isCorrect: false },
        { label: "D", textEn: "Quit India", textMr: "भारत छोडो", isCorrect: false },
      ],
    },
    {
      textEn: "In which year and for what reason was the Dandi March conducted?",
      textMr: "दांडी यात्रा कोणत्या वर्षी व कोणत्या कारणासाठी केली?",
      explanationEn: "Gandhiji conducted the Dandi March in 1930 from Sabarmati to Dandi with 78 companions to protest the unjust tax on salt.",
      explanationMr: "गांधीजींनी इ.स. १९३० मध्ये मिठावरील अन्यायकारक कराविरुद्ध ७८ सहकाऱ्यांसह साबरमती ते दांडी यात्रा केली.",
      options: [
        { label: "A", textEn: "1920 — Tax on cloth", textMr: "इ.स. १९२० — कापडावरील कर", isCorrect: false },
        { label: "B", textEn: "1930 — Tax on salt", textMr: "इ.स. १९३० — मिठावरील कर", isCorrect: true },
        { label: "C", textEn: "1932 — Land revenue", textMr: "इ.स. १९३२ — जमीन महसूल", isCorrect: false },
        { label: "D", textEn: "1942 — Railway", textMr: "इ.स. १९४२ — रेल्वे", isCorrect: false },
      ],
    },
    {
      textEn: "What is Civil Disobedience?",
      textMr: "सविनय कायदेभंग म्हणजे काय?",
      explanationEn: "Civil Disobedience means nonviolently breaking unjust laws and accepting the punishment that follows.",
      explanationMr: "सविनय कायदेभंग म्हणजे अहिंसात्मक मार्गाने अन्यायी कायदे मोडणे आणि त्यामुळे होणारी शिक्षा स्वीकारणे.",
      options: [
        { label: "A", textEn: "Armed revolt", textMr: "सशस्त्र उठाव", isCorrect: false },
        { label: "B", textEn: "Nonviolently breaking unjust laws", textMr: "अहिंसात्मक मार्गाने अन्यायी कायदे मोडणे", isCorrect: true },
        { label: "C", textEn: "Cooperating with government", textMr: "सरकारशी सहकार्य", isCorrect: false },
        { label: "D", textEn: "Going abroad", textMr: "परदेशात जाणे", isCorrect: false },
      ],
    },
    {
      textEn: "In which year was the Gandhi-Irwin Pact signed?",
      textMr: "गांधी-इर्विन करार कोणत्या वर्षी झाला?",
      explanationEn: "In 1931, a pact was signed between Gandhiji and Viceroy Lord Irwin, after which the Civil Disobedience Movement was withdrawn.",
      explanationMr: "इ.स. १९३१ मध्ये गांधीजी व व्हाईसरॉय लॉर्ड इर्विन यांच्यात करार झाला ज्यानुसार सविनय कायदेभंग चळवळ मागे घेण्यात आली.",
      options: [
        { label: "A", textEn: "1928 AD", textMr: "इ.स. १९२८", isCorrect: false },
        { label: "B", textEn: "1931 AD", textMr: "इ.स. १९३१", isCorrect: true },
        { label: "C", textEn: "1935 AD", textMr: "इ.स. १९३५", isCorrect: false },
        { label: "D", textEn: "1942 AD", textMr: "इ.स. १९४२", isCorrect: false },
      ],
    },
    {
      textEn: "In which year did the 'Quit India' movement begin?",
      textMr: "'भारत छोडो' आंदोलन कोणत्या वर्षी सुरू झाले?",
      explanationEn: "Gandhiji launched the 'Quit India' movement on August 8, 1942 in Mumbai with the slogan 'Do or Die'.",
      explanationMr: "गांधीजींनी ८ ऑगस्ट १९४२ रोजी मुंबई येथे 'भारत छोडो' आंदोलन सुरू केले आणि 'करेंगे या मरेंगे' हा नारा दिला.",
      options: [
        { label: "A", textEn: "1939 AD", textMr: "इ.स. १९३९", isCorrect: false },
        { label: "B", textEn: "1942 AD", textMr: "इ.स. १९४२", isCorrect: true },
        { label: "C", textEn: "1945 AD", textMr: "इ.स. १९४५", isCorrect: false },
        { label: "D", textEn: "1947 AD", textMr: "इ.स. १९४७", isCorrect: false },
      ],
    },
    {
      textEn: "In which year did the Cabinet Mission come to India?",
      textMr: "कॅबिनेट मिशन कोणत्या वर्षी भारतात आले?",
      explanationEn: "In 1946, the British government sent the Cabinet Mission to India, which made recommendations regarding arrangements for India's independence.",
      explanationMr: "इ.स. १९४६ मध्ये ब्रिटिश सरकारने कॅबिनेट मिशन भारतात पाठवले ज्याने भारताच्या स्वातंत्र्याच्या व्यवस्थेबाबत सूचना दिल्या.",
      options: [
        { label: "A", textEn: "1942 AD", textMr: "इ.स. १९४२", isCorrect: false },
        { label: "B", textEn: "1945 AD", textMr: "इ.स. १९४५", isCorrect: false },
        { label: "C", textEn: "1946 AD", textMr: "इ.स. १९४६", isCorrect: true },
        { label: "D", textEn: "1947 AD", textMr: "इ.स. १९४७", isCorrect: false },
      ],
    },
    {
      textEn: "What was the name of the army established by Netaji Subhash Chandra Bose?",
      textMr: "नेताजी सुभाषचंद्र बोस यांनी स्थापन केलेल्या सेनेचे नाव काय होते?",
      explanationEn: "Netaji Subhash Chandra Bose took leadership of the Azad Hind Fauj in 1943 AD and gave the slogan 'Jai Hind'.",
      explanationMr: "नेताजी सुभाषचंद्र बोस यांनी इ.स. १९४३ मध्ये आझाद हिंद फौजेचे नेतृत्व स्वीकारले आणि 'जय हिंद' हा नारा दिला.",
      options: [
        { label: "A", textEn: "National Army", textMr: "राष्ट्रीय सेना", isCorrect: false },
        { label: "B", textEn: "Azad Hind Fauj", textMr: "आझाद हिंद फौज", isCorrect: true },
        { label: "C", textEn: "Revolutionary Army", textMr: "क्रांतिकारी सेना", isCorrect: false },
        { label: "D", textEn: "Bharat Sena", textMr: "भारत सेना", isCorrect: false },
      ],
    },
    {
      textEn: "In which year were Bhagat Singh, Rajguru, and Sukhdev hanged?",
      textMr: "भगतसिंग, राजगुरू व सुखदेव यांना कोणत्या वर्षी फाशी देण्यात आले?",
      explanationEn: "Bhagat Singh, Rajguru, and Sukhdev were hanged at Lahore on March 23, 1931.",
      explanationMr: "भगतसिंग, राजगुरू व सुखदेव यांना २३ मार्च १९३१ रोजी लाहोर येथे फाशी देण्यात आले.",
      options: [
        { label: "A", textEn: "1929 AD", textMr: "इ.स. १९२९", isCorrect: false },
        { label: "B", textEn: "1931 AD", textMr: "इ.स. १९३१", isCorrect: true },
        { label: "C", textEn: "1933 AD", textMr: "इ.स. १९३३", isCorrect: false },
        { label: "D", textEn: "1935 AD", textMr: "इ.स. १९३५", isCorrect: false },
      ],
    },
    {
      textEn: "Who did the Chapekar brothers assassinate?",
      textMr: "चापेकर बंधूंनी कोणाची हत्या केली?",
      explanationEn: "Damodar and Balkrishna Chapekar shot Rand and Ayerst in Pune in 1897 for their brutal behavior during the plague.",
      explanationMr: "दामोदर व बाळकृष्ण चापेकर यांनी इ.स. १८९७ मध्ये प्लेगच्या काळी क्रूर वागणूक देणाऱ्या रँड व आयर्स्ट यांना पुण्यात गोळ्या घातल्या.",
      options: [
        { label: "A", textEn: "Lord Curzon", textMr: "लॉर्ड कर्झन", isCorrect: false },
        { label: "B", textEn: "Rand and Ayerst", textMr: "रँड व आयर्स्ट", isCorrect: true },
        { label: "C", textEn: "Lord Irwin", textMr: "लॉर्ड इर्विन", isCorrect: false },
        { label: "D", textEn: "General Dyer", textMr: "जनरल डायर", isCorrect: false },
      ],
    },
    {
      textEn: "Where did Mahatma Phule open the first school for girls?",
      textMr: "महात्मा फुले यांनी मुलींसाठी पहिली शाळा कोठे उघडली?",
      explanationEn: "Mahatma Jotirao Phule opened the first school for girls in Pune in 1848 AD.",
      explanationMr: "महात्मा जोतीराव फुले यांनी इ.स. १८४८ मध्ये पुण्यात मुलींसाठी पहिली शाळा उघडली.",
      options: [
        { label: "A", textEn: "Kolhapur", textMr: "कोल्हापूर", isCorrect: false },
        { label: "B", textEn: "Pune", textMr: "पुणे", isCorrect: true },
        { label: "C", textEn: "Mumbai", textMr: "मुंबई", isCorrect: false },
        { label: "D", textEn: "Nagpur", textMr: "नागपूर", isCorrect: false },
      ],
    },
    {
      textEn: "At which place in Mahad did Dr. Ambedkar conduct a Satyagraha?",
      textMr: "डॉ. आंबेडकर यांनी महाड येथे कोणत्या ठिकाणी सत्याग्रह केला?",
      explanationEn: "Dr. Ambedkar conducted a Satyagraha at Chavdar Lake in Mahad in 1927 AD to assert the right to drink water from it.",
      explanationMr: "डॉ. आंबेडकर यांनी इ.स. १९२७ मध्ये महाड येथील चवदार तळ्यातील पाणी पिण्याचा अधिकार मागण्यासाठी सत्याग्रह केला.",
      options: [
        { label: "A", textEn: "At a well", textMr: "विहिरीवर", isCorrect: false },
        { label: "B", textEn: "Chavdar Lake", textMr: "चवदार तळे", isCorrect: true },
        { label: "C", textEn: "Temple", textMr: "मंदिर", isCorrect: false },
        { label: "D", textEn: "School", textMr: "शाळा", isCorrect: false },
      ],
    },
    {
      textEn: "When did India become independent?",
      textMr: "भारत स्वतंत्र कधी झाला?",
      explanationEn: "India gained independence from British rule on 15 August 1947.",
      explanationMr: "भारताला १५ ऑगस्ट १९४७ रोजी ब्रिटिश राजवटीपासून स्वातंत्र्य मिळाले.",
      options: [
        { label: "A", textEn: "15 August 1946", textMr: "१५ ऑगस्ट १९४६", isCorrect: false },
        { label: "B", textEn: "15 August 1947", textMr: "१५ ऑगस्ट १९४७", isCorrect: true },
        { label: "C", textEn: "26 January 1947", textMr: "२६ जानेवारी १९४७", isCorrect: false },
        { label: "D", textEn: "26 January 1950", textMr: "२६ जानेवारी १९५०", isCorrect: false },
      ],
    },
    {
      textEn: "Under which act was the India-Pakistan partition carried out?",
      textMr: "भारत-पाकिस्तान फाळणी कोणत्या कायद्यान्वये झाली?",
      explanationEn: "Under the Indian Independence Act 1947, two independent nations — India and Pakistan — were created.",
      explanationMr: "भारतीय स्वातंत्र्य कायदा १९४७ अन्वये भारत व पाकिस्तान असे दोन स्वतंत्र देश निर्माण झाले.",
      options: [
        { label: "A", textEn: "Government of India Act 1935", textMr: "भारत सरकार कायदा १९३५", isCorrect: false },
        { label: "B", textEn: "Indian Independence Act 1947", textMr: "भारतीय स्वातंत्र्य कायदा १९४७", isCorrect: true },
        { label: "C", textEn: "Montague-Chelmsford Reforms", textMr: "मॉन्टेग्यू-चेम्सफोर्ड सुधारणा", isCorrect: false },
        { label: "D", textEn: "Cripps Proposal", textMr: "क्रिप्स प्रस्ताव", isCorrect: false },
      ],
    },
    {
      textEn: "On which day did the Indian Constitution come into force?",
      textMr: "भारतीय राज्यघटना कोणत्या दिवशी लागू झाली?",
      explanationEn: "The Indian Constitution came into force on 26 January 1950, which is why we celebrate this day as Republic Day.",
      explanationMr: "भारतीय राज्यघटना २६ जानेवारी १९५० रोजी लागू झाली म्हणून आपण हा दिवस प्रजासत्ताक दिन म्हणून साजरा करतो.",
      options: [
        { label: "A", textEn: "15 August 1947", textMr: "१५ ऑगस्ट १९४७", isCorrect: false },
        { label: "B", textEn: "26 January 1950", textMr: "२६ जानेवारी १९५०", isCorrect: true },
        { label: "C", textEn: "26 November 1949", textMr: "२६ नोव्हेंबर १९४९", isCorrect: false },
        { label: "D", textEn: "15 August 1950", textMr: "१५ ऑगस्ट १९५०", isCorrect: false },
      ],
    },
    {
      textEn: "Who is credited with the merger of princely states into India?",
      textMr: "संस्थानांचे भारतात विलीनीकरण करण्याचे श्रेय कोणाला जाते?",
      explanationEn: "Sardar Vallabhbhai Patel merged over 500 princely states into India, which is why he is called the 'Iron Man'.",
      explanationMr: "सरदार वल्लभभाई पटेल यांनी देशातील ५०० हून अधिक संस्थाने भारतात विलीन केली म्हणून त्यांना 'लोहपुरुष' म्हणतात.",
      options: [
        { label: "A", textEn: "Jawaharlal Nehru", textMr: "जवाहरलाल नेहरू", isCorrect: false },
        { label: "B", textEn: "Sardar Vallabhbhai Patel", textMr: "सरदार वल्लभभाई पटेल", isCorrect: true },
        { label: "C", textEn: "Dr. Rajendra Prasad", textMr: "डॉ. राजेंद्र प्रसाद", isCorrect: false },
        { label: "D", textEn: "Babasaheb Ambedkar", textMr: "बाबासाहेब आंबेडकर", isCorrect: false },
      ],
    },
    {
      textEn: "On which day was Maharashtra state established?",
      textMr: "महाराष्ट्र राज्य कोणत्या दिवशी स्थापन झाले?",
      explanationEn: "Maharashtra state for Marathi speakers was established on 1 May 1960, which is why we celebrate this day as 'Maharashtra Day'.",
      explanationMr: "१ मे १९६० रोजी मराठी भाषिकांचे वेगळे महाराष्ट्र राज्य स्थापन झाले म्हणून आपण हा दिवस 'महाराष्ट्र दिन' म्हणून साजरा करतो.",
      options: [
        { label: "A", textEn: "1 May 1950", textMr: "१ मे १९५०", isCorrect: false },
        { label: "B", textEn: "1 May 1960", textMr: "१ मे १९६०", isCorrect: true },
        { label: "C", textEn: "26 January 1950", textMr: "२६ जानेवारी १९५०", isCorrect: false },
        { label: "D", textEn: "15 August 1955", textMr: "१५ ऑगस्ट १९५५", isCorrect: false },
      ],
    },
    {
      textEn: "Who led the agitation for the formation of Maharashtra state?",
      textMr: "महाराष्ट्र राज्यनिर्मितीसाठी आंदोलन कोणी केले?",
      explanationEn: "The Samyukta Maharashtra Samiti led an intense agitation for a separate state for Marathi speakers.",
      explanationMr: "संयुक्त महाराष्ट्र समितीने मराठी भाषिकांचे स्वतंत्र राज्य मिळावे यासाठी तीव्र आंदोलन केले.",
      options: [
        { label: "A", textEn: "Samyukta Maharashtra Samiti", textMr: "संयुक्त महाराष्ट्र समिती", isCorrect: true },
        { label: "B", textEn: "Congress Samiti", textMr: "काँग्रेस समिती", isCorrect: false },
        { label: "C", textEn: "Jana Sangh Samiti", textMr: "जनसंघ समिती", isCorrect: false },
        { label: "D", textEn: "Socialist Samiti", textMr: "समाजवादी समिती", isCorrect: false },
      ],
    },
    {
      textEn: "What was the first capital of Maharashtra?",
      textMr: "महाराष्ट्राची पहिली राजधानी कोणती होती?",
      explanationEn: "The capital of Maharashtra state is Mumbai. Nagpur is the sub-capital where the winter session of the legislature is held.",
      explanationMr: "महाराष्ट्र राज्याची राजधानी मुंबई आहे. नागपूर हे उपराजधानी आहे आणि तेथे हिवाळी अधिवेशन होते.",
      options: [
        { label: "A", textEn: "Pune", textMr: "पुणे", isCorrect: false },
        { label: "B", textEn: "Nagpur", textMr: "नागपूर", isCorrect: false },
        { label: "C", textEn: "Mumbai", textMr: "मुंबई", isCorrect: true },
        { label: "D", textEn: "Aurangabad", textMr: "औरंगाबाद", isCorrect: false },
      ],
    },
    {
      textEn: "In parliamentary government, to whom is the executive responsible?",
      textMr: "संसदीय शासनपद्धतीत कार्यकारी मंडळ कोणाला जबाबदार असते?",
      explanationEn: "In parliamentary government, the executive (cabinet) is responsible to the legislature (Parliament).",
      explanationMr: "संसदीय शासनपद्धतीत कार्यकारी मंडळ (मंत्रिमंडळ) संसदेला (कायदेमंडळाला) जबाबदार असते.",
      options: [
        { label: "A", textEn: "To the President", textMr: "राष्ट्रपतींना", isCorrect: false },
        { label: "B", textEn: "To the Legislature", textMr: "कायदेमंडळाला", isCorrect: true },
        { label: "C", textEn: "To the Judiciary", textMr: "न्यायमंडळाला", isCorrect: false },
        { label: "D", textEn: "To the Governor", textMr: "राज्यपालांना", isCorrect: false },
      ],
    },
    {
      textEn: "What type of government system does India have?",
      textMr: "भारतात कोणती शासनपद्धती आहे?",
      explanationEn: "India has a parliamentary democratic system of government in which the Prime Minister is the head of government.",
      explanationMr: "भारतात संसदीय लोकशाही शासनपद्धती आहे ज्यात पंतप्रधान हे सरकार प्रमुख असतात.",
      options: [
        { label: "A", textEn: "Presidential system", textMr: "राष्ट्रपती शासनपद्धती", isCorrect: false },
        { label: "B", textEn: "Parliamentary system", textMr: "संसदीय शासनपद्धती", isCorrect: true },
        { label: "C", textEn: "Dictatorship", textMr: "हुकुमशाही", isCorrect: false },
        { label: "D", textEn: "Monarchy", textMr: "राजेशाही", isCorrect: false },
      ],
    },
    {
      textEn: "How is the Prime Minister selected in a parliamentary system?",
      textMr: "संसदीय शासनपद्धतीत पंतप्रधान कसे निवडले जातात?",
      explanationEn: "The leader of the party with a majority in the Lok Sabha is appointed as Prime Minister by the President.",
      explanationMr: "लोकसभेत बहुमत असलेल्या पक्षाच्या नेत्यास राष्ट्रपती पंतप्रधान म्हणून नियुक्त करतात.",
      options: [
        { label: "A", textEn: "Directly elected by people", textMr: "जनतेकडून थेट निवडून", isCorrect: false },
        { label: "B", textEn: "Leader of majority party in Lok Sabha", textMr: "लोकसभेतील बहुमत पक्षाचे नेते", isCorrect: true },
        { label: "C", textEn: "Appointed by President", textMr: "राष्ट्रपती नियुक्त करतात", isCorrect: false },
        { label: "D", textEn: "From Rajya Sabha", textMr: "राज्यसभेतून", isCorrect: false },
      ],
    },
    {
      textEn: "How many houses does the Indian Parliament have?",
      textMr: "भारतीय संसदेत किती सभागृहे आहेत?",
      explanationEn: "The Indian Parliament has two houses — Lok Sabha (Lower House) and Rajya Sabha (Upper House).",
      explanationMr: "भारतीय संसदेत दोन सभागृहे आहेत — लोकसभा (कनिष्ठ सभागृह) आणि राज्यसभा (वरिष्ठ सभागृह).",
      options: [
        { label: "A", textEn: "One", textMr: "एक", isCorrect: false },
        { label: "B", textEn: "Two", textMr: "दोन", isCorrect: true },
        { label: "C", textEn: "Three", textMr: "तीन", isCorrect: false },
        { label: "D", textEn: "Four", textMr: "चार", isCorrect: false },
      ],
    },
    {
      textEn: "What is the term of the Lok Sabha?",
      textMr: "लोकसभेचा कार्यकाल किती वर्षांचा असतो?",
      explanationEn: "The normal term of the Lok Sabha is 5 years, but it can be extended during an emergency.",
      explanationMr: "लोकसभेचा सामान्य कार्यकाल ५ वर्षांचा असतो परंतु आणीबाणीत तो वाढवता येतो.",
      options: [
        { label: "A", textEn: "3 years", textMr: "३ वर्षे", isCorrect: false },
        { label: "B", textEn: "4 years", textMr: "४ वर्षे", isCorrect: false },
        { label: "C", textEn: "5 years", textMr: "५ वर्षे", isCorrect: true },
        { label: "D", textEn: "6 years", textMr: "६ वर्षे", isCorrect: false },
      ],
    },
    {
      textEn: "How are members of the Rajya Sabha elected?",
      textMr: "राज्यसभेचे सदस्य कसे निवडले जातात?",
      explanationEn: "Rajya Sabha members are indirectly elected by state legislatures. The President nominates 12 members.",
      explanationMr: "राज्यसभेचे सदस्य राज्यांच्या विधानसभांद्वारे अप्रत्यक्षपणे निवडले जातात. राष्ट्रपती १२ सदस्य नामनिर्देशित करतात.",
      options: [
        { label: "A", textEn: "Directly by the people", textMr: "जनतेकडून थेट", isCorrect: false },
        { label: "B", textEn: "By state legislatures", textMr: "राज्यांच्या विधानसभांनी", isCorrect: true },
        { label: "C", textEn: "By the President", textMr: "राष्ट्रपतींनी", isCorrect: false },
        { label: "D", textEn: "By the Prime Minister", textMr: "पंतप्रधानांनी", isCorrect: false },
      ],
    },
    {
      textEn: "Who is the Speaker of the Lok Sabha?",
      textMr: "लोकसभेचे अध्यक्ष (Speaker) कोण असतात?",
      explanationEn: "Lok Sabha members elect one from among themselves as the Speaker.",
      explanationMr: "लोकसभेचे सदस्य आपल्यातूनच एकाला अध्यक्ष (Speaker) म्हणून निवडतात.",
      options: [
        { label: "A", textEn: "President", textMr: "राष्ट्रपती", isCorrect: false },
        { label: "B", textEn: "Prime Minister", textMr: "पंतप्रधान", isCorrect: false },
        { label: "C", textEn: "Elected by Lok Sabha members", textMr: "लोकसभेचे सदस्य निवडतात तो", isCorrect: true },
        { label: "D", textEn: "Chief Justice", textMr: "मुख्य न्यायाधीश", isCorrect: false },
      ],
    },
    {
      textEn: "Where is the Supreme Court of India located?",
      textMr: "भारताचे सर्वोच्च न्यायालय कोठे आहे?",
      explanationEn: "The Supreme Court of India is located in New Delhi.",
      explanationMr: "भारताचे सर्वोच्च न्यायालय नवी दिल्ली येथे आहे.",
      options: [
        { label: "A", textEn: "Mumbai", textMr: "मुंबई", isCorrect: false },
        { label: "B", textEn: "Delhi", textMr: "दिल्ली", isCorrect: true },
        { label: "C", textEn: "Kolkata", textMr: "कोलकाता", isCorrect: false },
        { label: "D", textEn: "Chennai", textMr: "चेन्नई", isCorrect: false },
      ],
    },
    {
      textEn: "At which level is the High Court?",
      textMr: "उच्च न्यायालय कोणत्या पातळीवर असते?",
      explanationEn: "The High Court is the highest court at the state level.",
      explanationMr: "उच्च न्यायालय हे राज्य पातळीवरील सर्वोच्च न्यायालय असते.",
      options: [
        { label: "A", textEn: "District", textMr: "जिल्हा", isCorrect: false },
        { label: "B", textEn: "State", textMr: "राज्य", isCorrect: true },
        { label: "C", textEn: "Taluka", textMr: "तालुका", isCorrect: false },
        { label: "D", textEn: "Central", textMr: "केंद्र", isCorrect: false },
      ],
    },
    {
      textEn: "Who appoints the Chief Justice of the Supreme Court?",
      textMr: "सर्वोच्च न्यायालयाच्या मुख्य न्यायाधीशांची नियुक्ती कोण करते?",
      explanationEn: "The President appoints the Chief Justice of the Supreme Court.",
      explanationMr: "सर्वोच्च न्यायालयाच्या मुख्य न्यायाधीशांची नियुक्ती राष्ट्रपती करतात.",
      options: [
        { label: "A", textEn: "Prime Minister", textMr: "पंतप्रधान", isCorrect: false },
        { label: "B", textEn: "President", textMr: "राष्ट्रपती", isCorrect: true },
        { label: "C", textEn: "Parliament", textMr: "संसद", isCorrect: false },
        { label: "D", textEn: "Vice President", textMr: "उपराष्ट्रपती", isCorrect: false },
      ],
    },
    {
      textEn: "Who is the head of the state government?",
      textMr: "राज्य सरकारचे प्रमुख कोण असतात?",
      explanationEn: "The Chief Minister is the real head of the state government while the Governor is the constitutional head.",
      explanationMr: "राज्य सरकारचे वास्तविक प्रमुख मुख्यमंत्री असतात तर राज्यपाल हे घटनात्मक प्रमुख असतात.",
      options: [
        { label: "A", textEn: "Governor", textMr: "राज्यपाल", isCorrect: false },
        { label: "B", textEn: "Chief Minister", textMr: "मुख्यमंत्री", isCorrect: true },
        { label: "C", textEn: "Prime Minister", textMr: "पंतप्रधान", isCorrect: false },
        { label: "D", textEn: "President", textMr: "राष्ट्रपती", isCorrect: false },
      ],
    },
    {
      textEn: "Who appoints the Governor?",
      textMr: "राज्यपालांची नियुक्ती कोण करते?",
      explanationEn: "The Governor is appointed by the President and serves at the pleasure of the President.",
      explanationMr: "राज्यपालांची नियुक्ती राष्ट्रपती करतात आणि ते राष्ट्रपतींच्या इच्छेनुसार पदावर राहतात.",
      options: [
        { label: "A", textEn: "Chief Minister", textMr: "मुख्यमंत्री", isCorrect: false },
        { label: "B", textEn: "President", textMr: "राष्ट्रपती", isCorrect: true },
        { label: "C", textEn: "Prime Minister", textMr: "पंतप्रधान", isCorrect: false },
        { label: "D", textEn: "Parliament", textMr: "संसद", isCorrect: false },
      ],
    },
    {
      textEn: "If a state has only one legislative house, what is it called?",
      textMr: "राज्यात एकच सभागृह असेल तर त्याला काय म्हणतात?",
      explanationEn: "A state with only one house has a Vidhan Sabha. The Vidhan Parishad is the second (upper) house.",
      explanationMr: "ज्या राज्यात एकच सभागृह असते त्याला विधानसभा म्हणतात. विधानपरिषद हे दुसरे (वरिष्ठ) सभागृह असते.",
      options: [
        { label: "A", textEn: "Vidhan Parishad", textMr: "विधानपरिषद", isCorrect: false },
        { label: "B", textEn: "Vidhan Sabha", textMr: "विधानसभा", isCorrect: true },
        { label: "C", textEn: "Rajya Sabha", textMr: "राज्यसभा", isCorrect: false },
        { label: "D", textEn: "Lok Sabha", textMr: "लोकसभा", isCorrect: false },
      ],
    },
    {
      textEn: "Who is the chief administrative officer of a district?",
      textMr: "जिल्ह्याचा प्रमुख अधिकारी कोण असतो?",
      explanationEn: "The District Collector is the chief administrative officer of a district.",
      explanationMr: "जिल्हाधिकारी (Collector) हे जिल्ह्याचे प्रमुख प्रशासकीय अधिकारी असतात.",
      options: [
        { label: "A", textEn: "Tehsildar", textMr: "तहसीलदार", isCorrect: false },
        { label: "B", textEn: "District Collector", textMr: "जिल्हाधिकारी (Collector)", isCorrect: true },
        { label: "C", textEn: "Superintendent of Police", textMr: "पोलीस अधीक्षक", isCorrect: false },
        { label: "D", textEn: "Gram Sevak", textMr: "ग्रामसेवक", isCorrect: false },
      ],
    },
    {
      textEn: "What does IAS stand for?",
      textMr: "IAS म्हणजे काय?",
      explanationEn: "IAS stands for Indian Administrative Service. These officers are selected through the UPSC examination.",
      explanationMr: "IAS म्हणजे Indian Administrative Service (भारतीय प्रशासकीय सेवा). हे अधिकारी UPSC परीक्षेद्वारे निवडले जातात.",
      options: [
        { label: "A", textEn: "Indian Administrative Service", textMr: "भारतीय प्रशासकीय सेवा", isCorrect: true },
        { label: "B", textEn: "Indian Army Service", textMr: "भारतीय सैन्य सेवा", isCorrect: false },
        { label: "C", textEn: "International Administrative System", textMr: "आंतरराष्ट्रीय प्रशासन", isCorrect: false },
        { label: "D", textEn: "Indian Audit Service", textMr: "भारतीय लेखापरीक्षण सेवा", isCorrect: false },
      ],
    },
    {
      textEn: "Who handles government work at the village level?",
      textMr: "ग्रामपातळीवर सरकारी कामकाज कोण पाहते?",
      explanationEn: "The Gram Sevak is the government officer who implements government schemes at the village level.",
      explanationMr: "ग्रामसेवक हे गावपातळीवर सरकारी योजना राबवणारे अधिकारी असतात.",
      options: [
        { label: "A", textEn: "Collector", textMr: "जिल्हाधिकारी", isCorrect: false },
        { label: "B", textEn: "Tehsildar", textMr: "तहसीलदार", isCorrect: false },
        { label: "C", textEn: "Gram Sevak", textMr: "ग्रामसेवक", isCorrect: true },
        { label: "D", textEn: "Minister", textMr: "मंत्री", isCorrect: false },
      ],
    },
  ],
};

export default data;
