import type { QuestionSetInput } from "./types";

// Source: All questions & answer/AMVI_Std8_Geo_English.pdf + AMVI_Std8_Geo_Marathi.pdf
// Both PDFs share identical question numbering/options/answers (43 MCQs).
const data: QuestionSetInput = {
  standard: { code: "STD8", nameEn: "Standard 8", nameMr: "इयत्ता ८वी", sortOrder: 8 },
  subject: { code: "GEO", nameEn: "Geography", nameMr: "भूगोल", sortOrder: 2 },
  questions: [
    {
      textEn: "How long does the Earth take to rotate on its own axis?",
      textMr: "पृथ्वी स्वतःभोवती फिरण्यास किती वेळ लागतो?",
      explanationEn: "The Earth takes approximately 24 hours (23 hours 56 minutes 4 seconds) to rotate once on its axis.",
      explanationMr: "पृथ्वी स्वतःभोवती एकदा फिरण्यास सुमारे २४ तास (२३ तास ५६ मिनिटे ४ सेकंद) लागतात.",
      options: [
        { label: "A", textEn: "12 hours", textMr: "१२ तास", isCorrect: false },
        { label: "B", textEn: "24 hours", textMr: "२४ तास", isCorrect: true },
        { label: "C", textEn: "36 hours", textMr: "३६ तास", isCorrect: false },
        { label: "D", textEn: "48 hours", textMr: "४८ तास", isCorrect: false },
      ],
    },
    {
      textEn: "How many degrees does the Earth rotate in one hour?",
      textMr: "एका तासात पृथ्वी किती अंश फिरते?",
      explanationEn: "The Earth rotates 360° in 24 hours, so it rotates 360÷24 = 15° per hour.",
      explanationMr: "पृथ्वी २४ तासांत ३६०° फिरते म्हणजे एका तासात ३६०÷२४ = १५° फिरते.",
      options: [
        { label: "A", textEn: "10°", textMr: "१०°", isCorrect: false },
        { label: "B", textEn: "15°", textMr: "१५°", isCorrect: true },
        { label: "C", textEn: "20°", textMr: "२०°", isCorrect: false },
        { label: "D", textEn: "25°", textMr: "२५°", isCorrect: false },
      ],
    },
    {
      textEn: "What is India's Standard Meridian?",
      textMr: "भारताची प्रमाण देशांतर रेषा (Standard Meridian) कोणती?",
      explanationEn: "India's Standard Meridian is 82°30' East, which passes near Allahabad (Prayagraj).",
      explanationMr: "भारताची प्रमाण देशांतर रेषा ८२°३०' पूर्व आहे जी अलाहाबाद (प्रयागराज) जवळून जाते.",
      options: [
        { label: "A", textEn: "72°30' East", textMr: "७२°३०' पूर्व", isCorrect: false },
        { label: "B", textEn: "80°0' East", textMr: "८०°०' पूर्व", isCorrect: false },
        { label: "C", textEn: "82°30' East", textMr: "८२°३०' पूर्व", isCorrect: true },
        { label: "D", textEn: "90°0' East", textMr: "९०°०' पूर्व", isCorrect: false },
      ],
    },
    {
      textEn: "On which meridian is Greenwich Mean Time (GMT) based?",
      textMr: "जागतिक प्रमाण वेळ (GMT) कोणत्या देशांतर रेषेवर आधारित आहे?",
      explanationEn: "GMT is based on the 0° longitude meridian passing through Greenwich, England.",
      explanationMr: "GMT हे इंग्लंडमधील ग्रीनविच येथून जाणाऱ्या ०° देशांतर रेषेवर आधारित आहे.",
      options: [
        { label: "A", textEn: "0° Longitude", textMr: "०° देशांतर", isCorrect: true },
        { label: "B", textEn: "180° Longitude", textMr: "१८०° देशांतर", isCorrect: false },
        { label: "C", textEn: "90° East", textMr: "९०° पूर्व", isCorrect: false },
        { label: "D", textEn: "90° West", textMr: "९०° पश्चिम", isCorrect: false },
      ],
    },
    {
      textEn: "What is the time difference between India and GMT?",
      textMr: "भारत आणि GMT यांत किती फरक आहे?",
      explanationEn: "Indian Standard Time (IST) is +5:30 hours ahead of GMT.",
      explanationMr: "भारतीय प्रमाण वेळ (IST) हा GMT पेक्षा +५:३० तास पुढे असतो.",
      options: [
        { label: "A", textEn: "+4:30 hours", textMr: "+४:३० तास", isCorrect: false },
        { label: "B", textEn: "+5:30 hours", textMr: "+५:३० तास", isCorrect: true },
        { label: "C", textEn: "+6:00 hours", textMr: "+६:०० तास", isCorrect: false },
        { label: "D", textEn: "+3:00 hours", textMr: "+३:०० तास", isCorrect: false },
      ],
    },
    {
      textEn: "What is local time?",
      textMr: "स्थानिक वेळ म्हणजे काय?",
      explanationEn: "Time based on a place's longitude is that place's local time.",
      explanationMr: "एखाद्या ठिकाणच्या देशांतरावर आधारित वेळ म्हणजे त्या ठिकाणची स्थानिक वेळ होय.",
      options: [
        { label: "A", textEn: "Time as per GMT", textMr: "GMT नुसार वेळ", isCorrect: false },
        { label: "B", textEn: "Time based on a place's longitude", textMr: "एखाद्या ठिकाणच्या देशांतरावर आधारित वेळ", isCorrect: true },
        { label: "C", textEn: "Time fixed by government", textMr: "सरकारने ठरवलेली वेळ", isCorrect: false },
        { label: "D", textEn: "International time", textMr: "आंतरराष्ट्रीय वेळ", isCorrect: false },
      ],
    },
    {
      textEn: "How many layers are in the interior of the Earth?",
      textMr: "पृथ्वीच्या अंतरंगात किती थर आहेत?",
      explanationEn: "The Earth's interior has mainly three layers: Crust, Mantle, and Core.",
      explanationMr: "पृथ्वीच्या अंतरंगात मुख्यतः तीन थर आहेत: भूकवच (Crust), आवरण (Mantle) आणि गाभा (Core).",
      options: [
        { label: "A", textEn: "Two", textMr: "दोन", isCorrect: false },
        { label: "B", textEn: "Three", textMr: "तीन", isCorrect: true },
        { label: "C", textEn: "Four", textMr: "चार", isCorrect: false },
        { label: "D", textEn: "Five", textMr: "पाच", isCorrect: false },
      ],
    },
    {
      textEn: "What is the outermost layer of the Earth called?",
      textMr: "पृथ्वीच्या सर्वात बाहेरच्या थराला काय म्हणतात?",
      explanationEn: "The outermost layer of the Earth is the Crust. Its average thickness is 30-40 km.",
      explanationMr: "पृथ्वीचा सर्वात बाहेरचा थर म्हणजे भूकवच (Crust). याचे सरासरी जाडी ३०-४० किमी आहे.",
      options: [
        { label: "A", textEn: "Core", textMr: "गाभा", isCorrect: false },
        { label: "B", textEn: "Mantle", textMr: "आवरण", isCorrect: false },
        { label: "C", textEn: "Crust", textMr: "भूकवच", isCorrect: true },
        { label: "D", textEn: "Outer Core", textMr: "बाह्य गाभा", isCorrect: false },
      ],
    },
    {
      textEn: "What types of earthquake waves are there?",
      textMr: "भूकंप लाटा कोणत्या प्रकारच्या असतात?",
      explanationEn: "Earthquake waves are mainly of two types: P waves (Primary waves) and S waves (Secondary waves).",
      explanationMr: "भूकंप लाटांचे मुख्यतः दोन प्रकार आहेत: P लाटा (Primary waves) आणि S लाटा (Secondary waves).",
      options: [
        { label: "A", textEn: "P and Q waves", textMr: "P आणि Q लाटा", isCorrect: false },
        { label: "B", textEn: "P and S waves", textMr: "P आणि S लाटा", isCorrect: true },
        { label: "C", textEn: "X and Y waves", textMr: "X आणि Y लाटा", isCorrect: false },
        { label: "D", textEn: "A and B waves", textMr: "A आणि B लाटा", isCorrect: false },
      ],
    },
    {
      textEn: "What is the molten rock erupting from a volcano called?",
      textMr: "ज्वालामुखीतून बाहेर पडणाऱ्या द्रव खडकास काय म्हणतात?",
      explanationEn: "The molten rock erupting from a volcano is called lava. When it is underground, it is called magma.",
      explanationMr: "ज्वालामुखीतून बाहेर पडणाऱ्या द्रव खडकास लावा म्हणतात. जमिनीखाली असताना त्यास मॅग्मा म्हणतात.",
      options: [
        { label: "A", textEn: "Magma", textMr: "मॅग्मा", isCorrect: false },
        { label: "B", textEn: "Lava", textMr: "लावा", isCorrect: true },
        { label: "C", textEn: "Basalt", textMr: "बेसाल्ट", isCorrect: false },
        { label: "D", textEn: "Granite", textMr: "ग्रॅनाईट", isCorrect: false },
      ],
    },
    {
      textEn: "Of what is the Earth's core composed?",
      textMr: "पृथ्वीचा गाभा कशाने बनलेला आहे?",
      explanationEn: "The Earth's core is mainly composed of iron and nickel. Its temperature is very high.",
      explanationMr: "पृथ्वीचा गाभा मुख्यत: लोह व निकेल यांनी बनलेला आहे. याचे तापमान खूप जास्त असते.",
      options: [
        { label: "A", textEn: "Silicon and Aluminum", textMr: "सिलिका व ॲल्युमिनियम", isCorrect: false },
        { label: "B", textEn: "Iron and Nickel", textMr: "लोह व निकेल", isCorrect: true },
        { label: "C", textEn: "Carbon and Sulfur", textMr: "कार्बन व सल्फर", isCorrect: false },
        { label: "D", textEn: "Oxygen and Hydrogen", textMr: "ऑक्सिजन व हायड्रोजन", isCorrect: false },
      ],
    },
    {
      textEn: "What is the amount of water vapour in the air called?",
      textMr: "हवेतील पाण्याच्या वाफेच्या प्रमाणाला काय म्हणतात?",
      explanationEn: "The amount of water vapour dissolved in air is called humidity.",
      explanationMr: "हवेत विरघळलेल्या पाण्याच्या वाफेच्या प्रमाणाला आर्द्रता म्हणतात.",
      options: [
        { label: "A", textEn: "Rainfall", textMr: "पर्जन्यमान", isCorrect: false },
        { label: "B", textEn: "Humidity", textMr: "आर्द्रता", isCorrect: true },
        { label: "C", textEn: "Temperature", textMr: "तापमान", isCorrect: false },
        { label: "D", textEn: "Pressure", textMr: "दाब", isCorrect: false },
      ],
    },
    {
      textEn: "From what are clouds formed?",
      textMr: "ढग कशापासून तयार होतात?",
      explanationEn: "When tiny water droplets and ice crystals in the air gather together, clouds are formed.",
      explanationMr: "हवेत पाण्याच्या वाफेचे लहान थेंब व बर्फाचे कण एकत्र जमल्यावर ढग तयार होतात.",
      options: [
        { label: "A", textEn: "From dust", textMr: "धुळीपासून", isCorrect: false },
        { label: "B", textEn: "From tiny water droplets and ice crystals", textMr: "पाण्याच्या लहान थेंबांपासून व बर्फाच्या कणांपासून", isCorrect: true },
        { label: "C", textEn: "From smoke", textMr: "धुरापासून", isCorrect: false },
        { label: "D", textEn: "From gases", textMr: "वायूपासून", isCorrect: false },
      ],
    },
    {
      textEn: "What happens when relative humidity reaches 100%?",
      textMr: "सापेक्ष आर्द्रता १००% झाल्यावर काय होते?",
      explanationEn: "When the relative humidity of air reaches 100%, the air becomes saturated and precipitation occurs.",
      explanationMr: "जेव्हा हवेची सापेक्ष आर्द्रता १००% होते तेव्हा हवा संतृप्त होते आणि पर्जन्य होतो.",
      options: [
        { label: "A", textEn: "Wind blows", textMr: "वारा वाहतो", isCorrect: false },
        { label: "B", textEn: "It rains", textMr: "पाऊस पडतो", isCorrect: true },
        { label: "C", textEn: "Storm comes", textMr: "वादळ येते", isCorrect: false },
        { label: "D", textEn: "Drought occurs", textMr: "दुष्काळ पडतो", isCorrect: false },
      ],
    },
    {
      textEn: "Which type of clouds bring rain?",
      textMr: "कोणत्या प्रकारचे ढग पाऊस आणतात?",
      explanationEn: "Nimbus type clouds bring rain. Cumulonimbus clouds are associated with heavy rain.",
      explanationMr: "निंबस (Nimbus) प्रकारचे ढग पाऊस आणतात. क्युम्युलोनिंबस ढग मुसळधार पावसाशी संबंधित असतात.",
      options: [
        { label: "A", textEn: "Cirrus", textMr: "सिरस", isCorrect: false },
        { label: "B", textEn: "Cumulus", textMr: "क्युम्युलस", isCorrect: false },
        { label: "C", textEn: "Nimbus", textMr: "निंबस", isCorrect: true },
        { label: "D", textEn: "Stratus", textMr: "स्ट्रेटस", isCorrect: false },
      ],
    },
    {
      textEn: "Which is the deepest oceanic trench in the world?",
      textMr: "जगातील सर्वात खोल सागरी खड्डा कोणता?",
      explanationEn: "The Mariana Trench is the deepest oceanic trench in the world. It is in the Pacific Ocean with a depth of about 11,034 meters.",
      explanationMr: "मारियाना खड्डा हा जगातील सर्वात खोल सागरी खड्डा आहे. तो पॅसिफिक महासागरात आहे आणि त्याची खोली सुमारे ११,०३४ मीटर आहे.",
      options: [
        { label: "A", textEn: "Java Trench", textMr: "जावा खड्डा", isCorrect: false },
        { label: "B", textEn: "Mariana Trench", textMr: "मारियाना खड्डा", isCorrect: true },
        { label: "C", textEn: "Tonga Trench", textMr: "टोंगा खड्डा", isCorrect: false },
        { label: "D", textEn: "Atlantic Trench", textMr: "अटलांटिक खड्डा", isCorrect: false },
      ],
    },
    {
      textEn: "What is the Continental Shelf?",
      textMr: "महाद्वीपीय मचाण (Continental Shelf) म्हणजे काय?",
      explanationEn: "The shallow (generally up to 200 meters deep) marine area at the edge of a continent is the Continental Shelf.",
      explanationMr: "महाद्वीपाच्या कडेला असलेला उथळ (साधारण २०० मीटरपर्यंत खोली असलेला) सागरी भाग म्हणजे महाद्वीपीय मचाण.",
      options: [
        { label: "A", textEn: "High plateau of a continent", textMr: "महाद्वीपाचे उंच पठार", isCorrect: false },
        { label: "B", textEn: "Shallow part at the edge of the ocean", textMr: "महासागराच्या काठाचा उथळ भाग", isCorrect: true },
        { label: "C", textEn: "Mountains in the sea", textMr: "समुद्रातील पर्वत", isCorrect: false },
        { label: "D", textEn: "Deep sea trench", textMr: "खोल सागरी खड्डा", isCorrect: false },
      ],
    },
    {
      textEn: "What are the underwater mountain ranges in the middle of oceans called?",
      textMr: "महासागराच्या मध्यभागी असलेल्या पाण्याखालील पर्वतांच्या रांगेला काय म्हणतात?",
      explanationEn: "The underwater mountain ranges in the middle of oceans are called mid-oceanic ridges. E.g., Mid-Atlantic Ridge.",
      explanationMr: "महासागराच्या मध्यभागात असलेल्या पाण्याखालील पर्वतरांगांना मध्य-महासागरीय उंचवटे म्हणतात. उदा. मध्य अटलांटिक उंचवटा.",
      options: [
        { label: "A", textEn: "Ocean trench", textMr: "सागरी गर्त", isCorrect: false },
        { label: "B", textEn: "Mid-oceanic ridges", textMr: "मध्य-महासागरीय उंचवटे", isCorrect: true },
        { label: "C", textEn: "Continental slope", textMr: "महाद्वीपीय उतार", isCorrect: false },
        { label: "D", textEn: "Abyssal plain", textMr: "अभिसरण", isCorrect: false },
      ],
    },
    {
      textEn: "What are ocean currents?",
      textMr: "सागरी प्रवाह म्हणजे काय?",
      explanationEn: "The regular flow of water in oceans in a definite direction is called ocean current.",
      explanationMr: "महासागरातील पाण्याचे निश्चित दिशेने नियमित प्रवाहणे म्हणजे सागरी प्रवाह.",
      options: [
        { label: "A", textEn: "Underwater earthquakes", textMr: "पाण्याखालील भूकंप", isCorrect: false },
        { label: "B", textEn: "Regular flows of water in oceans", textMr: "महासागरातील पाण्याचे नियमित प्रवाह", isCorrect: true },
        { label: "C", textEn: "Storms in oceans", textMr: "महासागरातील वादळे", isCorrect: false },
        { label: "D", textEn: "Waves on seashores", textMr: "समुद्र किनाऱ्यावरील लाटा", isCorrect: false },
      ],
    },
    {
      textEn: "In which direction do cold ocean currents flow?",
      textMr: "थंड सागरी प्रवाह कोणत्या दिशेने वाहतात?",
      explanationEn: "Cold ocean currents flow from polar regions towards the equator.",
      explanationMr: "थंड सागरी प्रवाह ध्रुवीय भागांतून विषुववृत्ताच्या दिशेने वाहतात.",
      options: [
        { label: "A", textEn: "From poles towards equator", textMr: "ध्रुवाकडून विषुववृत्ताकडे", isCorrect: true },
        { label: "B", textEn: "From equator towards poles", textMr: "विषुववृत्ताकडून ध्रुवाकडे", isCorrect: false },
        { label: "C", textEn: "From east to west", textMr: "पूर्वेकडून पश्चिमेकडे", isCorrect: false },
        { label: "D", textEn: "From west to east", textMr: "पश्चिमेकडून पूर्वेकडे", isCorrect: false },
      ],
    },
    {
      textEn: "What type of current is the Gulf Stream?",
      textMr: "गल्फ स्ट्रीम हा कोणता प्रवाह आहे?",
      explanationEn: "The Gulf Stream is a warm ocean current that flows from the Gulf of Mexico into the North Atlantic.",
      explanationMr: "गल्फ स्ट्रीम हा एक उष्ण सागरी प्रवाह आहे जो मेक्सिकोच्या आखातातून उत्तर अटलांटिकमध्ये वाहतो.",
      options: [
        { label: "A", textEn: "Cold", textMr: "थंड", isCorrect: false },
        { label: "B", textEn: "Warm", textMr: "उष्ण", isCorrect: true },
        { label: "C", textEn: "Neutral", textMr: "तटस्थ", isCorrect: false },
        { label: "D", textEn: "Mixed", textMr: "मिश्र", isCorrect: false },
      ],
    },
    {
      textEn: "What effect do ocean currents have on climate?",
      textMr: "सागरी प्रवाहांचा हवामानावर काय परिणाम होतो?",
      explanationEn: "Warm currents warm coastal areas and cold currents cool them, affecting the climate of those regions.",
      explanationMr: "उष्ण प्रवाह किनारी प्रदेश उष्ण करतात तर थंड प्रवाह थंड करतात. यामुळे त्या प्रदेशाचे हवामान बदलते.",
      options: [
        { label: "A", textEn: "No effect", textMr: "परिणाम नाही", isCorrect: false },
        { label: "B", textEn: "They change temperatures in coastal areas", textMr: "किनारी प्रदेशातील तापमान बदलतात", isCorrect: true },
        { label: "C", textEn: "Only bring storms", textMr: "फक्त वादळे आणतात", isCorrect: false },
        { label: "D", textEn: "Reduce rainfall", textMr: "पर्जन्य कमी करतात", isCorrect: false },
      ],
    },
    {
      textEn: "What is land use?",
      textMr: "भूउपयोग म्हणजे काय?",
      explanationEn: "The use of land by humans for various purposes such as agriculture, forest, construction, industry, etc. is called land use.",
      explanationMr: "मानवाने शेती, वन, बांधकाम, उद्योग आदी विविध कारणांसाठी जमिनीचा जो उपयोग करतो त्याला भूउपयोग म्हणतात.",
      options: [
        { label: "A", textEn: "Land measurement", textMr: "जमिनीची मोजणी", isCorrect: false },
        { label: "B", textEn: "Use of land for various purposes", textMr: "जमिनीचा विविध कारणांसाठी केलेला उपयोग", isCorrect: true },
        { label: "C", textEn: "Sale of land", textMr: "जमिनीची विक्री", isCorrect: false },
        { label: "D", textEn: "Classification of land", textMr: "जमिनीचे वर्गीकरण", isCorrect: false },
      ],
    },
    {
      textEn: "For which purpose is most land in India used?",
      textMr: "भारतात सर्वाधिक जमीन कोणत्या कारणासाठी वापरली जाते?",
      explanationEn: "Most land in India is used for agriculture. India is an agriculture-based country.",
      explanationMr: "भारतात सर्वाधिक जमीन शेतीसाठी वापरली जाते. भारत कृषिप्रधान देश आहे.",
      options: [
        { label: "A", textEn: "Forests", textMr: "वने", isCorrect: false },
        { label: "B", textEn: "Agriculture", textMr: "शेती", isCorrect: true },
        { label: "C", textEn: "Construction", textMr: "बांधकाम", isCorrect: false },
        { label: "D", textEn: "Industry", textMr: "उद्योग", isCorrect: false },
      ],
    },
    {
      textEn: "What percentage of a country's total land should be forest?",
      textMr: "वन जमिनीचे प्रमाण देशाच्या एकूण जमिनीच्या किती टक्के असावे?",
      explanationEn: "For ecological balance, 33% of a country's total land should be covered with forests.",
      explanationMr: "पर्यावरणीय संतुलनासाठी देशाच्या एकूण भूभागाच्या ३३% जमीन वनांनी व्यापलेली असावी.",
      options: [
        { label: "A", textEn: "10%", textMr: "१०%", isCorrect: false },
        { label: "B", textEn: "20%", textMr: "२०%", isCorrect: false },
        { label: "C", textEn: "33%", textMr: "३३%", isCorrect: true },
        { label: "D", textEn: "50%", textMr: "५०%", isCorrect: false },
      ],
    },
    {
      textEn: "How often is the census conducted in India?",
      textMr: "भारतात प्रत्येक किती वर्षांनी जनगणना होते?",
      explanationEn: "The census in India is conducted every 10 years. The first census was held in 1872 AD.",
      explanationMr: "भारतात दर दहा वर्षांनी जनगणना होते. पहिली जनगणना इ.स. १८७२ मध्ये झाली.",
      options: [
        { label: "A", textEn: "5 years", textMr: "५ वर्षे", isCorrect: false },
        { label: "B", textEn: "7 years", textMr: "७ वर्षे", isCorrect: false },
        { label: "C", textEn: "10 years", textMr: "१० वर्षे", isCorrect: true },
        { label: "D", textEn: "15 years", textMr: "१५ वर्षे", isCorrect: false },
      ],
    },
    {
      textEn: "What is population density?",
      textMr: "लोकसंख्येची घनता म्हणजे काय?",
      explanationEn: "The number of people living per square kilometer is called population density.",
      explanationMr: "एका चौरस किलोमीटर क्षेत्रात राहणाऱ्या लोकांच्या संख्येला लोकसंख्येची घनता म्हणतात.",
      options: [
        { label: "A", textEn: "Total population", textMr: "एकूण लोकसंख्या", isCorrect: false },
        { label: "B", textEn: "Population per sq. km", textMr: "प्रति चौ. किमी क्षेत्रातील लोकसंख्या", isCorrect: true },
        { label: "C", textEn: "Annual population growth", textMr: "वार्षिक लोकसंख्यावाढ", isCorrect: false },
        { label: "D", textEn: "Urban population", textMr: "शहरी लोकसंख्या", isCorrect: false },
      ],
    },
    {
      textEn: "What factors affect population?",
      textMr: "लोकसंख्येवर परिणाम करणारे घटक कोणते?",
      explanationEn: "Population is affected by three factors: birth rate, death rate, and migration (immigration/emigration).",
      explanationMr: "लोकसंख्येवर जन्मदर, मृत्युदर आणि स्थलांतर (immigration/emigration) या तीन घटकांचा परिणाम होतो.",
      options: [
        { label: "A", textEn: "Only birth rate", textMr: "फक्त जन्मदर", isCorrect: false },
        { label: "B", textEn: "Birth rate, death rate, and migration", textMr: "जन्मदर, मृत्युदर व स्थलांतर", isCorrect: true },
        { label: "C", textEn: "Only migration", textMr: "फक्त स्थलांतर", isCorrect: false },
        { label: "D", textEn: "Only death rate", textMr: "फक्त मृत्युदर", isCorrect: false },
      ],
    },
    {
      textEn: "On which factors does population distribution depend?",
      textMr: "लोकसंख्येचे वितरण कोणत्या घटकांवर अवलंबून असते?",
      explanationEn: "Topography, climate, soil, water, natural resources, and economic factors affect population distribution.",
      explanationMr: "भूरूप, हवामान, मृदा, पाणी, नैसर्गिक संसाधने आणि आर्थिक घटक लोकसंख्या वितरणावर परिणाम करतात.",
      options: [
        { label: "A", textEn: "Only on climate", textMr: "फक्त हवामानावर", isCorrect: false },
        { label: "B", textEn: "Topography, climate, soil, water, resources", textMr: "भूरूप, हवामान, मृदा, पाणी, संसाधने", isCorrect: true },
        { label: "C", textEn: "Only on industries", textMr: "फक्त उद्योगांवर", isCorrect: false },
        { label: "D", textEn: "Only on government policies", textMr: "फक्त सरकारी धोरणांवर", isCorrect: false },
      ],
    },
    {
      textEn: "What are primary industries?",
      textMr: "प्राथमिक उद्योग म्हणजे काय?",
      explanationEn: "Industries that directly extract or produce natural resources are primary industries. E.g., agriculture, fishing, mining.",
      explanationMr: "नैसर्गिक साधनसंपत्तीचे थेट उत्पादन किंवा उत्खनन करणारे उद्योग म्हणजे प्राथमिक उद्योग. उदा. शेती, मासेमारी, खाणकाम.",
      options: [
        { label: "A", textEn: "Factories", textMr: "कारखाने", isCorrect: false },
        { label: "B", textEn: "Direct extraction of natural resources", textMr: "नैसर्गिक साधनसंपत्तीचे थेट उत्खनन", isCorrect: true },
        { label: "C", textEn: "Service sector", textMr: "सेवा क्षेत्र", isCorrect: false },
        { label: "D", textEn: "Information technology", textMr: "माहिती तंत्रज्ञान", isCorrect: false },
      ],
    },
    {
      textEn: "Which is an important textile industry center in India?",
      textMr: "भारतातील महत्त्वाचे कापड उद्योगाचे केंद्र कोणते?",
      explanationEn: "Mumbai is the leading center of the textile industry in India. Hence, Mumbai is also called the 'Cotton City'.",
      explanationMr: "मुंबई भारतातील कापड उद्योगाचे प्रमुख केंद्र आहे. त्यामुळे मुंबईला 'कापूस नगरी' असेही म्हणतात.",
      options: [
        { label: "A", textEn: "Jamshedpur", textMr: "जमशेदपूर", isCorrect: false },
        { label: "B", textEn: "Mumbai", textMr: "मुंबई", isCorrect: true },
        { label: "C", textEn: "Bhilai", textMr: "भिलाई", isCorrect: false },
        { label: "D", textEn: "Durgapur", textMr: "दुर्गापूर", isCorrect: false },
      ],
    },
    {
      textEn: "What raw materials are needed for the steel industry?",
      textMr: "पोलाद उद्योगासाठी कोणते कच्चे माल लागते?",
      explanationEn: "Iron ore and coal are the main raw materials required for the steel industry.",
      explanationMr: "पोलाद उद्योगासाठी लोखंडाचे धातूक (Iron ore) आणि कोळसा हे मुख्य कच्चे माल लागतात.",
      options: [
        { label: "A", textEn: "Cotton and sugarcane", textMr: "कापूस व ऊस", isCorrect: false },
        { label: "B", textEn: "Iron ore and coal", textMr: "लोखंड व कोळसा", isCorrect: true },
        { label: "C", textEn: "Gold and silver", textMr: "सोने व चांदी", isCorrect: false },
        { label: "D", textEn: "Fertilizers and chemicals", textMr: "खते व रसायने", isCorrect: false },
      ],
    },
    {
      textEn: "Which is the main center of information technology industry in India?",
      textMr: "माहिती तंत्रज्ञान उद्योगाचे भारतातील प्रमुख केंद्र कोणते?",
      explanationEn: "Bengaluru is the main center of the IT industry in India. It is called the 'Silicon Valley of India'.",
      explanationMr: "बेंगलुरू हे भारतातील माहिती तंत्रज्ञान उद्योगाचे प्रमुख केंद्र आहे. त्याला 'भारताची सिलिकॉन व्हॅली' म्हणतात.",
      options: [
        { label: "A", textEn: "Kolkata", textMr: "कोलकाता", isCorrect: false },
        { label: "B", textEn: "Jamshedpur", textMr: "जमशेदपूर", isCorrect: false },
        { label: "C", textEn: "Bengaluru", textMr: "बेंगलुरू", isCorrect: true },
        { label: "D", textEn: "Bhopal", textMr: "भोपाळ", isCorrect: false },
      ],
    },
    {
      textEn: "What is a map scale?",
      textMr: "नकाशाचा मापक (Scale) म्हणजे काय?",
      explanationEn: "The ratio between distance on the map and the actual distance on the ground is called the scale.",
      explanationMr: "नकाशावरील अंतर आणि प्रत्यक्ष जमिनीवरील अंतर यांचे गुणोत्तर म्हणजे मापक होय.",
      options: [
        { label: "A", textEn: "Color of the map", textMr: "नकाशाचा रंग", isCorrect: false },
        { label: "B", textEn: "Ratio of map distance to actual distance", textMr: "नकाशावरील अंतर आणि प्रत्यक्ष जमिनीवरील अंतर यांचे गुणोत्तर", isCorrect: true },
        { label: "C", textEn: "Size of the map", textMr: "नकाशाचा आकार", isCorrect: false },
        { label: "D", textEn: "Symbols on the map", textMr: "नकाशावरील चिन्हे", isCorrect: false },
      ],
    },
    {
      textEn: "For what purpose is a large scale map used?",
      textMr: "मोठ्या मापकाचा (Large Scale) नकाशा कशासाठी वापरतात?",
      explanationEn: "A large scale map shows more detailed information about a small area. E.g., a city map.",
      explanationMr: "मोठ्या मापकाच्या नकाशात लहान क्षेत्राची अधिक तपशीलवार माहिती दाखवता येते. उदा. शहराचा नकाशा.",
      options: [
        { label: "A", textEn: "To show the world", textMr: "जग दाखवण्यासाठी", isCorrect: false },
        { label: "B", textEn: "Detailed description of a small area", textMr: "लहान क्षेत्राचे तपशीलवार वर्णन", isCorrect: true },
        { label: "C", textEn: "To show oceans", textMr: "महासागर दाखवण्यासाठी", isCorrect: false },
        { label: "D", textEn: "To show continents", textMr: "खंड दाखवण्यासाठी", isCorrect: false },
      ],
    },
    {
      textEn: "What does a scale of 1:50,000 mean?",
      textMr: "१:५०,००० मापकाचा अर्थ काय?",
      explanationEn: "1:50,000 means 1 centimeter on the map represents 50,000 centimeters (500 meters) on the ground.",
      explanationMr: "१:५०,००० म्हणजे नकाशावरील १ सेंटीमीटर जमिनीवरील ५०,००० सेंटीमीटर (५०० मीटर) इतके अंतर दर्शवते.",
      options: [
        { label: "A", textEn: "1 m on map = 50,000 m on ground", textMr: "नकाशावर १ मीटर = जमिनीवर ५०,००० मीटर", isCorrect: false },
        { label: "B", textEn: "1 cm on map = 50,000 cm on ground", textMr: "नकाशावर १ सेंटीमीटर = जमिनीवर ५०,००० सेंटीमीटर", isCorrect: true },
        { label: "C", textEn: "50,000 km on map = 1 km on ground", textMr: "नकाशावर ५०,००० किमी = जमिनीवर १ किमी", isCorrect: false },
        { label: "D", textEn: "1 km on map = 50,000 km on ground", textMr: "नकाशावर १ किमी = जमिनीवर ५०,००० किमी", isCorrect: false },
      ],
    },
    {
      textEn: "What is a field visit?",
      textMr: "क्षेत्रभेट म्हणजे काय?",
      explanationEn: "A field visit is observing, collecting information, and studying a subject by visiting the actual place.",
      explanationMr: "एखाद्या विषयाचा प्रत्यक्ष ठिकाणी जाऊन निरीक्षण, माहिती संकलन व अभ्यास करणे म्हणजे क्षेत्रभेट.",
      options: [
        { label: "A", textEn: "Getting information from books", textMr: "पुस्तकातून माहिती घेणे", isCorrect: false },
        { label: "B", textEn: "Collecting information by visiting the actual place", textMr: "प्रत्यक्ष ठिकाणी जाऊन माहिती संकलन करणे", isCorrect: true },
        { label: "C", textEn: "Reading maps", textMr: "नकाशा वाचणे", isCorrect: false },
        { label: "D", textEn: "Searching information on internet", textMr: "इंटरनेटवर माहिती शोधणे", isCorrect: false },
      ],
    },
    {
      textEn: "What instruments are used during a field visit?",
      textMr: "क्षेत्रभेटीत कोणती उपकरणे वापरतात?",
      explanationEn: "During a field visit, instruments like compass, map, notebook, camera, recorder, etc. are used.",
      explanationMr: "क्षेत्रभेटीत कंपास, नकाशा, नोटबुक, कॅमेरा, रेकॉर्डर आदी उपकरणे वापरतात.",
      options: [
        { label: "A", textEn: "Only books", textMr: "फक्त पुस्तके", isCorrect: false },
        { label: "B", textEn: "Compass, map, notebook, camera", textMr: "कंपास, नकाशा, नोटबुक, कॅमेरा", isCorrect: true },
        { label: "C", textEn: "Only camera", textMr: "फक्त कॅमेरा", isCorrect: false },
        { label: "D", textEn: "Only map", textMr: "फक्त नकाशा", isCorrect: false },
      ],
    },
    {
      textEn: "What is done after a field visit?",
      textMr: "क्षेत्रभेटीनंतर काय करतात?",
      explanationEn: "After a field visit, the collected information is analyzed and a report is prepared.",
      explanationMr: "क्षेत्रभेटीनंतर संकलित माहितीचे विश्लेषण करून अहवाल तयार केला जातो.",
      options: [
        { label: "A", textEn: "Take rest", textMr: "विश्रांती घेतात", isCorrect: false },
        { label: "B", textEn: "Compile information and prepare a report", textMr: "माहितीचे संकलन व अहवाल तयार करतात", isCorrect: true },
        { label: "C", textEn: "Visit again", textMr: "पुन्हा भेट देतात", isCorrect: false },
        { label: "D", textEn: "Forget the information", textMr: "माहिती विसरतात", isCorrect: false },
      ],
    },
    {
      textEn: "With what is the intensity of an earthquake measured?",
      textMr: "भूकंपाचे मोजमाप कशाने करतात?",
      explanationEn: "The intensity of earthquake waves is measured using a seismograph.",
      explanationMr: "भूकंपाच्या लाटांचे मोजमाप सिस्मोग्राफ या उपकरणाद्वारे केले जाते.",
      options: [
        { label: "A", textEn: "Barometer", textMr: "बॅरोमीटर", isCorrect: false },
        { label: "B", textEn: "Thermometer", textMr: "थर्मामीटर", isCorrect: false },
        { label: "C", textEn: "Seismograph", textMr: "सिस्मोग्राफ", isCorrect: true },
        { label: "D", textEn: "Hygrometer", textMr: "हायग्रोमीटर", isCorrect: false },
      ],
    },
    {
      textEn: "What causes tides?",
      textMr: "भरती-ओहोटी कशामुळे होते?",
      explanationEn: "Tides are caused by the gravitational force of the Sun and Moon on ocean water.",
      explanationMr: "सूर्य व चंद्राच्या गुरुत्वाकर्षण शक्तीमुळे समुद्राच्या पाण्यात भरती व ओहोटी होते.",
      options: [
        { label: "A", textEn: "Due to wind", textMr: "वाऱ्यामुळे", isCorrect: false },
        { label: "B", textEn: "Due to gravity of Sun and Moon", textMr: "सूर्य व चंद्राच्या गुरुत्वाकर्षणामुळे", isCorrect: true },
        { label: "C", textEn: "Due to earthquakes", textMr: "भूकंपामुळे", isCorrect: false },
        { label: "D", textEn: "Due to climate change", textMr: "हवामान बदलामुळे", isCorrect: false },
      ],
    },
    {
      textEn: "What is the literacy rate?",
      textMr: "साक्षरता दर म्हणजे काय?",
      explanationEn: "The proportion of literate people (who can read and write) in the total population is called the literacy rate.",
      explanationMr: "एकूण लोकसंख्येत लिहिता-वाचता येणाऱ्या लोकांच्या प्रमाणाला साक्षरता दर म्हणतात.",
      options: [
        { label: "A", textEn: "Average age of people", textMr: "लोकांचे सरासरी वय", isCorrect: false },
        { label: "B", textEn: "Proportion of literate people in total population", textMr: "एकूण लोकसंख्येत साक्षरांचे प्रमाण", isCorrect: true },
        { label: "C", textEn: "Proportion of children going to school", textMr: "शाळेत जाणाऱ्या मुलांचे प्रमाण", isCorrect: false },
        { label: "D", textEn: "Proportion of graduates", textMr: "पदवीधरांचे प्रमाण", isCorrect: false },
      ],
    },
    {
      textEn: "What is a Cottage Industry?",
      textMr: "कुटीर उद्योग (Cottage Industry) म्हणजे काय?",
      explanationEn: "Producing goods at home level with simple tools on a small scale is a cottage industry. E.g., weaving, pottery.",
      explanationMr: "घरगुती पातळीवर साध्या साधनांनी लहान प्रमाणात वस्तू तयार करणे म्हणजे कुटीर उद्योग. उदा. विणकाम, मातीची भांडी.",
      options: [
        { label: "A", textEn: "Production in large factories", textMr: "मोठ्या कारखान्यात उत्पादन", isCorrect: false },
        { label: "B", textEn: "Small-scale production at home level", textMr: "घरगुती पातळीवर लहान प्रमाणात उत्पादन", isCorrect: true },
        { label: "C", textEn: "Multinational company industries", textMr: "बहुराष्ट्रीय कंपन्यांचे उद्योग", isCorrect: false },
        { label: "D", textEn: "Government factories", textMr: "सरकारी कारखाने", isCorrect: false },
      ],
    },
  ],
};

export default data;
