import type { QuestionSetInput } from "./types";

// Source: All questions & answer/AMVI_Std9_Geo_English.pdf + AMVI_Std9_Geo_Marathi.pdf
// Both PDFs share identical question numbering/options/answers (49 MCQs).
const data: QuestionSetInput = {
  standard: { code: "STD9", nameEn: "Standard 9", nameMr: "इयत्ता ९वी", sortOrder: 9 },
  subject: { code: "GEO", nameEn: "Geography", nameMr: "भूगोल", sortOrder: 1 },
  questions: [
    {
      textEn: "What is the main purpose of distributional maps?",
      textMr: "वितरण नकाशांचा मुख्य उद्देश कोणता आहे?",
      explanationEn:
        "Distributional maps are used to show the distribution of geographical features like population, rainfall, crops.",
      explanationMr:
        "वितरण नकाशे भौगोलिक घटकांचे (लोकसंख्या, पाऊस, पिके) वितरण दाखवण्यासाठी वापरले जातात.",
      options: [
        { label: "A", textEn: "To show boundaries of countries", textMr: "देशाच्या सीमा दाखवणे", isCorrect: false },
        { label: "B", textEn: "To show distribution of geographical features", textMr: "भौगोलिक घटकांचे वितरण दाखवणे", isCorrect: true },
        { label: "C", textEn: "To show road routes", textMr: "रस्त्यांचे मार्ग दाखवणे", isCorrect: false },
        { label: "D", textEn: "To show river flow", textMr: "नद्यांचे प्रवाह दाखवणे", isCorrect: false },
      ],
    },
    {
      textEn: "In a dot map, one dot represents how many units?",
      textMr: "बिंदू नकाशात एक बिंदू किती एककांचे प्रतिनिधित्व करतो?",
      explanationEn: "In a dot map, one dot represents a decided value (e.g., 1000 population) as per the map scale.",
      explanationMr: "बिंदू नकाशात एक बिंदू ठरविलेल्या मूल्यानुसार (उदा. १००० लोकसंख्या) प्रतिनिधित्व करतो.",
      options: [
        { label: "A", textEn: "One", textMr: "एक", isCorrect: false },
        { label: "B", textEn: "Ten", textMr: "दहा", isCorrect: false },
        { label: "C", textEn: "As per the decided value", textMr: "ठरविलेल्या मूल्यानुसार", isCorrect: true },
        { label: "D", textEn: "Hundred", textMr: "शंभर", isCorrect: false },
      ],
    },
    {
      textEn: "In a choropleth map, the depth of colour indicates what?",
      textMr: "छायांकन नकाशात रंगाची खोली कशाचे निर्देशन करते?",
      explanationEn:
        "In a choropleth map, the depth of colour indicates density or proportion. Darker colour shows higher density.",
      explanationMr: "छायांकन नकाशात रंगाची खोली घनता किंवा प्रमाण दर्शवते. गडद रंग जास्त घनता दाखवतो.",
      options: [
        { label: "A", textEn: "Temperature", textMr: "तापमान", isCorrect: false },
        { label: "B", textEn: "Density or proportion", textMr: "घनता किंवा प्रमाण", isCorrect: true },
        { label: "C", textEn: "Altitude", textMr: "उंची", isCorrect: false },
        { label: "D", textEn: "Vegetation", textMr: "वनस्पती", isCorrect: false },
      ],
    },
    {
      textEn: "In a flow map, what does the width of the arrow indicate?",
      textMr: "वाहप्रवाह नकाशात बाणाची रुंदी काय दर्शवते?",
      explanationEn: "In a flow map, the width of the arrow indicates the quantity or number of traffic, trade or population movement.",
      explanationMr: "वाहप्रवाह नकाशात बाणाची रुंदी वाहतूक, व्यापार किंवा लोकसंख्येचे प्रमाण दर्शवते.",
      options: [
        { label: "A", textEn: "Direction", textMr: "दिशा", isCorrect: false },
        { label: "B", textEn: "Speed", textMr: "वेग", isCorrect: false },
        { label: "C", textEn: "Quantity or number", textMr: "प्रमाण किंवा संख्या", isCorrect: true },
        { label: "D", textEn: "Distance", textMr: "अंतर", isCorrect: false },
      ],
    },
    {
      textEn: "Isotherms are used in which type of map?",
      textMr: "समताप रेषा कोणत्या नकाशात वापरली जाते?",
      explanationEn: "Isotherms connect places of equal temperature and are used in temperature distribution maps.",
      explanationMr: "समताप रेषा (Isotherms) समान तापमानाच्या ठिकाणांना जोडतात आणि तापमान वितरण नकाशात वापरली जाते.",
      options: [
        { label: "A", textEn: "Dot map", textMr: "बिंदू नकाशा", isCorrect: false },
        { label: "B", textEn: "Temperature distribution map", textMr: "तापमान वितरण नकाशा", isCorrect: true },
        { label: "C", textEn: "Population map", textMr: "लोकसंख्या नकाशा", isCorrect: false },
        { label: "D", textEn: "Flow map", textMr: "वाहप्रवाह नकाशा", isCorrect: false },
      ],
    },
    {
      textEn: "Endogenetic movements originate from which part of the Earth?",
      textMr: "अंतर्जात हालचाली पृथ्वीच्या कोणत्या भागातून निर्माण होतात?",
      explanationEn: "Endogenetic movements originate from the heat and pressure in the interior of the Earth.",
      explanationMr: "अंतर्जात हालचाली पृथ्वीच्या अंतरंगातील उष्णता व दाबामुळे निर्माण होतात.",
      options: [
        { label: "A", textEn: "Atmosphere", textMr: "वायुमंडळ", isCorrect: false },
        { label: "B", textEn: "Ocean", textMr: "महासागर", isCorrect: false },
        { label: "C", textEn: "Interior of the Earth", textMr: "पृथ्वीचे अंतरंग", isCorrect: true },
        { label: "D", textEn: "Vegetation", textMr: "वनस्पती", isCorrect: false },
      ],
    },
    {
      textEn: "Which instrument is used to measure the intensity of earthquakes?",
      textMr: "भूकंपाची तीव्रता मोजण्यासाठी कोणते साधन वापरले जाते?",
      explanationEn: "Seismograph is the instrument used to record the intensity and waves of earthquakes.",
      explanationMr: "सिस्मोग्राफ हे भूकंपाच्या लहरींची तीव्रता नोंदवणारे साधन आहे.",
      options: [
        { label: "A", textEn: "Barometer", textMr: "बॅरोमीटर", isCorrect: false },
        { label: "B", textEn: "Seismograph", textMr: "सिस्मोग्राफ", isCorrect: true },
        { label: "C", textEn: "Thermometer", textMr: "थर्मोमीटर", isCorrect: false },
        { label: "D", textEn: "Anemometer", textMr: "ॲनिमोमीटर", isCorrect: false },
      ],
    },
    {
      textEn: "What is the molten rock that comes out during volcanic activity called?",
      textMr: "ज्वालामुखीय क्रियेतून बाहेर पडणाऱ्या वितळलेल्या खडकाला काय म्हणतात?",
      explanationEn: "The molten rock that erupts from a volcano is called lava; when inside the Earth it is called magma.",
      explanationMr: "ज्वालामुखीतून बाहेर पडणाऱ्या वितळलेल्या खडकाला लाव्हा म्हणतात; पृथ्वीच्या आत असताना त्याला मॅग्मा म्हणतात.",
      options: [
        { label: "A", textEn: "Magma", textMr: "मॅग्मा", isCorrect: false },
        { label: "B", textEn: "Lava", textMr: "लाव्हा", isCorrect: true },
        { label: "C", textEn: "Granite", textMr: "ग्रॅनाइट", isCorrect: false },
        { label: "D", textEn: "Basalt", textMr: "बेसाल्ट", isCorrect: false },
      ],
    },
    {
      textEn: "The Himalayas were formed due to which type of movements?",
      textMr: "हिमालय पर्वत कोणत्या प्रकारच्या हालचालींमुळे निर्माण झाला?",
      explanationEn:
        "The Himalayas were formed due to diastrophic/horizontal movements, i.e., the collision of the Indian plate and the Eurasian plate.",
      explanationMr:
        "हिमालय पर्वत दीर्घकालीन भूकंपीय (दिआस्ट्रोफिक) क्षैतिज हालचालींमुळे, म्हणजे भारतीय प्लेट व युरेशियन प्लेटच्या टक्करामुळे निर्माण झाला.",
      options: [
        { label: "A", textEn: "Exogenetic movements", textMr: "बाह्यजात हालचाली", isCorrect: false },
        { label: "B", textEn: "Earthquakes", textMr: "भूकंप", isCorrect: false },
        { label: "C", textEn: "Diastrophic/horizontal movements", textMr: "दीर्घकालीन/क्षैतिज भूकंपीय हालचाली", isCorrect: true },
        { label: "D", textEn: "Volcanism", textMr: "ज्वालामुखी", isCorrect: false },
      ],
    },
    {
      textEn: "An earthquake with magnitude 7 or more on the Richter scale is called?",
      textMr: "रिश्टर स्केलवर ७ किंवा त्यापेक्षा जास्त तीव्रतेच्या भूकंपाला काय म्हणतात?",
      explanationEn: "An earthquake with magnitude 7 or more on the Richter scale is called a major or great earthquake.",
      explanationMr: "रिश्टर स्केलवर ७ किंवा त्यापेक्षा जास्त तीव्रतेच्या भूकंपाला महाभूकंप (great/major earthquake) म्हणतात.",
      options: [
        { label: "A", textEn: "Mild earthquake", textMr: "सौम्य भूकंप", isCorrect: false },
        { label: "B", textEn: "Moderate earthquake", textMr: "मध्यम भूकंप", isCorrect: false },
        { label: "C", textEn: "Major/Great earthquake", textMr: "महाभूकंप", isCorrect: true },
        { label: "D", textEn: "Microseism", textMr: "मायक्रोसिझम", isCorrect: false },
      ],
    },
    {
      textEn: "Exogenetic processes are caused by which forces?",
      textMr: "बाह्यजात प्रक्रिया कोणत्या शक्तींमुळे घडतात?",
      explanationEn: "Exogenetic processes are caused by external forces like solar heat, wind, water, and glaciers.",
      explanationMr: "बाह्यजात प्रक्रिया सूर्याची उष्णता, वारा, पाणी, हिमनदी यांसारख्या बाहेरील शक्तींमुळे घडतात.",
      options: [
        { label: "A", textEn: "Internal forces of the Earth", textMr: "पृथ्वीच्या आतील शक्ती", isCorrect: false },
        { label: "B", textEn: "External forces (sun, wind, water)", textMr: "बाहेरील शक्ती (सूर्य, वारा, पाणी)", isCorrect: true },
        { label: "C", textEn: "Gravity only", textMr: "गुरुत्वाकर्षण फक्त", isCorrect: false },
        { label: "D", textEn: "Volcanism", textMr: "ज्वालामुखी", isCorrect: false },
      ],
    },
    {
      textEn: "What is the physical breakdown of rocks called?",
      textMr: "खडकांच्या भौतिक विघटनाला काय म्हणतात?",
      explanationEn: "The physical breakdown of rocks into smaller pieces without chemical change is called mechanical (physical) weathering.",
      explanationMr: "खडकांचे तुकडे होणे परंतु रासायनिक बदल न होणे यास यांत्रिक (भौतिक) विच्छेदन म्हणतात.",
      options: [
        { label: "A", textEn: "Chemical weathering", textMr: "रासायनिक विच्छेदन", isCorrect: false },
        { label: "B", textEn: "Mechanical weathering", textMr: "यांत्रिक विच्छेदन", isCorrect: true },
        { label: "C", textEn: "Biological weathering", textMr: "जैविक विच्छेदन", isCorrect: false },
        { label: "D", textEn: "Erosion", textMr: "अपरधन", isCorrect: false },
      ],
    },
    {
      textEn: "The landform created by deposition of sediment carried by a river at its mouth is called?",
      textMr: "नदीच्या खाली वाहून नेलेल्या गाळापासून निर्माण होणाऱ्या भूरूपाला काय म्हणतात?",
      explanationEn: "When a river meets the sea, it deposits sediment forming a delta (triangular landform). The Ganga-Brahmaputra delta is the world's largest.",
      explanationMr: "नदी समुद्राला मिळताना गाळ जमा करते त्यातून डेल्टा (त्रिभुज प्रदेश) तयार होतो. गंगा-ब्रह्मपुत्रा डेल्टा जगातील सर्वात मोठा आहे.",
      options: [
        { label: "A", textEn: "Canyon", textMr: "घाटी", isCorrect: false },
        { label: "B", textEn: "Waterfall", textMr: "धबधबा", isCorrect: false },
        { label: "C", textEn: "Delta", textMr: "डेल्टा", isCorrect: true },
        { label: "D", textEn: "Plain", textMr: "मैदान", isCorrect: false },
      ],
    },
    {
      textEn: "The process of landform formation by wind is called?",
      textMr: "वाऱ्यामुळे घडणाऱ्या भूरूप निर्माण प्रक्रियेला काय म्हणतात?",
      explanationEn: "Landform formation by wind is called Aeolian action. Sand dunes in deserts are examples of Aeolian landforms.",
      explanationMr: "वाऱ्यामुळे होणाऱ्या भूरूप निर्माणाला वायव्य (ऐओलियन) क्रिया म्हणतात. वाळवंटातील बलुई टेकड्या (Dunes) हे त्याचे उदाहरण आहे.",
      options: [
        { label: "A", textEn: "Glacial action", textMr: "हिमनदी क्रिया", isCorrect: false },
        { label: "B", textEn: "Aeolian action", textMr: "वायव्य क्रिया", isCorrect: true },
        { label: "C", textEn: "Marine action", textMr: "सागरी क्रिया", isCorrect: false },
        { label: "D", textEn: "Fluvial action", textMr: "नदी क्रिया", isCorrect: false },
      ],
    },
    {
      textEn: "The U-shaped valley created by a glacier is called?",
      textMr: "हिमनदीने निर्माण केलेल्या U-आकाराच्या दरीला काय म्हणतात?",
      explanationEn: "A glacier creates a U-shaped wide valley called Glacial Trough, while a river creates a V-shaped narrow valley.",
      explanationMr: "हिमनदी U-आकाराची रुंद दरी (Glacial Trough) तयार करते, तर नदी V-आकाराची अरुंद दरी तयार करते.",
      options: [
        { label: "A", textEn: "River valley", textMr: "नदी दरी", isCorrect: false },
        { label: "B", textEn: "Glacial trough", textMr: "हिमखात", isCorrect: true },
        { label: "C", textEn: "Canyon", textMr: "घाटी", isCorrect: false },
        { label: "D", textEn: "Valley plain", textMr: "खोऱ्याचे मैदान", isCorrect: false },
      ],
    },
    {
      textEn: "The vertical cliff formed by sea waves is called?",
      textMr: "समुद्राच्या लाटांमुळे तयार होणाऱ्या उभ्या कड्याला काय म्हणतात?",
      explanationEn: "Sea cliffs are vertical rock faces formed by the erosional action of sea waves on the coast.",
      explanationMr: "समुद्राच्या लाटांच्या अपरधनामुळे किनाऱ्यावर उभ्या कड्या (Sea Cliffs) तयार होतात.",
      options: [
        { label: "A", textEn: "Headland", textMr: "भूशीर", isCorrect: false },
        { label: "B", textEn: "Sea cliff", textMr: "सागरी भिंत/सपाट", isCorrect: true },
        { label: "C", textEn: "Island", textMr: "बेट", isCorrect: false },
        { label: "D", textEn: "Coast", textMr: "किनारपट्टी", isCorrect: false },
      ],
    },
    {
      textEn: "Pillars of rock formed by wind erosion in deserts are called?",
      textMr: "वाळवंटात वाऱ्यामुळे तयार होणाऱ्या बालुकास्तंभाला काय म्हणतात?",
      explanationEn: "Yardangs are rock formations shaped by wind erosion where soft rock is worn away leaving hard rock pillars.",
      explanationMr: "वाऱ्याच्या अपरधनामुळे मऊ खडक वाहून जातो आणि कठीण खडकाचे यार्डांग (Yardang) तयार होतात.",
      options: [
        { label: "A", textEn: "Inselberg", textMr: "इनसेलबर्ग", isCorrect: false },
        { label: "B", textEn: "Sand dune", textMr: "बलुई टेकडी", isCorrect: false },
        { label: "C", textEn: "Yardang", textMr: "यार्डांग", isCorrect: true },
        { label: "D", textEn: "Zara", textMr: "झारा", isCorrect: false },
      ],
    },
    {
      textEn: "Landslides mainly occur in which areas?",
      textMr: "भूस्खलन (Landslide) प्रामुख्याने कोठे होते?",
      explanationEn: "Landslides mainly occur in hilly and slope regions due to heavy rain, earthquakes, or deforestation.",
      explanationMr: "भूस्खलन प्रामुख्याने डोंगराळ व उतार प्रदेशांत होते. जास्त पाऊस, भूकंप किंवा झाडे तोडल्यामुळे भूस्खलन होऊ शकते.",
      options: [
        { label: "A", textEn: "Plains", textMr: "मैदानी प्रदेश", isCorrect: false },
        { label: "B", textEn: "Hilly and slope regions", textMr: "डोंगराळ व उतार प्रदेश", isCorrect: true },
        { label: "C", textEn: "Sea coasts", textMr: "समुद्रकिनारे", isCorrect: false },
        { label: "D", textEn: "Deserts", textMr: "वाळवंट", isCorrect: false },
      ],
    },
    {
      textEn: "The curve formed by a river in its middle course is called?",
      textMr: "नदीच्या आतील वळणाला (Meander) काय म्हणतात?",
      explanationEn: "As a river flows slowly in the plains, it forms S-shaped curves called meanders. Deposition occurs on the inner bend.",
      explanationMr: "नदी मैदानी भागात संथ वाहताना नागमोडी वळणे (Meanders) घेते. या वळणाच्या आतील बाजू जमा होते.",
      options: [
        { label: "A", textEn: "Delta", textMr: "डेल्टा", isCorrect: false },
        { label: "B", textEn: "Meander", textMr: "नागमोडी वळण", isCorrect: true },
        { label: "C", textEn: "Waterfall", textMr: "जलप्रपात", isCorrect: false },
        { label: "D", textEn: "Watershed", textMr: "जलविभाजक", isCorrect: false },
      ],
    },
    {
      textEn: "In India, the monsoon rain comes from which direction?",
      textMr: "भारतात मान्सून पाऊस कोणत्या दिशेने येतो?",
      explanationEn: "In India, the summer monsoon comes from the south-west direction from the Arabian Sea and Bay of Bengal. June to September is the monsoon season.",
      explanationMr: "भारतात उन्हाळी मान्सून नैऋत्य दिशेने अरबी समुद्र व बंगालच्या उपसागरातून येतो. जून ते सप्टेंबर हा मान्सून काळ आहे.",
      options: [
        { label: "A", textEn: "North-East", textMr: "उत्तर-पूर्व", isCorrect: false },
        { label: "B", textEn: "South-West", textMr: "नैऋत्य", isCorrect: true },
        { label: "C", textEn: "North-West", textMr: "उत्तर-पश्चिम", isCorrect: false },
        { label: "D", textEn: "South-East", textMr: "आग्नेय", isCorrect: false },
      ],
    },
    {
      textEn: "Where does India receive the highest rainfall?",
      textMr: "भारतात सर्वाधिक पाऊस कोठे पडतो?",
      explanationEn: "Mawsynram in Meghalaya is one of the wettest places on Earth with an average annual rainfall of about 11,871 mm.",
      explanationMr: "मेघालयातील मासिनराम हे जगातील सर्वाधिक पाऊस पडणारे ठिकाण आहे. येथे सरासरी ११,८७१ मिमी पाऊस पडतो.",
      options: [
        { label: "A", textEn: "Rajasthan", textMr: "राजस्थान", isCorrect: false },
        { label: "B", textEn: "Meghalaya (Mawsynram)", textMr: "मेघालय (मासिनराम)", isCorrect: true },
        { label: "C", textEn: "Delhi", textMr: "दिल्ली", isCorrect: false },
        { label: "D", textEn: "Gujarat", textMr: "गुजरात", isCorrect: false },
      ],
    },
    {
      textEn: "Orographic rainfall is caused by?",
      textMr: "ओरोग्राफिक पाऊस कशामुळे पडतो?",
      explanationEn: "Orographic rainfall occurs when moist air rises over mountains, cools, and condenses. The windward side receives more rain.",
      explanationMr: "ओरोग्राफिक (पर्वतीय) पाऊस ओलसर वारे पर्वताच्या उताराने वर चढताना थंड होऊन पडतो. वाऱ्याच्या बाजूला जास्त पाऊस पडतो.",
      options: [
        { label: "A", textEn: "Due to cold winds from sea", textMr: "समुद्रावरून येणाऱ्या थंड वाऱ्यांमुळे", isCorrect: false },
        { label: "B", textEn: "Due to moist air rising and cooling over mountains", textMr: "पर्वतांच्या अडथळ्यामुळे ओलसर वारे वर जाऊन थंड होतात", isCorrect: true },
        { label: "C", textEn: "Due to convergence of warm winds", textMr: "उष्ण वाऱ्यांच्या मिलनामुळे", isCorrect: false },
        { label: "D", textEn: "Due to Mediterranean climate", textMr: "भूमध्यसागरी हवामानामुळे", isCorrect: false },
      ],
    },
    {
      textEn: "Snow, hail and rain are all types of?",
      textMr: "हिम, गारा आणि पाऊस हे सर्व कशाचे प्रकार आहेत?",
      explanationEn: "Rain, snow, hail, sleet, and fog are all forms of precipitation — water falling to the ground in various states.",
      explanationMr: "पाऊस, हिम, गारा, धुके या सर्वांना अवपात (Precipitation) म्हणतात. पाण्याचे वेगवेगळ्या अवस्थांत जमिनीवर पडणे म्हणजे अवपात.",
      options: [
        { label: "A", textEn: "Evapotranspiration", textMr: "वाष्पोत्सर्जन", isCorrect: false },
        { label: "B", textEn: "Precipitation", textMr: "अवपात (Precipitation)", isCorrect: true },
        { label: "C", textEn: "Condensation", textMr: "संघनन", isCorrect: false },
        { label: "D", textEn: "Evaporation", textMr: "वाफीकरण", isCorrect: false },
      ],
    },
    {
      textEn: "Which instrument is used to measure rainfall?",
      textMr: "पावसाचे मोजमाप कोणत्या साधनाने केले जाते?",
      explanationEn: "Rainfall is measured by a rain gauge. Rainfall is recorded in millimetres.",
      explanationMr: "पावसाचे मोजमाप रेनगेज (पर्जन्यमापक) या साधनाने केले जाते. पावसाची नोंद मिलिमीटरमध्ये केली जाते.",
      options: [
        { label: "A", textEn: "Barometer", textMr: "बॅरोमीटर", isCorrect: false },
        { label: "B", textEn: "Thermometer", textMr: "थर्मोमीटर", isCorrect: false },
        { label: "C", textEn: "Rain gauge", textMr: "रेनगेज (पर्जन्यमापक)", isCorrect: true },
        { label: "D", textEn: "Hygrometer", textMr: "हायग्रोमीटर", isCorrect: false },
      ],
    },
    {
      textEn: "What is the average salinity of sea water?",
      textMr: "समुद्राच्या पाण्याची सरासरी क्षारता किती आहे?",
      explanationEn: "The average salinity of sea water is 35 ppt (parts per thousand). The Mediterranean Sea has the highest salinity.",
      explanationMr: "समुद्राच्या पाण्याची सरासरी क्षारता ३५ ppt (प्रती हजार भाग) आहे. सर्वाधिक क्षारता भूमध्य सागरात आढळते.",
      options: [
        { label: "A", textEn: "15 ppt", textMr: "१५ ppt", isCorrect: false },
        { label: "B", textEn: "35 ppt", textMr: "३५ ppt", isCorrect: true },
        { label: "C", textEn: "50 ppt", textMr: "५० ppt", isCorrect: false },
        { label: "D", textEn: "75 ppt", textMr: "७५ ppt", isCorrect: false },
      ],
    },
    {
      textEn: "Regular horizontal movements of sea water are called?",
      textMr: "समुद्राच्या प्रवाहांना काय म्हणतात?",
      explanationEn: "Regular horizontal movement of sea water is called ocean currents. Gulf Stream is a warm current, Labrador is a cold current.",
      explanationMr: "समुद्राच्या पाण्याची नियमित क्षैतिज हालचाल म्हणजे समुद्री प्रवाह. गल्फ स्ट्रीम हा उष्ण प्रवाह, लॅब्राडोर हा थंड प्रवाह आहे.",
      options: [
        { label: "A", textEn: "Tides", textMr: "भरती-ओहोटी", isCorrect: false },
        { label: "B", textEn: "Ocean currents", textMr: "समुद्री प्रवाह", isCorrect: true },
        { label: "C", textEn: "Waves", textMr: "लाटा", isCorrect: false },
        { label: "D", textEn: "Tsunami", textMr: "सुनामी", isCorrect: false },
      ],
    },
    {
      textEn: "Tides are caused by?",
      textMr: "भरती-ओहोटी कशामुळे होते?",
      explanationEn: "Tides are primarily caused by the gravitational pull of the moon and partly the sun. High tides occur on full moon and new moon days.",
      explanationMr: "भरती-ओहोटी मुख्यतः चंद्राच्या व काही प्रमाणात सूर्याच्या गुरुत्वाकर्षणामुळे होते. पौर्णिमा व अमावास्येला मोठी भरती येते.",
      options: [
        { label: "A", textEn: "Sun's rays", textMr: "सूर्याचे किरण", isCorrect: false },
        { label: "B", textEn: "Due to wind", textMr: "वाऱ्यामुळे", isCorrect: false },
        { label: "C", textEn: "Due to gravitational pull of moon and sun", textMr: "चंद्र व सूर्याच्या गुरुत्वाकर्षणामुळे", isCorrect: true },
        { label: "D", textEn: "Due to ocean currents", textMr: "समुद्री प्रवाहांमुळे", isCorrect: false },
      ],
    },
    {
      textEn: "Tsunami is caused by?",
      textMr: "सुनामी कशामुळे निर्माण होते?",
      explanationEn: "Tsunami is caused by underwater earthquakes, volcanoes, or landslides. The 2004 Indian Ocean tsunami was the most devastating.",
      explanationMr: "सुनामी समुद्रातील भूकंप, ज्वालामुखी किंवा भूस्खलनामुळे निर्माण होते. २००४ च्या हिंद महासागरातील सुनामी सर्वात विनाशकारी होती.",
      options: [
        { label: "A", textEn: "Storm winds", textMr: "वादळी वारे", isCorrect: false },
        { label: "B", textEn: "Underwater earthquake or volcano", textMr: "समुद्रातील भूकंप किंवा ज्वालामुखी", isCorrect: true },
        { label: "C", textEn: "Moon's gravity", textMr: "चंद्राचे गुरुत्वाकर्षण", isCorrect: false },
        { label: "D", textEn: "Ocean currents", textMr: "समुद्री प्रवाह", isCorrect: false },
      ],
    },
    {
      textEn: "The International Date Line (IDL) is located at which longitude?",
      textMr: "आंतरराष्ट्रीय तारीख रेषा (IDL) कोणत्या रेखांशावर असते?",
      explanationEn: "The International Date Line is located at 180° longitude in the Pacific Ocean. Crossing this line changes the date.",
      explanationMr: "आंतरराष्ट्रीय तारीख रेषा १८०° रेखांशावर प्रशांत महासागरात आहे. ही रेषा ओलांडताना तारखेत बदल होतो.",
      options: [
        { label: "A", textEn: "0°", textMr: "०°", isCorrect: false },
        { label: "B", textEn: "90° East", textMr: "९०° पूर्व", isCorrect: false },
        { label: "C", textEn: "180°", textMr: "१८०°", isCorrect: true },
        { label: "D", textEn: "90° West", textMr: "९०° पश्चिम", isCorrect: false },
      ],
    },
    {
      textEn: "Where is the Prime Meridian located?",
      textMr: "मूळ रेखांश (Prime Meridian) कोठे आहे?",
      explanationEn: "The Prime Meridian (0°) passes through Greenwich Observatory in London and is the reference for measuring time.",
      explanationMr: "मूळ रेखांश (0°) लंडनमधील ग्रीनविच वेधशाळेतून जातो आणि वेळाचे मापन याच रेषेवरून होते.",
      options: [
        { label: "A", textEn: "New York", textMr: "न्यूयॉर्क", isCorrect: false },
        { label: "B", textEn: "Greenwich, London", textMr: "ग्रीनविच, लंडन", isCorrect: true },
        { label: "C", textEn: "Paris", textMr: "पॅरिस", isCorrect: false },
        { label: "D", textEn: "Moscow", textMr: "मॉस्को", isCorrect: false },
      ],
    },
    {
      textEn: "Indian Standard Time (IST) is based on which longitude?",
      textMr: "भारताचा प्रमाण वेळ (IST) कोणत्या रेखांशावर आधारित आहे?",
      explanationEn: "Indian Standard Time (IST) is based on 82.5° East longitude. It is 5 hours 30 minutes ahead of Greenwich Mean Time (GMT).",
      explanationMr: "भारताचा प्रमाण वेळ (IST) ८२.५° पूर्व रेखांशावर आधारित आहे. हा ग्रीनविचपेक्षा ५ तास ३० मिनिटे पुढे आहे.",
      options: [
        { label: "A", textEn: "75° East", textMr: "७५° पूर्व", isCorrect: false },
        { label: "B", textEn: "80° East", textMr: "८०° पूर्व", isCorrect: false },
        { label: "C", textEn: "82.5° East", textMr: "८२.५° पूर्व", isCorrect: true },
        { label: "D", textEn: "90° East", textMr: "९०° पूर्व", isCorrect: false },
      ],
    },
    {
      textEn: "When crossing IDL from west to east, what happens to the date?",
      textMr: "आंतरराष्ट्रीय तारीख रेषा पश्चिमेकडून पूर्वेकडे ओलांडल्यास तारखेत काय बदल होतो?",
      explanationEn: "When crossing the IDL from west to east (Asia to America direction), the date goes back by one day.",
      explanationMr: "आंतरराष्ट्रीय तारीख रेषा पश्चिमेकडून पूर्वेकडे (एशिया ते अमेरिका दिशेने) ओलांडताना एक दिवस मागे जातो.",
      options: [
        { label: "A", textEn: "Date advances by one day", textMr: "एक दिवस पुढे जातो", isCorrect: false },
        { label: "B", textEn: "Date goes back by one day", textMr: "एक दिवस मागे जातो", isCorrect: true },
        { label: "C", textEn: "Date advances by two days", textMr: "दोन दिवस पुढे जातात", isCorrect: false },
        { label: "D", textEn: "No change in date", textMr: "तारखेत बदल होत नाही", isCorrect: false },
      ],
    },
    {
      textEn: "Who is considered the father of economics?",
      textMr: "अर्थशास्त्राचे जनक कोणाला मानले जाते?",
      explanationEn: "Adam Smith is considered the father of economics. He wrote 'The Wealth of Nations' (1776).",
      explanationMr: "अॅडम स्मिथ यांना अर्थशास्त्राचे जनक मानले जाते. त्यांनी 'The Wealth of Nations' (१७७६) हे महत्त्वाचे पुस्तक लिहिले.",
      options: [
        { label: "A", textEn: "Karl Marx", textMr: "कार्ल मार्क्स", isCorrect: false },
        { label: "B", textEn: "Adam Smith", textMr: "अॅडम स्मिथ", isCorrect: true },
        { label: "C", textEn: "John Keynes", textMr: "जॉन केन्स", isCorrect: false },
        { label: "D", textEn: "David Ricardo", textMr: "डेव्हिड रिकार्डो", isCorrect: false },
      ],
    },
    {
      textEn: "What does GDP stand for?",
      textMr: "GDP म्हणजे काय?",
      explanationEn: "GDP stands for Gross Domestic Product — the total value of all goods and services produced in a country in one year.",
      explanationMr: "GDP म्हणजे Gross Domestic Product - एका वर्षात देशात उत्पादित सर्व वस्तू व सेवांचे एकूण मूल्य.",
      options: [
        { label: "A", textEn: "Gross Domestic Product", textMr: "Gross Domestic Product", isCorrect: true },
        { label: "B", textEn: "General Development Plan", textMr: "General Development Plan", isCorrect: false },
        { label: "C", textEn: "Geographic Distribution of People", textMr: "Geographic Distribution of People", isCorrect: false },
        { label: "D", textEn: "Government Development Policy", textMr: "Government Development Policy", isCorrect: false },
      ],
    },
    {
      textEn: "Which activity is included in the primary sector?",
      textMr: "प्राथमिक उद्योगात कोणते काम येते?",
      explanationEn: "Primary sector includes agriculture, fishing, mining, and forestry — activities based on natural resources.",
      explanationMr: "प्राथमिक क्षेत्रात शेती, मासेमारी, खाणकाम, वनोत्पादन या नैसर्गिक स्रोतांवर आधारित क्रिया येतात.",
      options: [
        { label: "A", textEn: "Factory production", textMr: "कारखाना उत्पादन", isCorrect: false },
        { label: "B", textEn: "Agriculture", textMr: "शेती", isCorrect: true },
        { label: "C", textEn: "Banking", textMr: "बँकिंग", isCorrect: false },
        { label: "D", textEn: "Transport", textMr: "वाहतूक", isCorrect: false },
      ],
    },
    {
      textEn: "What is meant by imports?",
      textMr: "आयात म्हणजे काय?",
      explanationEn: "Import means bringing goods from other countries. Export means sending goods abroad. India imports crude oil in large quantities.",
      explanationMr: "आयात म्हणजे परदेशातून माल आणणे. निर्यात म्हणजे परदेशात माल पाठवणे. भारत कच्चे तेल मोठ्या प्रमाणावर आयात करतो.",
      options: [
        { label: "A", textEn: "Sending goods to other countries", textMr: "परदेशात माल पाठवणे", isCorrect: false },
        { label: "B", textEn: "Bringing goods from other countries", textMr: "परदेशातून माल आणणे", isCorrect: true },
        { label: "C", textEn: "Selling goods within the country", textMr: "देशांतर्गत माल विकणे", isCorrect: false },
        { label: "D", textEn: "Storing goods", textMr: "माल साठवणे", isCorrect: false },
      ],
    },
    {
      textEn: "What is a trade deficit?",
      textMr: "व्यापारी तूट (Trade Deficit) म्हणजे काय?",
      explanationEn: "When imports exceed exports, a trade deficit occurs. India generally faces a trade deficit.",
      explanationMr: "जेव्हा आयात निर्यातीपेक्षा जास्त असते तेव्हा व्यापारी तूट निर्माण होते. भारतास साधारणतः व्यापारी तुटीचा सामना करावा लागतो.",
      options: [
        { label: "A", textEn: "Exports > Imports", textMr: "निर्यात > आयात", isCorrect: false },
        { label: "B", textEn: "Imports > Exports", textMr: "आयात > निर्यात", isCorrect: true },
        { label: "C", textEn: "Imports = Exports", textMr: "आयात = निर्यात", isCorrect: false },
        { label: "D", textEn: "Less tax collection", textMr: "कर संकलन कमी असणे", isCorrect: false },
      ],
    },
    {
      textEn: "Where is the headquarters of the World Trade Organization (WTO)?",
      textMr: "जागतिक व्यापार संघटनेचे (WTO) मुख्यालय कोठे आहे?",
      explanationEn: "The World Trade Organization (WTO) headquarters is in Geneva, Switzerland. WTO regulates international trade.",
      explanationMr: "जागतिक व्यापार संघटना (WTO) चे मुख्यालय जिनिव्हा, स्वित्झर्लंड येथे आहे. WTO आंतरराष्ट्रीय व्यापाराचे नियमन करते.",
      options: [
        { label: "A", textEn: "New York", textMr: "न्यूयॉर्क", isCorrect: false },
        { label: "B", textEn: "Geneva", textMr: "जिनिव्हा", isCorrect: true },
        { label: "C", textEn: "London", textMr: "लंडन", isCorrect: false },
        { label: "D", textEn: "Paris", textMr: "पॅरिस", isCorrect: false },
      ],
    },
    {
      textEn: "What is urbanisation?",
      textMr: "नागरीकरण म्हणजे काय?",
      explanationEn: "Urbanisation is the increase in the number of cities and the proportion of population living in urban areas, driven by industrial growth.",
      explanationMr: "नागरीकरण म्हणजे शहरांची संख्या व शहरात राहणाऱ्या लोकसंख्येचे प्रमाण वाढणे. उद्योगाच्या वाढीमुळे नागरीकरण होते.",
      options: [
        { label: "A", textEn: "Increase in number of villages", textMr: "गावांची संख्या वाढणे", isCorrect: false },
        { label: "B", textEn: "Increase in cities and urban population", textMr: "शहरांची संख्या व शहरी लोकसंख्या वाढणे", isCorrect: true },
        { label: "C", textEn: "Increase in agricultural land", textMr: "शेतजमिनीचे क्षेत्रफळ वाढणे", isCorrect: false },
        { label: "D", textEn: "Increase in forests", textMr: "जंगले वाढणे", isCorrect: false },
      ],
    },
    {
      textEn: "What is the largest metropolitan city in India?",
      textMr: "भारतातील सर्वात मोठे महानगर कोणते आहे?",
      explanationEn: "Mumbai is the largest metropolitan city in India and its financial capital. Delhi is the political capital.",
      explanationMr: "मुंबई हे भारतातील सर्वात मोठे महानगर असून ती देशाची आर्थिक राजधानी आहे. दिल्ली ही राजकीय राजधानी आहे.",
      options: [
        { label: "A", textEn: "Delhi", textMr: "दिल्ली", isCorrect: false },
        { label: "B", textEn: "Mumbai", textMr: "मुंबई", isCorrect: true },
        { label: "C", textEn: "Kolkata", textMr: "कोलकाता", isCorrect: false },
        { label: "D", textEn: "Chennai", textMr: "चेन्नई", isCorrect: false },
      ],
    },
    {
      textEn: "What are slums?",
      textMr: "झोपडपट्टी म्हणजे काय?",
      explanationEn: "Slums are overcrowded, poor, informal urban settlements with inadequate facilities. Dharavi (Mumbai) is one of Asia's largest slums.",
      explanationMr: "झोपडपट्टी म्हणजे शहरात अतिगर्दी, गरिबी व अपुऱ्या सोयींसह असलेल्या अनधिकृत वसाहती. धारावी (मुंबई) आशियातील मोठ्या झोपडपट्ट्यांपैकी एक आहे.",
      options: [
        { label: "A", textEn: "High-class residential area", textMr: "उच्चभ्रू निवासी क्षेत्र", isCorrect: false },
        { label: "B", textEn: "Overcrowded, poor, informal urban settlement", textMr: "अतिगर्दी, गरिबी असलेले अनधिकृत शहरी वसाहत", isCorrect: true },
        { label: "C", textEn: "Industrial area", textMr: "औद्योगिक क्षेत्र", isCorrect: false },
        { label: "D", textEn: "Commercial area", textMr: "व्यापारी क्षेत्र", isCorrect: false },
      ],
    },
    {
      textEn: "India's railway network ranks at which position in the world?",
      textMr: "भारतातील रेल्वे जाळे जगात कितव्या क्रमांकावर आहे?",
      explanationEn: "India's railway network is the fourth largest in the world. It is also the largest railway network in Asia.",
      explanationMr: "भारतीय रेल्वे जाळे जगात चौथ्या क्रमांकावर आहे. भारतीय रेल्वे आशियातील सर्वात मोठे रेल्वे जाळे आहे.",
      options: [
        { label: "A", textEn: "First", textMr: "पहिल्या", isCorrect: false },
        { label: "B", textEn: "Second", textMr: "दुसऱ्या", isCorrect: false },
        { label: "C", textEn: "Fourth", textMr: "चौथ्या", isCorrect: true },
        { label: "D", textEn: "Sixth", textMr: "सहाव्या", isCorrect: false },
      ],
    },
    {
      textEn: "Which is the cheapest mode of transport in India?",
      textMr: "भारतात सर्वाधिक स्वस्त वाहतुकीचे साधन कोणते आहे?",
      explanationEn: "Water transport (sea and river) is the cheapest mode of transport as it uses less fuel per ton of goods.",
      explanationMr: "जलवाहतूक (समुद्री व नदी) हे सर्वात स्वस्त वाहतुकीचे साधन आहे कारण इंधनाचा वापर कमी होतो.",
      options: [
        { label: "A", textEn: "Air transport", textMr: "हवाई वाहतूक", isCorrect: false },
        { label: "B", textEn: "Road transport", textMr: "रस्ते वाहतूक", isCorrect: false },
        { label: "C", textEn: "Water transport", textMr: "जलवाहतूक", isCorrect: true },
        { label: "D", textEn: "Railway", textMr: "रेल्वे", isCorrect: false },
      ],
    },
    {
      textEn: "In which decade was the internet invented?",
      textMr: "इंटरनेटचा शोध कोणत्या दशकात लागला?",
      explanationEn: "Internet originated as ARPANET (Advanced Research Projects Agency Network) in 1969 in the USA.",
      explanationMr: "इंटरनेटची सुरुवात ARPANET (Advanced Research Projects Agency Network) म्हणून १९६९ मध्ये अमेरिकेत झाली.",
      options: [
        { label: "A", textEn: "In the 1950s", textMr: "१९५०च्या दशकात", isCorrect: false },
        { label: "B", textEn: "In the 1960s-70s", textMr: "१९६०-७०च्या दशकात", isCorrect: true },
        { label: "C", textEn: "In the 1990s", textMr: "१९९०च्या दशकात", isCorrect: false },
        { label: "D", textEn: "In the 2000s", textMr: "२०००च्या दशकात", isCorrect: false },
      ],
    },
    {
      textEn: "Nagpur is considered which capital of India?",
      textMr: "नागपूर ही भारताची कोणती राजधानी मानली जाते?",
      explanationEn: "Nagpur is called the Zero Mile City of India as it is the geographical centre where major national highways converge.",
      explanationMr: "नागपूर हे भारताचे भौगोलिक केंद्र (Zero Mile City) मानले जाते कारण येथे राष्ट्रीय महामार्गांचे केंद्र आहे.",
      options: [
        { label: "A", textEn: "Political capital", textMr: "राजकीय राजधानी", isCorrect: false },
        { label: "B", textEn: "Economic capital", textMr: "आर्थिक राजधानी", isCorrect: false },
        { label: "C", textEn: "Zero Mile city (geographical centre)", textMr: "भौगोलिक केंद्र/शून्य मैल नगर", isCorrect: true },
        { label: "D", textEn: "Cultural capital", textMr: "सांस्कृतिक राजधानी", isCorrect: false },
      ],
    },
    {
      textEn: "Which state in India attracts the most tourists?",
      textMr: "भारतातील सर्वाधिक पर्यटक आकर्षित करणारे राज्य कोणते आहे?",
      explanationEn: "Uttar Pradesh (Agra-Taj Mahal) is the most visited state by foreign tourists. Maharashtra is also a leading tourist destination.",
      explanationMr: "उत्तर प्रदेश (आग्रा-ताजमहाल) हे परदेशी पर्यटकांसाठी सर्वाधिक भेट देण्याचे राज्य आहे. महाराष्ट्रही पर्यटनात अग्रेसर आहे.",
      options: [
        { label: "A", textEn: "Goa", textMr: "गोवा", isCorrect: false },
        { label: "B", textEn: "Rajasthan", textMr: "राजस्थान", isCorrect: false },
        { label: "C", textEn: "Kerala", textMr: "केरळ", isCorrect: false },
        { label: "D", textEn: "Uttar Pradesh", textMr: "उत्तर प्रदेश", isCorrect: true },
      ],
    },
    {
      textEn: "What is ecotourism?",
      textMr: "इको-टुरिझम (Ecotourism) म्हणजे काय?",
      explanationEn: "Ecotourism is responsible travel to natural and wildlife areas without harming the environment. It protects local culture and ecology.",
      explanationMr: "इको-टुरिझम म्हणजे पर्यावरणाला हानी न करता नैसर्गिक व वन्यजीव क्षेत्रांना जबाबदारीने भेट देणे. ते स्थानिक संस्कृती व पर्यावरणाचे संरक्षण करते.",
      options: [
        { label: "A", textEn: "Visiting cities", textMr: "शहरांना भेट देणे", isCorrect: false },
        { label: "B", textEn: "Visiting natural areas without harming the environment", textMr: "पर्यावरणाला हानी न करता नैसर्गिक ठिकाणांना भेट देणे", isCorrect: true },
        { label: "C", textEn: "Visiting historical monuments", textMr: "ऐतिहासिक वास्तूंना भेट देणे", isCorrect: false },
        { label: "D", textEn: "Tourism abroad", textMr: "परदेशात पर्यटन", isCorrect: false },
      ],
    },
    {
      textEn: "Which state in India has the most UNESCO World Heritage Sites?",
      textMr: "भारतातील सर्वाधिक UNESCO जागतिक वारसा स्थळे कोणत्या राज्यात आहेत?",
      explanationEn: "Maharashtra has multiple UNESCO World Heritage Sites including Ajanta, Ellora, Elephanta, CST Mumbai, and Victorian Gothic architecture.",
      explanationMr: "महाराष्ट्रात अजंठा, एलोरा, एलिफंटा, छत्रपती शिवाजी टर्मिनस, मुंबईचे विक्टोरियन-गोथिक स्थापत्य यासह अनेक UNESCO जागतिक वारसा स्थळे आहेत.",
      options: [
        { label: "A", textEn: "Delhi", textMr: "दिल्ली", isCorrect: false },
        { label: "B", textEn: "Maharashtra", textMr: "महाराष्ट्र", isCorrect: true },
        { label: "C", textEn: "Uttar Pradesh", textMr: "उत्तर प्रदेश", isCorrect: false },
        { label: "D", textEn: "Rajasthan", textMr: "राजस्थान", isCorrect: false },
      ],
    },
    {
      textEn: "What is Kerala called in the context of tourism?",
      textMr: "भारतातील केरळला कोणती उपमा दिली जाते?",
      explanationEn: "Kerala is known as 'God's Own Country'. Its backwaters, ayurveda tourism, and natural beauty attract tourists worldwide.",
      explanationMr: "केरळला 'God's Own Country' (ईश्वराचे स्वतःचे देश) म्हणून ओळखले जाते. येथील बॅकवॉटर, आयुर्वेद पर्यटन जगप्रसिद्ध आहे.",
      options: [
        { label: "A", textEn: "Golden State", textMr: "सोनेरी राज्य", isCorrect: false },
        { label: "B", textEn: "Gift of Arabian Sea", textMr: "अरबी सागराचे वरदान", isCorrect: false },
        { label: "C", textEn: "God's own country", textMr: "भगवानाचे स्वतःचे देश", isCorrect: true },
        { label: "D", textEn: "Green State", textMr: "हरित राज्य", isCorrect: false },
      ],
    },
  ],
};

export default data;
