import type { QuestionSetInput } from "./types";

// Source: All questions & answer/AMVI_Std9_Sci_English.pdf + AMVI_Std9_Sci_Marathi.pdf
// Both PDFs share identical question numbering/options/answers (61 MCQs).
// The Science English PDF frequently mixed Devanagari words, symbols with dropped
// subscripts (e.g. "R■" for "R₁"), and "मराठी (English gloss)" combined cells into its
// option text; these were cleaned into separate, standard-notation textEn/textMr fields
// using the Marathi PDF and standard chemistry/physics notation as reference. This did
// not change the meaning or the marked correct answers.
const data: QuestionSetInput = {
  standard: { code: "STD9", nameEn: "Standard 9", nameMr: "इयत्ता ९वी", sortOrder: 9 },
  subject: { code: "SCI", nameEn: "Science", nameMr: "विज्ञान", sortOrder: 3 },
  questions: [
    {
      textEn: "According to Newton's first law, what does an object do if no external force acts on it?",
      textMr: "न्यूटनच्या पहिल्या नियमानुसार, जर कोणतीही बाह्य शक्ती नसेल तर वस्तू काय करते?",
      explanationEn: "Newton's first law states that without an external force, no object changes its state of rest or uniform motion. This is called the law of inertia.",
      explanationMr: "न्यूटनचा पहिला नियम सांगतो की बाह्य शक्तीशिवाय कोणतीही वस्तू आपली गती किंवा स्थिती बदलत नाही. यालाच जडत्वाचा नियम म्हणतात.",
      options: [
        { label: "A", textEn: "Changes its motion", textMr: "गती बदलते", isCorrect: false },
        { label: "B", textEn: "Remains at rest or uniform motion", textMr: "स्थिर राहते किंवा एकसमान गतीत राहते", isCorrect: true },
        { label: "C", textEn: "Stops", textMr: "थांबते", isCorrect: false },
        { label: "D", textEn: "Moves upward", textMr: "वर जाते", isCorrect: false },
      ],
    },
    {
      textEn: "What is the formula for Newton's second law?",
      textMr: "न्यूटनच्या दुसऱ्या नियमाचे सूत्र कोणते?",
      explanationEn: "Newton's second law states: Force = mass × acceleration (F = ma). Force equals the product of mass and acceleration.",
      explanationMr: "न्यूटनचा दुसरा नियम सांगतो: बल = वस्तुमान × त्वरण (F = ma). बल हे वस्तुमान आणि त्वरणाच्या गुणाकाराएवढे असते.",
      options: [
        { label: "A", textEn: "F = m/a", textMr: "F = m/a", isCorrect: false },
        { label: "B", textEn: "F = ma", textMr: "F = ma", isCorrect: true },
        { label: "C", textEn: "F = a/m", textMr: "F = a/m", isCorrect: false },
        { label: "D", textEn: "F = m + a", textMr: "F = m + a", isCorrect: false },
      ],
    },
    {
      textEn: "According to Newton's third law, every action has an equal and opposite _____.",
      textMr: "न्यूटनच्या तिसऱ्या नियमानुसार प्रत्येक क्रियेला सम व विरुद्ध _____ असते.",
      explanationEn: "Newton's third law: Every action has an equal and opposite reaction. E.g. rocket propulsion, recoil of a gun.",
      explanationMr: "न्यूटनचा तिसरा नियम: प्रत्येक क्रियेला सम आणि विरुद्ध प्रतिक्रिया असते. उदा. रॉकेट प्रणोदन, बंदुकीची मागे जाण्याची क्रिया.",
      options: [
        { label: "A", textEn: "Force", textMr: "बल", isCorrect: false },
        { label: "B", textEn: "Reaction", textMr: "प्रतिक्रिया", isCorrect: true },
        { label: "C", textEn: "Acceleration", textMr: "त्वरण", isCorrect: false },
        { label: "D", textEn: "Velocity", textMr: "वेग", isCorrect: false },
      ],
    },
    {
      textEn: "What is the measure of inertia of an object?",
      textMr: "वस्तूच्या जडत्वाचे मोजमाप कशाने केले जाते?",
      explanationEn: "The mass of an object is the measure of its inertia. An object with greater mass has greater inertia.",
      explanationMr: "वस्तूचे वस्तुमान हे त्याच्या जडत्वाचे मोजमाप आहे. जास्त वस्तुमान असलेल्या वस्तूत जास्त जडत्व असते.",
      options: [
        { label: "A", textEn: "Force", textMr: "बल", isCorrect: false },
        { label: "B", textEn: "Velocity", textMr: "वेग", isCorrect: false },
        { label: "C", textEn: "Mass", textMr: "वस्तुमान", isCorrect: true },
        { label: "D", textEn: "Density", textMr: "घनता", isCorrect: false },
      ],
    },
    {
      textEn: "Momentum = ?",
      textMr: "संवेग (momentum) = ?",
      explanationEn: "Momentum = mass × velocity (p = mv). Momentum is a vector quantity; its SI unit is kg·m/s.",
      explanationMr: "संवेग = वस्तुमान × वेग (p = mv). संवेग हे सदिश राशी आहे आणि SI एकक kg·m/s आहे.",
      options: [
        { label: "A", textEn: "Velocity (v)", textMr: "वेग", isCorrect: false },
        { label: "B", textEn: "Mass × velocity (mv)", textMr: "वस्तुमान × वेग (mv)", isCorrect: true },
        { label: "C", textEn: "Force × time (Ft)", textMr: "बल × वेळ (Ft)", isCorrect: false },
        { label: "D", textEn: "Mass (m)", textMr: "वस्तुमान", isCorrect: false },
      ],
    },
    {
      textEn: "Work = ?",
      textMr: "कार्य (Work) = ?",
      explanationEn: "Work = Force × Displacement in the direction of force (W = F × d). SI unit of work is Joule (J).",
      explanationMr: "कार्य = बल × बलाच्या दिशेत विस्थापन (W = F × d). कार्याचे SI एकक जूल (J) आहे.",
      options: [
        { label: "A", textEn: "Displacement", textMr: "विस्थापन", isCorrect: false },
        { label: "B", textEn: "Force × Displacement", textMr: "बल × विस्थापन", isCorrect: true },
        { label: "C", textEn: "Mass × Velocity", textMr: "वस्तुमान × वेग", isCorrect: false },
        { label: "D", textEn: "Force + Displacement", textMr: "बल + विस्थापन", isCorrect: false },
      ],
    },
    {
      textEn: "What is the formula for kinetic energy?",
      textMr: "गतिज ऊर्जेचे सूत्र कोणते?",
      explanationEn: "Kinetic energy = ½ × mass × velocity² (KE = ½mv²). A moving object possesses this energy.",
      explanationMr: "गतिज ऊर्जा = ½ × वस्तुमान × वेगाचा वर्ग (KE = ½mv²). गतिमान वस्तूकडे ही ऊर्जा असते.",
      options: [
        { label: "A", textEn: "KE = mgh", textMr: "KE = mgh", isCorrect: false },
        { label: "B", textEn: "KE = ½mv²", textMr: "KE = ½mv²", isCorrect: true },
        { label: "C", textEn: "KE = mv", textMr: "KE = mv", isCorrect: false },
        { label: "D", textEn: "KE = Fd", textMr: "KE = Fd", isCorrect: false },
      ],
    },
    {
      textEn: "What is the formula for potential energy?",
      textMr: "स्थितिज ऊर्जेचे सूत्र कोणते?",
      explanationEn: "Gravitational potential energy = mass × gravitational acceleration × height (PE = mgh). A raised object possesses this energy.",
      explanationMr: "गुरुत्वीय स्थितिज ऊर्जा = वस्तुमान × गुरुत्वीय प्रवेग × उंची (PE = mgh). उंचावलेल्या वस्तूकडे ही ऊर्जा असते.",
      options: [
        { label: "A", textEn: "PE = ½mv²", textMr: "PE = ½mv²", isCorrect: false },
        { label: "B", textEn: "PE = mgh", textMr: "PE = mgh", isCorrect: true },
        { label: "C", textEn: "PE = mv²", textMr: "PE = mv²", isCorrect: false },
        { label: "D", textEn: "PE = F/d", textMr: "PE = F/d", isCorrect: false },
      ],
    },
    {
      textEn: "Energy can be converted but cannot be _____ or _____.",
      textMr: "ऊर्जेचे रूपांतर करता येते पण ती _____ किंवा _____ करता येत नाही.",
      explanationEn: "The law of conservation of energy states: Energy can neither be created nor destroyed, only converted. Total energy remains constant.",
      explanationMr: "ऊर्जा संवर्धनाचा नियम सांगतो: ऊर्जा निर्माण किंवा नष्ट करता येत नाही, फक्त रूपांतरित करता येते. एकूण ऊर्जा स्थिर राहते.",
      options: [
        { label: "A", textEn: "Stored or used", textMr: "साठवता किंवा वापरता", isCorrect: false },
        { label: "B", textEn: "Created or destroyed", textMr: "निर्माण किंवा नष्ट", isCorrect: true },
        { label: "C", textEn: "Measured or felt", textMr: "मोजता किंवा अनुभवता", isCorrect: false },
        { label: "D", textEn: "Changed or transferred", textMr: "बदलता किंवा वाहवता", isCorrect: false },
      ],
    },
    {
      textEn: "Power = ?",
      textMr: "शक्ती (Power) = ?",
      explanationEn: "Power = Work / Time (P = W/t). SI unit of power is Watt (W). 1 Watt = 1 Joule/second.",
      explanationMr: "शक्ती = कार्य / वेळ (P = W/t). शक्तीचे SI एकक वॅट (W) आहे. 1 वॅट = 1 जूल/सेकंद.",
      options: [
        { label: "A", textEn: "Time", textMr: "वेळ", isCorrect: false },
        { label: "B", textEn: "Work / Time", textMr: "कार्य / वेळ", isCorrect: true },
        { label: "C", textEn: "Energy × Time", textMr: "ऊर्जा × वेळ", isCorrect: false },
        { label: "D", textEn: "Force × velocity²", textMr: "बल × वेग²", isCorrect: false },
      ],
    },
    {
      textEn: "According to Ohm's law, V = ?",
      textMr: "ओमच्या नियमानुसार V = ?",
      explanationEn: "Ohm's Law: V = IR, where V = voltage (Volts), I = current (Amperes), R = resistance (Ohms). This law applies to metallic conductors.",
      explanationMr: "ओमचा नियम: V = IR, जेथे V = विद्युत दाब (व्होल्ट), I = विद्युतधारा (अँपिअर), R = रोध (ओम). हा नियम धातूंना लागू होतो.",
      options: [
        { label: "A", textEn: "I/R", textMr: "I/R", isCorrect: false },
        { label: "B", textEn: "IR", textMr: "IR", isCorrect: true },
        { label: "C", textEn: "I+R", textMr: "I+R", isCorrect: false },
        { label: "D", textEn: "I²R", textMr: "I²R", isCorrect: false },
      ],
    },
    {
      textEn: "What is the SI unit of electric current?",
      textMr: "विद्युतधारेचे SI एकक कोणते?",
      explanationEn: "The SI unit of electric current is Ampere (A). Current is the amount of charge flowing per unit time (I = Q/t).",
      explanationMr: "विद्युतधारेचे SI एकक अँपिअर (A) आहे. विद्युतधारा म्हणजे एकक वेळात वाहणाऱ्या आवेशाचे प्रमाण (I = Q/t).",
      options: [
        { label: "A", textEn: "Volt", textMr: "व्होल्ट", isCorrect: false },
        { label: "B", textEn: "Ampere", textMr: "अँपिअर", isCorrect: true },
        { label: "C", textEn: "Ohm", textMr: "ओम", isCorrect: false },
        { label: "D", textEn: "Watt", textMr: "वॅट", isCorrect: false },
      ],
    },
    {
      textEn: "In series combination, total resistance R = ?",
      textMr: "मालिका जोडणीत एकूण रोध (R) = ?",
      explanationEn: "In series connection, total resistance = R₁ + R₂ + R₃ + ... . In parallel connection: 1/R = 1/R₁ + 1/R₂ + ...",
      explanationMr: "मालिका जोडणीत (series connection) एकूण रोध = R₁ + R₂ + R₃ + ... . समांतर जोडणीत (parallel) 1/R = 1/R₁ + 1/R₂ + ...",
      options: [
        { label: "A", textEn: "R₁ × R₂", textMr: "R₁ × R₂", isCorrect: false },
        { label: "B", textEn: "R₁ + R₂", textMr: "R₁ + R₂", isCorrect: true },
        { label: "C", textEn: "1/R₁ + 1/R₂", textMr: "1/R₁ + 1/R₂", isCorrect: false },
        { label: "D", textEn: "R₁", textMr: "R₁", isCorrect: false },
      ],
    },
    {
      textEn: "Electrical energy = ?",
      textMr: "विद्युत ऊर्जा = ?",
      explanationEn: "Electrical energy = V × I × t (W = VIt = I²Rt). SI unit is Joule (J). In practice, kWh (kilowatt-hour) is used.",
      explanationMr: "विद्युत ऊर्जा = V × I × t (W = VIt = I²Rt). विद्युत ऊर्जेचे SI एकक जूल (J) आहे. व्यवहारात kWh वापरतात.",
      options: [
        { label: "A", textEn: "V × I", textMr: "V × I", isCorrect: false },
        { label: "B", textEn: "V × I × t", textMr: "V × I × t", isCorrect: true },
        { label: "C", textEn: "V × R", textMr: "V × R", isCorrect: false },
        { label: "D", textEn: "I²", textMr: "I²", isCorrect: false },
      ],
    },
    {
      textEn: "What is atomic mass unit (amu)?",
      textMr: "अणुवस्तुमान एकक (amu) म्हणजे काय?",
      explanationEn: "1 atomic mass unit (amu) = 1/12th the mass of a carbon-12 atom. It is a very small unit (1.66 × 10⁻²⁷ kg).",
      explanationMr: "1 अणुवस्तुमान एकक (amu) = कार्बन-12 अणूच्या वस्तुमानाच्या 1/12 भाग. हे खूप लहान एकक आहे (1.66 × 10⁻²⁷ kg).",
      options: [
        { label: "A", textEn: "1/12 of hydrogen atom mass", textMr: "हायड्रोजन अणूच्या वस्तुमानाच्या 1/12", isCorrect: false },
        { label: "B", textEn: "1/12 of carbon-12 atom mass", textMr: "कार्बन-12 अणूच्या वस्तुमानाच्या 1/12", isCorrect: true },
        { label: "C", textEn: "Mass of oxygen atom", textMr: "ऑक्सिजन अणूचे वस्तुमान", isCorrect: false },
        { label: "D", textEn: "1 gram", textMr: "1 ग्रॅम", isCorrect: false },
      ],
    },
    {
      textEn: "What is a mole?",
      textMr: "मोल (mole) म्हणजे काय?",
      explanationEn: "1 mole = 6.022 × 10²³ particles (atoms, molecules, or ions). This is Avogadro's number.",
      explanationMr: "1 मोल = 6.022 × 10²³ कण (अणू, रेणू किंवा आयन). हे आवोगाड्रोचे संख्या (Avogadro's number) आहे.",
      options: [
        { label: "A", textEn: "10²³ particles", textMr: "10²³ कण", isCorrect: false },
        { label: "B", textEn: "6.022 × 10²³ particles (Avogadro's number)", textMr: "6.022 × 10²³ कण (आवोगाड्रो संख्या)", isCorrect: true },
        { label: "C", textEn: "1 gram of substance", textMr: "1 ग्रॅम पदार्थ", isCorrect: false },
        { label: "D", textEn: "Mass of atoms", textMr: "अणूंचे वस्तुमान", isCorrect: false },
      ],
    },
    {
      textEn: "In what unit is molar mass measured?",
      textMr: "मोलर वस्तुमान (molar mass) कशात मोजतात?",
      explanationEn: "Molar mass is measured in grams per mole (g/mol). E.g. molar mass of water (H₂O) = 18 g/mol.",
      explanationMr: "मोलर वस्तुमान ग्रॅम प्रति मोल (g/mol) मध्ये मोजतात. उदा. पाणी (H₂O) चे मोलर वस्तुमान = 18 g/mol.",
      options: [
        { label: "A", textEn: "g/mol", textMr: "ग्रॅम/मोल", isCorrect: true },
        { label: "B", textEn: "kg", textMr: "किलोग्रॅम", isCorrect: false },
        { label: "C", textEn: "amu", textMr: "amu", isCorrect: false },
        { label: "D", textEn: "Litre", textMr: "लिटर", isCorrect: false },
      ],
    },
    {
      textEn: "What is the volume of 1 mole of gas at STP?",
      textMr: "STP वर 1 मोल वायूचे आयतन किती असते?",
      explanationEn: "At STP (Standard Temperature and Pressure), 1 mole of any gas occupies 22.4 litres (22400 mL). This is called molar volume.",
      explanationMr: "STP (Standard Temperature and Pressure) वर 1 मोल कोणत्याही वायूचे आयतन 22.4 लिटर (22400 mL) असते. याला मोलर आयतन म्हणतात.",
      options: [
        { label: "A", textEn: "11.2 litres", textMr: "11.2 लिटर", isCorrect: false },
        { label: "B", textEn: "22.4 litres", textMr: "22.4 लिटर", isCorrect: true },
        { label: "C", textEn: "44.8 litres", textMr: "44.8 लिटर", isCorrect: false },
        { label: "D", textEn: "1 litre", textMr: "1 लिटर", isCorrect: false },
      ],
    },
    {
      textEn: "What is the pH value of an acid on the pH scale?",
      textMr: "pH स्केलवर आम्लाचे pH मूल्य कसे असते?",
      explanationEn: "On pH scale: acids have pH < 7, neutral substances have pH = 7, and bases have pH > 7. HCl has pH approximately 0-1.",
      explanationMr: "pH स्केलवर आम्लाचे pH < 7, तटस्थ पदार्थाचे pH = 7, आणि आम्लारीचे pH > 7 असते. HCl चे pH अंदाजे 0-1 असते.",
      options: [
        { label: "A", textEn: "Greater than 7", textMr: "7 पेक्षा जास्त", isCorrect: false },
        { label: "B", textEn: "Less than 7", textMr: "7 पेक्षा कमी", isCorrect: true },
        { label: "C", textEn: "Equal to 7", textMr: "7 बरोबर", isCorrect: false },
        { label: "D", textEn: "Equal to 14", textMr: "14 बरोबर", isCorrect: false },
      ],
    },
    {
      textEn: "What color does an acid turn litmus paper?",
      textMr: "लिटमस पेपरवर आम्लाचा रंग कोणता होतो?",
      explanationEn: "Acids turn blue litmus paper red. Bases turn red litmus paper blue. Litmus is a natural pH indicator.",
      explanationMr: "आम्ल निळ्या लिटमस पेपरला लाल करते. आम्लारी लाल लिटमस पेपरला निळा करते. लिटमस हे नैसर्गिक pH निर्देशक आहे.",
      options: [
        { label: "A", textEn: "Blue", textMr: "निळा", isCorrect: false },
        { label: "B", textEn: "Red", textMr: "लाल", isCorrect: true },
        { label: "C", textEn: "Green", textMr: "हिरवा", isCorrect: false },
        { label: "D", textEn: "Yellow", textMr: "पिवळा", isCorrect: false },
      ],
    },
    {
      textEn: "The reaction between an acid and a base is called?",
      textMr: "आम्ल आणि आम्लारी यांची अभिक्रिया म्हणजे काय?",
      explanationEn: "Acid + Base → Salt + Water. This reaction is called neutralisation. E.g. HCl + NaOH → NaCl + H₂O.",
      explanationMr: "आम्ल + आम्लारी → क्षार + पाणी. या अभिक्रियेला उदासीनीकरण (neutralisation) म्हणतात. उदा. HCl + NaOH → NaCl + H₂O.",
      options: [
        { label: "A", textEn: "Oxidation", textMr: "ऑक्सीकरण", isCorrect: false },
        { label: "B", textEn: "Neutralisation", textMr: "उदासीनीकरण", isCorrect: true },
        { label: "C", textEn: "Solidification", textMr: "घनीभवन", isCorrect: false },
        { label: "D", textEn: "Decomposition", textMr: "विघटन", isCorrect: false },
      ],
    },
    {
      textEn: "A substance that gives OH⁻ ions when dissolved in water is called?",
      textMr: "पाण्यात विरघळल्यावर OH⁻ आयन देणाऱ्या पदार्थाला काय म्हणतात?",
      explanationEn: "A base dissolves in water to give OH⁻ ions. A base soluble in water is called an alkali. E.g. NaOH → Na⁺ + OH⁻.",
      explanationMr: "आम्लारी (base) पाण्यात विरघळून OH⁻ आयन देते. पाण्यात विरघळणाऱ्या आम्लारीला अल्कली म्हणतात. उदा. NaOH → Na⁺ + OH⁻.",
      options: [
        { label: "A", textEn: "Acid", textMr: "आम्ल", isCorrect: false },
        { label: "B", textEn: "Base/Alkali", textMr: "आम्लारी/क्षार", isCorrect: true },
        { label: "C", textEn: "Salt", textMr: "क्षार", isCorrect: false },
        { label: "D", textEn: "Oxide", textMr: "ऑक्साइड", isCorrect: false },
      ],
    },
    {
      textEn: "Based on number of cotyledons, flowering plants are classified into how many types?",
      textMr: "बीजपत्रांच्या संख्येवर आधारित फुलझाडांचे किती प्रकार आहेत?",
      explanationEn: "Flowering plants (Angiosperms) are classified into two types based on cotyledons: Monocots (one cotyledon) and Dicots (two cotyledons).",
      explanationMr: "फुलझाडे (Angiosperms) बीजपत्रांच्या संख्येवर आधारित दोन प्रकारचे असतात: एकबीजपत्री (Monocots - एक बीजपत्र) आणि द्विबीजपत्री (Dicots - दोन बीजपत्रे).",
      options: [
        { label: "A", textEn: "Three", textMr: "तीन", isCorrect: false },
        { label: "B", textEn: "Two", textMr: "दोन", isCorrect: true },
        { label: "C", textEn: "Four", textMr: "चार", isCorrect: false },
        { label: "D", textEn: "Five", textMr: "पाच", isCorrect: false },
      ],
    },
    {
      textEn: "What is a characteristic of Pteridophyta?",
      textMr: "टेरिडोफायटा गटाची ओळख कोणती?",
      explanationEn: "Pteridophyta have vascular tissue but no seeds. E.g. ferns. Reproduction occurs through spores.",
      explanationMr: "टेरिडोफायटा (Pteridophyta) मध्ये संवहनी ऊतक (vascular tissue) असते पण बिया नसतात. उदा. फर्न. पुनरुत्पादन बीजाणूंद्वारे होते.",
      options: [
        { label: "A", textEn: "Have seeds", textMr: "बिया असतात", isCorrect: false },
        { label: "B", textEn: "Have vascular tissue but no seeds", textMr: "संवहनी ऊतक असते पण बिया नसतात", isCorrect: true },
        { label: "C", textEn: "Have flowers", textMr: "फुले असतात", isCorrect: false },
        { label: "D", textEn: "Live in water", textMr: "पाण्यात राहतात", isCorrect: false },
      ],
    },
    {
      textEn: "Who proposed the binomial nomenclature system?",
      textMr: "द्विनाम पद्धती कोणी मांडली?",
      explanationEn: "Binomial nomenclature was proposed by Carl Linnaeus. Each organism has a two-word scientific name — genus + species.",
      explanationMr: "द्विनाम पद्धती (binomial nomenclature) कार्ल लिनियस यांनी मांडली. प्रत्येक सजीवाला दोन शब्दांचे शास्त्रीय नाव असते - वंश (genus) + प्रजाती (species).",
      options: [
        { label: "A", textEn: "Darwin", textMr: "डार्विन", isCorrect: false },
        { label: "B", textEn: "Carl Linnaeus", textMr: "कार्ल लिनियस", isCorrect: true },
        { label: "C", textEn: "Mendel", textMr: "मेंडेल", isCorrect: false },
        { label: "D", textEn: "Pasteur", textMr: "पाश्चर", isCorrect: false },
      ],
    },
    {
      textEn: "Who are the producers in a food chain?",
      textMr: "अन्नसाखळीतील उत्पादक म्हणजे काय?",
      explanationEn: "Green plants prepare food from sunlight through photosynthesis, so they are producers in a food chain.",
      explanationMr: "हिरव्या वनस्पती प्रकाशसंश्लेषणाद्वारे सूर्यप्रकाशापासून अन्न तयार करतात, म्हणून त्या उत्पादक (producers) आहेत.",
      options: [
        { label: "A", textEn: "Animals", textMr: "प्राणी", isCorrect: false },
        { label: "B", textEn: "Green plants", textMr: "हिरव्या वनस्पती", isCorrect: true },
        { label: "C", textEn: "Fungi", textMr: "बुरशी", isCorrect: false },
        { label: "D", textEn: "Bacteria", textMr: "जीवाणू", isCorrect: false },
      ],
    },
    {
      textEn: "The ten percent law is associated with?",
      textMr: "10% नियम (ten percent law) कोणाशी संबंधित आहे?",
      explanationEn: "Lindemann's ten percent law states that only 10% of energy is transferred from one trophic level to the next in a food chain; the remaining 90% is lost.",
      explanationMr: "लिंडेमनने मांडलेल्या 10% नियमानुसार, अन्नसाखळीच्या एका पातळीवरून दुसऱ्या पातळीवर फक्त 10% ऊर्जा हस्तांतरित होते, उर्वरित 90% हरवते.",
      options: [
        { label: "A", textEn: "Mendel", textMr: "मेंडेल", isCorrect: false },
        { label: "B", textEn: "Lindemann", textMr: "लिंडेमन", isCorrect: true },
        { label: "C", textEn: "Darwin", textMr: "डार्विन", isCorrect: false },
        { label: "D", textEn: "Pasteur", textMr: "पाश्चर", isCorrect: false },
      ],
    },
    {
      textEn: "What do decomposers do?",
      textMr: "विघटक (decomposers) काय करतात?",
      explanationEn: "Decomposers (like fungi and bacteria) break down dead organisms and return nutrients to the soil. They help maintain nutrient cycling.",
      explanationMr: "विघटक (जसे बुरशी व जीवाणू) मृत सजीवांचे विघटन करतात आणि पोषक द्रव्ये पुन्हा मातीत मिसळतात. ते पोषक चक्र राखण्यास मदत करतात.",
      options: [
        { label: "A", textEn: "Produce food", textMr: "अन्न तयार करतात", isCorrect: false },
        { label: "B", textEn: "Decompose dead organisms", textMr: "मृत सजीवांचे विघटन करतात", isCorrect: true },
        { label: "C", textEn: "Hunt prey", textMr: "शिकार करतात", isCorrect: false },
        { label: "D", textEn: "Do photosynthesis", textMr: "प्रकाशसंश्लेषण करतात", isCorrect: false },
      ],
    },
    {
      textEn: "Penicillin antibiotic is obtained from?",
      textMr: "पेनिसिलिन हे प्रतिजैविक कोणापासून मिळते?",
      explanationEn: "Penicillin is obtained from Penicillium notatum fungus. Alexander Fleming discovered it in 1928.",
      explanationMr: "पेनिसिलिन हे पेनिसिलियम नोटेटम (Penicillium notatum) या बुरशीपासून मिळते. अलेक्झांडर फ्लेमिंग यांनी 1928 मध्ये हे शोधले.",
      options: [
        { label: "A", textEn: "Bacteria", textMr: "जीवाणू", isCorrect: false },
        { label: "B", textEn: "Penicillium fungus", textMr: "पेनिसिलियम बुरशी", isCorrect: true },
        { label: "C", textEn: "Virus", textMr: "विषाणू", isCorrect: false },
        { label: "D", textEn: "Algae", textMr: "शैवाल", isCorrect: false },
      ],
    },
    {
      textEn: "Which bacteria is used to prepare curd?",
      textMr: "दही तयार करण्यासाठी कोणत्या जीवाणूचा वापर होतो?",
      explanationEn: "Lactobacillus bacteria converts lactose in milk to lactic acid, causing milk to curdle and form yogurt (curd).",
      explanationMr: "लॅक्टोबॅसिलस (Lactobacillus) हा जीवाणू दुधातील लॅक्टोजचे लॅक्टिक आम्लात रूपांतर करतो ज्यामुळे दही तयार होते.",
      options: [
        { label: "A", textEn: "Escherichia coli", textMr: "एश्चेरिशिया कोलाय", isCorrect: false },
        { label: "B", textEn: "Lactobacillus", textMr: "लॅक्टोबॅसिलस", isCorrect: true },
        { label: "C", textEn: "Staphylococcus", textMr: "स्टॅफिलोकोकस", isCorrect: false },
        { label: "D", textEn: "Streptococcus", textMr: "स्ट्रेप्टोकोकस", isCorrect: false },
      ],
    },
    {
      textEn: "Malaria is caused by which parasite?",
      textMr: "मलेरिया रोग कोणत्या परजीवीमुळे होतो?",
      explanationEn: "Malaria is caused by Plasmodium parasite. It is transmitted through the bite of the female Anopheles mosquito.",
      explanationMr: "मलेरिया प्लाझमोडियम (Plasmodium) या परजीवीमुळे होतो. मादी अॅनॉफिलीस डासाद्वारे हा रोग पसरतो.",
      options: [
        { label: "A", textEn: "Plasmodium", textMr: "प्लाझमोडियम", isCorrect: true },
        { label: "B", textEn: "Leishmania", textMr: "लिशमानिया", isCorrect: false },
        { label: "C", textEn: "Trypanosoma", textMr: "ट्रिपॅनोसोमा", isCorrect: false },
        { label: "D", textEn: "Entamoeba", textMr: "एंटामोइबा", isCorrect: false },
      ],
    },
    {
      textEn: "The greenhouse effect is caused by?",
      textMr: "हरितगृह परिणाम (greenhouse effect) कशामुळे होतो?",
      explanationEn: "Greenhouse effect is caused by gases like carbon dioxide (CO₂), methane (CH₄), nitrous oxide (N₂O). These gases trap Earth's heat and prevent it from escaping into space.",
      explanationMr: "हरितगृह परिणाम कार्बन डायऑक्साइड (CO₂), मिथेन (CH₄), नायट्रस ऑक्साइड (N₂O) सारख्या वायूंमुळे होतो. हे वायू पृथ्वीची उष्णता अवकाशात जाण्यापासून रोखतात.",
      options: [
        { label: "A", textEn: "Oxygen", textMr: "ऑक्सिजन", isCorrect: false },
        { label: "B", textEn: "Greenhouse gases like CO₂, CH₄", textMr: "CO₂, CH₄ सारख्या हरितगृह वायूंमुळे", isCorrect: true },
        { label: "C", textEn: "Nitrogen", textMr: "नायट्रोजन", isCorrect: false },
        { label: "D", textEn: "Hydrogen", textMr: "हायड्रोजन", isCorrect: false },
      ],
    },
    {
      textEn: "What is biodegradable waste?",
      textMr: "जैवविघटनशील (biodegradable) कचरा म्हणजे काय?",
      explanationEn: "Biodegradable waste is waste that can be broken down by microorganisms (bacteria, fungi). E.g. food, paper, wood. Plastic and glass are non-biodegradable.",
      explanationMr: "जैवविघटनशील कचरा म्हणजे जो सूक्ष्मजीवांद्वारे (जीवाणू, बुरशी) विघटित होतो. उदा. अन्नपदार्थ, कागद, लाकूड. प्लास्टिक, काच हे अजैवविघटनशील असतात.",
      options: [
        { label: "A", textEn: "Plastic", textMr: "प्लास्टिक", isCorrect: false },
        { label: "B", textEn: "Waste that can be broken down by microbes", textMr: "सूक्ष्मजीवांद्वारे विघटित होणारा कचरा", isCorrect: true },
        { label: "C", textEn: "Glass", textMr: "काच", isCorrect: false },
        { label: "D", textEn: "Metal", textMr: "धातू", isCorrect: false },
      ],
    },
    {
      textEn: "Which gas depletes the ozone layer?",
      textMr: "ओझोन थर कोणत्या वायूमुळे नष्ट होतो?",
      explanationEn: "Chlorofluorocarbon (CFC) gas depletes the ozone layer. CFCs are used in refrigerators, ACs, and sprays. The ozone layer protects Earth from harmful UV rays.",
      explanationMr: "क्लोरोफ्लोरोकार्बन (CFC) वायू ओझोन थर नष्ट करतो. CFC फ्रीज, एसी, स्प्रेमध्ये वापरतात. ओझोन थर UV किरणांपासून पृथ्वीचे रक्षण करतो.",
      options: [
        { label: "A", textEn: "CO₂", textMr: "CO₂", isCorrect: false },
        { label: "B", textEn: "CFC (Chlorofluorocarbon)", textMr: "CFC (क्लोरोफ्लोरोकार्बन)", isCorrect: true },
        { label: "C", textEn: "O₂", textMr: "O₂", isCorrect: false },
        { label: "D", textEn: "N₂", textMr: "N₂", isCorrect: false },
      ],
    },
    {
      textEn: "Internet initially started under which name?",
      textMr: "इंटरनेटची सुरुवात कोणत्या नावाने झाली?",
      explanationEn: "The Internet started as ARPANET (Advanced Research Projects Agency Network) in 1969, developed by the US Department of Defense.",
      explanationMr: "इंटरनेटची सुरुवात ARPANET (Advanced Research Projects Agency Network) या नावाने 1969 मध्ये अमेरिकेच्या संरक्षण विभागाने केली.",
      options: [
        { label: "A", textEn: "INTERNET", textMr: "INTERNET", isCorrect: false },
        { label: "B", textEn: "ARPANET", textMr: "ARPANET", isCorrect: true },
        { label: "C", textEn: "NSFNET", textMr: "NSFNET", isCorrect: false },
        { label: "D", textEn: "BITNET", textMr: "BITNET", isCorrect: false },
      ],
    },
    {
      textEn: "Who is the father of WWW (World Wide Web)?",
      textMr: "WWW (World Wide Web) चे जनक कोण?",
      explanationEn: "Tim Berners-Lee invented the World Wide Web (WWW) in 1989. He was working at CERN at the time.",
      explanationMr: "टीम बर्नर्स-ली यांनी 1989 मध्ये World Wide Web (WWW) चा शोध लावला. ते CERN येथे काम करत होते.",
      options: [
        { label: "A", textEn: "Bill Gates", textMr: "बिल गेट्स", isCorrect: false },
        { label: "B", textEn: "Tim Berners-Lee", textMr: "टीम बर्नर्स-ली", isCorrect: true },
        { label: "C", textEn: "Steve Jobs", textMr: "स्टीव्ह जॉब्स", isCorrect: false },
        { label: "D", textEn: "Mark Zuckerberg", textMr: "मार्क झुकरबर्ग", isCorrect: false },
      ],
    },
    {
      textEn: "In which unit is digital data measured?",
      textMr: "डिजिटल डेटा कोणत्या एककाने मोजतात?",
      explanationEn: "The smallest unit of digital data is bit (0 or 1). 8 bits = 1 byte. Then comes Kilobyte, Megabyte, Gigabyte, Terabyte.",
      explanationMr: "डिजिटल डेटाचे सर्वात लहान एकक बिट (0 किंवा 1) आहे. 8 बिट = 1 बाइट. पुढे Kilobyte, Megabyte, Gigabyte, Terabyte येतात.",
      options: [
        { label: "A", textEn: "Metre", textMr: "मीटर", isCorrect: false },
        { label: "B", textEn: "Bit and Byte", textMr: "बिट आणि बाइट", isCorrect: true },
        { label: "C", textEn: "Hertz", textMr: "हर्ट्झ", isCorrect: false },
        { label: "D", textEn: "Volt", textMr: "व्होल्ट", isCorrect: false },
      ],
    },
    {
      textEn: "What type of image is formed by a plane mirror?",
      textMr: "समतल दर्पणात तयार होणारी प्रतिमा कशी असते?",
      explanationEn: "A plane mirror forms a virtual, erect image behind the mirror, of the same size as the object. Left and right are laterally inverted.",
      explanationMr: "समतल दर्पणात तयार होणारी प्रतिमा आभासी (virtual), सरळ (erect), दर्पणाच्या मागे आणि वस्तूएवढ्याच आकाराची असते. डावे-उजवे उलटे दिसते.",
      options: [
        { label: "A", textEn: "Real, inverted", textMr: "वास्तव, उलटी", isCorrect: false },
        { label: "B", textEn: "Virtual, erect", textMr: "आभासी, सरळ", isCorrect: true },
        { label: "C", textEn: "Real, erect", textMr: "वास्तव, सरळ", isCorrect: false },
        { label: "D", textEn: "Virtual, inverted", textMr: "आभासी, उलटी", isCorrect: false },
      ],
    },
    {
      textEn: "Law of reflection: Angle of incidence is equal to angle of _____.",
      textMr: "परावर्तनाचा नियम: आपात कोन _____ परावर्तन कोनाशी समान असतो.",
      explanationEn: "Law of reflection: Angle of incidence = Angle of reflection. The incident ray, reflected ray, and normal all lie in the same plane.",
      explanationMr: "परावर्तनाचा नियम: आपात कोन (angle of incidence) = परावर्तन कोन (angle of reflection). आपात किरण, परावर्तित किरण व अभिलंब एकाच समतलात असतात.",
      options: [
        { label: "A", textEn: "Refraction", textMr: "अपवर्तन", isCorrect: false },
        { label: "B", textEn: "Reflection", textMr: "परावर्तन", isCorrect: true },
        { label: "C", textEn: "Polarisation", textMr: "ध्रुवण", isCorrect: false },
        { label: "D", textEn: "Diffraction", textMr: "विवर्तन", isCorrect: false },
      ],
    },
    {
      textEn: "Concave mirror is used for?",
      textMr: "अवतल दर्पण (concave mirror) चा वापर कशासाठी होतो?",
      explanationEn: "Concave mirrors are used in dentistry, vehicle headlights, solar furnaces, and shaving mirrors. Convex mirrors are used as side (rear-view) mirrors in vehicles.",
      explanationMr: "अवतल दर्पण दंत डॉक्टर, वाहनांचे हेडलाइट, सोलार फर्नेस, शेव्हिंग मिरर यांसाठी वापरतात. उत्तल दर्पण वाहनांच्या साइड मिररसाठी वापरतात.",
      options: [
        { label: "A", textEn: "Rear-view in vehicles", textMr: "वाहनांच्या मागे पाहण्यासाठी", isCorrect: false },
        { label: "B", textEn: "Dentistry, vehicle headlights", textMr: "दंतचिकित्सा, वाहनांचे हेडलाइट", isCorrect: true },
        { label: "C", textEn: "Security in shops", textMr: "दुकानांत सुरक्षेसाठी", isCorrect: false },
        { label: "D", textEn: "Decoration in halls", textMr: "हॉलमध्ये सजावटीसाठी", isCorrect: false },
      ],
    },
    {
      textEn: "In which unit is frequency of sound measured?",
      textMr: "ध्वनीची वारंवारता (frequency) कशात मोजतात?",
      explanationEn: "Frequency of sound is measured in Hertz (Hz). Human ears can hear sounds from 20 Hz to 20,000 Hz.",
      explanationMr: "ध्वनीची वारंवारता हर्ट्झ (Hz) मध्ये मोजतात. मानवी कान 20 Hz ते 20,000 Hz वारंवारतेचा ध्वनी ऐकू शकतो.",
      options: [
        { label: "A", textEn: "Decibel", textMr: "डेसिबल", isCorrect: false },
        { label: "B", textEn: "Hertz", textMr: "हर्ट्झ", isCorrect: true },
        { label: "C", textEn: "Metre", textMr: "मीटर", isCorrect: false },
        { label: "D", textEn: "Second", textMr: "सेकंद", isCorrect: false },
      ],
    },
    {
      textEn: "What is ultrasound?",
      textMr: "अल्ट्रासाऊंड म्हणजे काय?",
      explanationEn: "Ultrasound refers to sound with frequency greater than 20,000 Hz (20 kHz) that humans cannot hear. It is used in medical imaging (sonography), cleaning, etc.",
      explanationMr: "अल्ट्रासाऊंड म्हणजे 20,000 Hz (20 kHz) पेक्षा जास्त वारंवारतेचा ध्वनी जो मानवाला ऐकू येत नाही. वैद्यकीय तपासणी, सोनोग्राफी, सफाई यात वापर होतो.",
      options: [
        { label: "A", textEn: "Sound with frequency less than 20 Hz", textMr: "20 Hz पेक्षा कमी वारंवारतेचा ध्वनी", isCorrect: false },
        { label: "B", textEn: "Sound with frequency greater than 20,000 Hz", textMr: "20,000 Hz पेक्षा जास्त वारंवारतेचा ध्वनी", isCorrect: true },
        { label: "C", textEn: "Visible light", textMr: "दृश्य प्रकाश", isCorrect: false },
        { label: "D", textEn: "Radio waves", textMr: "रेडिओ लहरी", isCorrect: false },
      ],
    },
    {
      textEn: "Why cannot sound travel through vacuum?",
      textMr: "शून्यात (vacuum) ध्वनी का प्रवास करत नाही?",
      explanationEn: "Sound is a mechanical wave and requires a medium for propagation. Since vacuum has no medium, sound cannot travel through it.",
      explanationMr: "ध्वनी यांत्रिक लहरी (mechanical waves) आहेत आणि त्यांना प्रसारासाठी माध्यम आवश्यक असते. शून्यात (vacuum) माध्यम नसल्याने ध्वनी प्रवास करू शकत नाही.",
      options: [
        { label: "A", textEn: "Sound is very small", textMr: "ध्वनी खूप लहान असतो", isCorrect: false },
        { label: "B", textEn: "Sound needs a medium to travel", textMr: "ध्वनीला प्रवासासाठी माध्यम आवश्यक आहे", isCorrect: true },
        { label: "C", textEn: "There is no light in vacuum", textMr: "शून्यात प्रकाश नसतो", isCorrect: false },
        { label: "D", textEn: "Sound needs water", textMr: "ध्वनीला पाण्याची गरज असते", isCorrect: false },
      ],
    },
    {
      textEn: "The different forms of carbon are called?",
      textMr: "कार्बनच्या विविध रूपांना काय म्हणतात?",
      explanationEn: "Allotropes of carbon include diamond, graphite, and fullerene. Different physical forms of the same element are called allotropes.",
      explanationMr: "कार्बनचे अपरूप (allotropes) म्हणजे हिरा (diamond), ग्रॅफाइट (graphite) आणि फुलेरीन (fullerene). एकाच मूलद्रव्याचे वेगळे भौतिक गुणधर्म असलेल्या रूपांना अपरूप म्हणतात.",
      options: [
        { label: "A", textEn: "Isotopes", textMr: "समस्थानिक", isCorrect: false },
        { label: "B", textEn: "Allotropes", textMr: "अपरूप", isCorrect: true },
        { label: "C", textEn: "Isobars", textMr: "समभारिक", isCorrect: false },
        { label: "D", textEn: "Isomers", textMr: "समावयव", isCorrect: false },
      ],
    },
    {
      textEn: "Why is diamond so hard?",
      textMr: "हिरा (diamond) इतका कठीण का असतो?",
      explanationEn: "In diamond, each carbon atom is bonded to four other carbon atoms by covalent bonds in a tetrahedral arrangement, making it extremely hard.",
      explanationMr: "हऱ्यात प्रत्येक कार्बन अणू चतुष्फलकीय (tetrahedral) रचनेत चार इतर कार्बन अणूंशी सहसंयोजक बंधाने (covalent bonds) जोडलेला असतो, त्यामुळे तो अत्यंत कठीण असतो.",
      options: [
        { label: "A", textEn: "It contains metals", textMr: "त्यात धातू असतात", isCorrect: false },
        { label: "B", textEn: "Each C atom bonded to 4 others by covalent bonds", textMr: "प्रत्येक कार्बन अणू चार इतर कार्बन अणूंशी सहसंयोजक बंधाने जोडलेला असतो", isCorrect: true },
        { label: "C", textEn: "It contains gold", textMr: "त्यात सोने असते", isCorrect: false },
        { label: "D", textEn: "It forms in water", textMr: "तो पाण्यात बनतो", isCorrect: false },
      ],
    },
    {
      textEn: "What are organic compounds?",
      textMr: "सेंद्रिय संयुगे (organic compounds) म्हणजे काय?",
      explanationEn: "Compounds made from carbon are called organic compounds. E.g. methane (CH₄), ethanol (C₂H₅OH). Carbon has a special ability to form chains (catenation).",
      explanationMr: "कार्बनपासून बनलेले संयुगे सेंद्रिय संयुगे म्हणतात. उदा. मिथेन (CH₄), इथेनॉल (C₂H₅OH). कार्बनला साखळी बनवण्याची विशेष क्षमता आहे (catenation).",
      options: [
        { label: "A", textEn: "Made from metals", textMr: "धातूंपासून बनलेले", isCorrect: false },
        { label: "B", textEn: "Compounds made from carbon", textMr: "कार्बनपासून बनलेले संयुगे", isCorrect: true },
        { label: "C", textEn: "Soluble in water", textMr: "पाण्यात विरघळणारे", isCorrect: false },
        { label: "D", textEn: "Found only in living organisms", textMr: "फक्त सजीवांमध्ये आढळणारे", isCorrect: false },
      ],
    },
    {
      textEn: "Soap is made from?",
      textMr: "साबण (soap) कशापासून बनवतात?",
      explanationEn: "Soap is made by the reaction of vegetable oils or animal fats (fatty acids) with sodium hydroxide (NaOH) or potassium hydroxide (KOH). This process is called saponification.",
      explanationMr: "साबण वनस्पती तेल किंवा प्राणी चरबी (वसा अम्ल) आणि सोडियम हायड्रॉक्साइड (NaOH) किंवा पोटॅशियम हायड्रॉक्साइड (KOH) यांच्या अभिक्रियेतून तयार होतो. यालाच साबणीकरण (saponification) म्हणतात.",
      options: [
        { label: "A", textEn: "Sand and water", textMr: "वाळू आणि पाणी", isCorrect: false },
        { label: "B", textEn: "Fatty acids and NaOH/KOH", textMr: "वसा अम्ल आणि NaOH/KOH", isCorrect: true },
        { label: "C", textEn: "Plastic", textMr: "प्लास्टिक", isCorrect: false },
        { label: "D", textEn: "Mineral oil", textMr: "खनिज तेल", isCorrect: false },
      ],
    },
    {
      textEn: "Plastic and nylon are what type of materials?",
      textMr: "प्लास्टिक आणि नायलॉन हे कोणत्या प्रकारचे पदार्थ आहेत?",
      explanationEn: "Plastics (polyethylene, PVC), nylon, terylene are polymers — large molecules made of chains of many monomers.",
      explanationMr: "प्लास्टिक (polyethylene, PVC), नायलॉन, टेरिलीन हे बहुवारिक (polymers) आहेत - अनेक एकारिकांच्या (monomers) साखळ्यांनी बनलेले मोठे रेणू.",
      options: [
        { label: "A", textEn: "Metals", textMr: "धातू", isCorrect: false },
        { label: "B", textEn: "Polymers", textMr: "बहुवारिक (polymers)", isCorrect: true },
        { label: "C", textEn: "Salts", textMr: "क्षार", isCorrect: false },
        { label: "D", textEn: "Minerals", textMr: "खनिजे", isCorrect: false },
      ],
    },
    {
      textEn: "What is the equation for photosynthesis?",
      textMr: "प्रकाशसंश्लेषणाचे सूत्र कोणते?",
      explanationEn: "Photosynthesis: 6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂. In the presence of sunlight and chlorophyll, CO₂ and water form glucose and oxygen.",
      explanationMr: "प्रकाशसंश्लेषण: 6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂. सूर्यप्रकाश आणि क्लोरोफिलच्या उपस्थितीत कार्बन डायऑक्साइड आणि पाण्यापासून ग्लुकोज आणि ऑक्सिजन तयार होतात.",
      options: [
        { label: "A", textEn: "C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O", textMr: "C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O", isCorrect: false },
        { label: "B", textEn: "6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂", textMr: "6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂", isCorrect: true },
        { label: "C", textEn: "CO₂ + H₂O → O₂", textMr: "CO₂ + H₂O → O₂", isCorrect: false },
        { label: "D", textEn: "H₂O + O₂ → CO₂", textMr: "H₂O + O₂ → CO₂", isCorrect: false },
      ],
    },
    {
      textEn: "What is the main function of respiration?",
      textMr: "श्वासोच्छ्वासाचे (respiration) मुख्य कार्य काय आहे?",
      explanationEn: "In respiration, glucose is oxidised to produce ATP (energy), CO₂, and H₂O. Equation: C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + energy.",
      explanationMr: "श्वासोच्छ्वासात ग्लुकोजचे ऑक्सीकरण होऊन ATP (ऊर्जा), CO₂ आणि H₂O तयार होतात. सूत्र: C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ऊर्जा.",
      options: [
        { label: "A", textEn: "Producing food", textMr: "अन्न तयार करणे", isCorrect: false },
        { label: "B", textEn: "Releasing energy (ATP)", textMr: "ऊर्जा (ATP) मुक्त करणे", isCorrect: true },
        { label: "C", textEn: "Absorbing CO₂", textMr: "कार्बन डायऑक्साइड घेणे", isCorrect: false },
        { label: "D", textEn: "Producing water", textMr: "पाणी तयार करणे", isCorrect: false },
      ],
    },
    {
      textEn: "Which pigment in blood carries oxygen?",
      textMr: "रक्तातून ऑक्सिजन वाहून नेणारे रंगद्रव्य कोणते?",
      explanationEn: "Red blood cells contain haemoglobin pigment, which carries oxygen from the lungs to all cells of the body.",
      explanationMr: "लाल रक्तपेशींमध्ये हिमोग्लोबिन (haemoglobin) हे रंगद्रव्य असते जे फुफ्फुसातून ऑक्सिजन घेऊन सर्व पेशींना पोहोचवते.",
      options: [
        { label: "A", textEn: "Chlorophyll", textMr: "क्लोरोफिल", isCorrect: false },
        { label: "B", textEn: "Haemoglobin", textMr: "हिमोग्लोबिन", isCorrect: true },
        { label: "C", textEn: "Melanin", textMr: "मेलॅनिन", isCorrect: false },
        { label: "D", textEn: "Bilirubin", textMr: "बिलिरुबिन", isCorrect: false },
      ],
    },
    {
      textEn: "Who is called the father of genetics?",
      textMr: "आनुवंशिकतेचे जनक कोण आहेत?",
      explanationEn: "Gregor Mendel is called the father of genetics. He conducted experiments on pea plants and proposed the laws of heredity.",
      explanationMr: "ग्रेगर मेंडेल यांना आनुवंशिकतेचे जनक (father of genetics) म्हणतात. त्यांनी वाटाण्याच्या झाडावर प्रयोग करून आनुवंशिकतेचे नियम मांडले.",
      options: [
        { label: "A", textEn: "Charles Darwin", textMr: "चार्ल्स डार्विन", isCorrect: false },
        { label: "B", textEn: "Gregor Mendel", textMr: "ग्रेगर मेंडेल", isCorrect: true },
        { label: "C", textEn: "Thomas Morgan", textMr: "थॉमस मॉर्गन", isCorrect: false },
        { label: "D", textEn: "Francis Crick", textMr: "फ्रांसिस क्रिक", isCorrect: false },
      ],
    },
    {
      textEn: "What is the full form of DNA?",
      textMr: "DNA चे पूर्ण रूप काय आहे?",
      explanationEn: "DNA stands for Deoxyribonucleic Acid. DNA is the molecule that stores hereditary information. Its double helix structure was discovered by Watson and Crick in 1953.",
      explanationMr: "DNA म्हणजे Deoxyribonucleic Acid. DNA हे आनुवंशिक माहिती साठवणारे रेणू आहे. DNA ची रचना दुहेरी साखळी (double helix) असते — हे वॉटसन आणि क्रिक यांनी 1953 मध्ये शोधले.",
      options: [
        { label: "A", textEn: "Deoxyribose Nucleic Acid", textMr: "Deoxyribose Nucleic Acid", isCorrect: false },
        { label: "B", textEn: "Deoxyribonucleic Acid", textMr: "Deoxyribonucleic Acid", isCorrect: true },
        { label: "C", textEn: "Diribonucleic Acid", textMr: "Diribonucleic Acid", isCorrect: false },
        { label: "D", textEn: "Diaminonucleic Acid", textMr: "Diaminonucleic Acid", isCorrect: false },
      ],
    },
    {
      textEn: "In Mendel's law, in Rr × Rr cross, ratio of RR : Rr : rr is?",
      textMr: "मेंडेलच्या नियमाप्रमाणे Rr × Rr या संकरणात शुद्ध प्रबळ (RR) : संकरित प्रबळ (Rr) : शुद्ध अप्रबळ (rr) हे प्रमाण किती असते?",
      explanationEn: "In Rr × Rr cross, F₂ generation shows genotype ratio RR:Rr:rr = 1:2:1 and phenotype ratio dominant:recessive = 3:1.",
      explanationMr: "Rr × Rr संकरणात F₂ पिढीत जीनोटाइप प्रमाण RR:Rr:rr = 1:2:1 असते आणि फेनोटाइप प्रमाण प्रबळ:अप्रबळ = 3:1 असते.",
      options: [
        { label: "A", textEn: "1:1:1", textMr: "1:1:1", isCorrect: false },
        { label: "B", textEn: "1:2:1", textMr: "1:2:1", isCorrect: true },
        { label: "C", textEn: "3:1:0", textMr: "3:1:0", isCorrect: false },
        { label: "D", textEn: "2:1:2", textMr: "2:1:2", isCorrect: false },
      ],
    },
    {
      textEn: "What is genetic engineering?",
      textMr: "जनुकीय अभियांत्रिकी (genetic engineering) म्हणजे काय?",
      explanationEn: "Genetic engineering is the technique of modifying DNA of an organism to introduce new traits. It is used to produce Bt cotton, Bt brinjal, insulin, etc.",
      explanationMr: "जनुकीय अभियांत्रिकी म्हणजे सजीवाच्या DNA मध्ये बदल करून नवीन गुणधर्म निर्माण करण्याचे तंत्र. याद्वारे Bt Cotton, Bt Brinjal, इन्सुलिन उत्पादन होते.",
      options: [
        { label: "A", textEn: "Viewing genes under microscope", textMr: "सूक्ष्मदर्शकाने जनुक पाहणे", isCorrect: false },
        { label: "B", textEn: "Technique of modifying genes", textMr: "जनुकांमध्ये बदल करण्याचे तंत्र", isCorrect: true },
        { label: "C", textEn: "Blood test", textMr: "रक्त चाचणी", isCorrect: false },
        { label: "D", textEn: "Plant grafting", textMr: "वनस्पतींचे प्रत्यारोपण", isCorrect: false },
      ],
    },
    {
      textEn: "PCR (Polymerase Chain Reaction) is used for?",
      textMr: "PCR (Polymerase Chain Reaction) चा वापर कशासाठी होतो?",
      explanationEn: "PCR is a technique to make millions of copies of a specific DNA segment. It is used in forensics, medical diagnosis, and genetic research.",
      explanationMr: "PCR हे DNA च्या विशिष्ट भागाच्या कोट्यावधी प्रती तयार करण्याचे तंत्र आहे. हे फॉरेन्सिक, वैद्यकीय निदान, जनुकीय संशोधनात वापरतात.",
      options: [
        { label: "A", textEn: "Making proteins", textMr: "प्रथिने बनवण्यासाठी", isCorrect: false },
        { label: "B", textEn: "Making copies of DNA", textMr: "DNA च्या प्रती बनवण्यासाठी", isCorrect: true },
        { label: "C", textEn: "Making medicines", textMr: "औषधे बनवण्यासाठी", isCorrect: false },
        { label: "D", textEn: "Testing blood group", textMr: "रक्त गट तपासण्यासाठी", isCorrect: false },
      ],
    },
    {
      textEn: "Which bacterium is used to produce human insulin?",
      textMr: "मानवी इन्सुलिन बनवण्यासाठी कोणत्या जीवाणूचा वापर होतो?",
      explanationEn: "Human insulin is produced by inserting the human insulin gene into E. coli bacteria through genetic engineering. It is used in diabetes treatment.",
      explanationMr: "मानवी इन्सुलिन जनुकीय अभियांत्रिकीद्वारे E. coli जीवाणूमध्ये मानवी इन्सुलिन जनुक घालून बनवतात. हे मधुमेहावरील उपचारात वापरतात.",
      options: [
        { label: "A", textEn: "Lactobacillus", textMr: "लॅक्टोबॅसिलस", isCorrect: false },
        { label: "B", textEn: "Escherichia coli (E. coli)", textMr: "एश्चेरिशिया कोलाय (E. coli)", isCorrect: true },
        { label: "C", textEn: "Clostridium", textMr: "क्लोस्ट्रिडियम", isCorrect: false },
        { label: "D", textEn: "Streptococcus", textMr: "स्ट्रेप्टोकोकस", isCorrect: false },
      ],
    },
    {
      textEn: "Who invented the telescope?",
      textMr: "दुर्बिणीचा शोध कोणी लावला?",
      explanationEn: "The telescope was invented by Hans Lippershey in 1608. Galileo improved it in 1609 and used it for astronomical observations.",
      explanationMr: "दुर्बिणीचा शोध हान्स लिपरशेय (Hans Lippershey) यांनी 1608 मध्ये लावला. गॅलिलिओने 1609 मध्ये सुधारित दुर्बीण बनवून खगोलशास्त्रात वापरली.",
      options: [
        { label: "A", textEn: "Newton", textMr: "न्यूटन", isCorrect: false },
        { label: "B", textEn: "Galileo Galilei", textMr: "गॅलिलिओ गॅलिली", isCorrect: false },
        { label: "C", textEn: "Hans Lippershey", textMr: "हान्स लिपरशेय", isCorrect: true },
        { label: "D", textEn: "Copernicus", textMr: "कोपर्निकस", isCorrect: false },
      ],
    },
    {
      textEn: "Where is the Hubble Space Telescope located?",
      textMr: "हबल अवकाश दुर्बीण (Hubble Space Telescope) कोठे स्थित आहे?",
      explanationEn: "The Hubble Space Telescope has been orbiting Earth (at approximately 547 km altitude) since 1990. Being outside Earth's atmosphere, it captures very clear images.",
      explanationMr: "हबल अवकाश दुर्बीण 1990 पासून पृथ्वीच्या कक्षेत (सुमारे 547 km उंचीवर) फिरत आहे. ती पृथ्वीच्या वातावरणाबाहेर असल्याने स्पष्ट प्रतिमा घेते.",
      options: [
        { label: "A", textEn: "On the Moon", textMr: "चंद्रावर", isCorrect: false },
        { label: "B", textEn: "In Earth's orbit", textMr: "पृथ्वीच्या कक्षेत", isCorrect: true },
        { label: "C", textEn: "On Mars", textMr: "मंगळावर", isCorrect: false },
        { label: "D", textEn: "On the Sun", textMr: "सूर्यावर", isCorrect: false },
      ],
    },
    {
      textEn: "Which waves does a radio telescope detect?",
      textMr: "रेडिओ दुर्बीण (radio telescope) कोणत्या लहरी पकडते?",
      explanationEn: "A radio telescope detects radio waves coming from objects in space. Unlike optical telescopes, it is not hindered by clouds or day/night conditions.",
      explanationMr: "रेडिओ दुर्बीण अवकाशातील वस्तूंपासून येणाऱ्या रेडिओ लहरी पकडते. प्रकाशीय दुर्बीणीप्रमाणे याला ढग किंवा दिवस/रात्र यांचा अडथळा येत नाही.",
      options: [
        { label: "A", textEn: "Visible light", textMr: "दृश्य प्रकाश", isCorrect: false },
        { label: "B", textEn: "Radio waves", textMr: "रेडिओ लहरी", isCorrect: true },
        { label: "C", textEn: "X-rays", textMr: "क्ष-किरण", isCorrect: false },
        { label: "D", textEn: "Ultraviolet rays", textMr: "अतिनील किरण", isCorrect: false },
      ],
    },
    {
      textEn: "What is India's largest radio telescope?",
      textMr: "भारताची सर्वात मोठी रेडिओ दुर्बीण कोणती आहे?",
      explanationEn: "GMRT (Giant Metrewave Radio Telescope) is located at Khodad near Pune. It is one of the world's largest radio telescope arrays, operated by TIFR, Mumbai.",
      explanationMr: "GMRT (Giant Metrewave Radio Telescope) पुण्याजवळील खोडद येथे स्थित आहे. हे जगातील सर्वात मोठ्या रेडिओ दुर्बिणींपैकी एक आहे. TIFR, मुंबई याचे संचालन करते.",
      options: [
        { label: "A", textEn: "VLA (USA)", textMr: "VLA (अमेरिका)", isCorrect: false },
        { label: "B", textEn: "GMRT (Giant Metrewave Radio Telescope)", textMr: "GMRT (जायंट मीटरवेव्ह रेडिओ टेलिस्कोप)", isCorrect: true },
        { label: "C", textEn: "FAST (China)", textMr: "FAST (चीन)", isCorrect: false },
        { label: "D", textEn: "Hubble", textMr: "हबल", isCorrect: false },
      ],
    },
  ],
};

export default data;
