import type { QuestionSetInput } from "./types";

// Source: All questions & answer/AMVI_Std9_HPS_English.pdf + AMVI_Std9_HPS_Marathi.pdf
// Both PDFs share identical question numbering/options/answers (47 MCQs).
// Some option cells in the source combined a Devanagari numeral with its English gloss
// (e.g. "१९६०/ 1960"); these were split into clean separate textEn/textMr fields.
const data: QuestionSetInput = {
  standard: { code: "STD9", nameEn: "Standard 9", nameMr: "इयत्ता ९वी", sortOrder: 9 },
  subject: { code: "HPS", nameEn: "History & Political Science", nameMr: "इतिहास व राज्यशास्त्र", sortOrder: 2 },
  questions: [
    {
      textEn: "What is an important written source of modern history?",
      textMr: "आधुनिक इतिहासाचे महत्त्वाचे लिखित साधन कोणते आहे?",
      explanationEn: "Newspapers are important written sources of modern history containing news about national, international, political and social events.",
      explanationMr: "वृत्तपत्रे आधुनिक काळातील महत्त्वाचे लिखित साधन आहेत. त्यात देश-विदेशातील घटना, राजकारण व समाजाची माहिती असते.",
      options: [
        { label: "A", textEn: "Coins", textMr: "नाणी", isCorrect: false },
        { label: "B", textEn: "Newspapers", textMr: "वृत्तपत्रे", isCorrect: true },
        { label: "C", textEn: "Inscriptions", textMr: "शिलालेख", isCorrect: false },
        { label: "D", textEn: "Architecture", textMr: "स्थापत्यशास्त्र", isCorrect: false },
      ],
    },
    {
      textEn: "What is included in material/archaeological sources?",
      textMr: "पुरातत्त्वीय पुरावे (Material Sources) मध्ये कशाचा समावेश होतो?",
      explanationEn: "Material (archaeological) sources include coins, sculptures, utensils, buildings, weapons, and other physical remains.",
      explanationMr: "भौतिक (पुरातत्त्वीय) स्रोतांत नाणी, मूर्ती, भांडी, इमारती, शस्त्रे यांचा समावेश होतो.",
      options: [
        { label: "A", textEn: "Newspapers", textMr: "वृत्तपत्रे", isCorrect: false },
        { label: "B", textEn: "Coins, sculptures, utensils", textMr: "नाणी, मूर्ती, भांडी", isCorrect: true },
        { label: "C", textEn: "Parliament debates", textMr: "संसद चर्चा", isCorrect: false },
        { label: "D", textEn: "Radio programmes", textMr: "रेडिओ कार्यक्रम", isCorrect: false },
      ],
    },
    {
      textEn: "In which year was PTI (Press Trust of India) established?",
      textMr: "PTI (Press Trust of India) ची स्थापना कोणत्या वर्षी झाली?",
      explanationEn: "Press Trust of India (PTI) was established in 1953. It is India's national news agency.",
      explanationMr: "प्रेस ट्रस्ट ऑफ इंडिया (PTI) ची स्थापना १९५३ साली झाली. हे भारताचे राष्ट्रीय वृत्तसंस्था आहे.",
      options: [
        { label: "A", textEn: "1947", textMr: "१९४७", isCorrect: false },
        { label: "B", textEn: "1949", textMr: "१९४९", isCorrect: false },
        { label: "C", textEn: "1953", textMr: "१९५३", isCorrect: true },
        { label: "D", textEn: "1960", textMr: "१९६०", isCorrect: false },
      ],
    },
    {
      textEn: "Where is the National Archives of India located?",
      textMr: "भारताचे राष्ट्रीय पुरालेखागार (National Archives) कोठे आहे?",
      explanationEn: "National Archives of India is located in New Delhi. It is the largest archive in Asia.",
      explanationMr: "भारताचे राष्ट्रीय पुरालेखागार नवी दिल्ली येथे आहे. ते आशियातील सर्वात मोठे पुरालेखागार आहे.",
      options: [
        { label: "A", textEn: "Mumbai", textMr: "मुंबई", isCorrect: false },
        { label: "B", textEn: "Kolkata", textMr: "कोलकाता", isCorrect: false },
        { label: "C", textEn: "New Delhi", textMr: "नवी दिल्ली", isCorrect: true },
        { label: "D", textEn: "Chennai", textMr: "चेन्नई", isCorrect: false },
      ],
    },
    {
      textEn: "In which year did the India-China war occur?",
      textMr: "भारत-चीन युद्ध कोणत्या वर्षी झाले?",
      explanationEn: "The India-China war occurred in 1962 over the MacMahon Line dispute. India suffered a defeat in this war.",
      explanationMr: "भारत-चीन युद्ध १९६२ साली मॅकमहोन रेषेवरील वादामुळे झाले. या युद्धात भारताचा पराभव झाला.",
      options: [
        { label: "A", textEn: "1947", textMr: "१९४७", isCorrect: false },
        { label: "B", textEn: "1962", textMr: "१९६२", isCorrect: true },
        { label: "C", textEn: "1965", textMr: "१९६५", isCorrect: false },
        { label: "D", textEn: "1971", textMr: "१९७१", isCorrect: false },
      ],
    },
    {
      textEn: "Who gave the slogan 'Jai Jawan Jai Kisan'?",
      textMr: "'जय जवान जय किसान' हा नारा कोणी दिला?",
      explanationEn: "Lal Bahadur Shastri gave the slogan 'Jai Jawan Jai Kisan' during the India-Pakistan war (1965).",
      explanationMr: "लाल बहादूर शास्त्री यांनी भारत-पाक युद्ध (१९६५) दरम्यान 'जय जवान जय किसान' हा नारा दिला.",
      options: [
        { label: "A", textEn: "Pt. Jawaharlal Nehru", textMr: "पं. जवाहरलाल नेहरू", isCorrect: false },
        { label: "B", textEn: "Lal Bahadur Shastri", textMr: "लाल बहादूर शास्त्री", isCorrect: true },
        { label: "C", textEn: "Indira Gandhi", textMr: "इंदिरा गांधी", isCorrect: false },
        { label: "D", textEn: "Rajiv Gandhi", textMr: "राजीव गांधी", isCorrect: false },
      ],
    },
    {
      textEn: "In which year was Bangladesh created?",
      textMr: "बांगलादेशाची निर्मिती कोणत्या वर्षी झाली?",
      explanationEn: "In the 1971 India-Pakistan war, India defeated Pakistan and East Pakistan became independent as Bangladesh.",
      explanationMr: "१९७१ च्या भारत-पाकिस्तान युद्धात भारताने पाकिस्तानचा पराभव केला व पूर्व पाकिस्तान स्वतंत्र होऊन बांगलादेश निर्माण झाला.",
      options: [
        { label: "A", textEn: "1965", textMr: "१९६५", isCorrect: false },
        { label: "B", textEn: "1971", textMr: "१९७१", isCorrect: true },
        { label: "C", textEn: "1975", textMr: "१९७५", isCorrect: false },
        { label: "D", textEn: "1985", textMr: "१९८५", isCorrect: false },
      ],
    },
    {
      textEn: "Where and in which year did India conduct its first nuclear test?",
      textMr: "भारताने पहिली अणुचाचणी कोठे व कोणत्या वर्षी केली?",
      explanationEn: "India conducted its first nuclear test codenamed 'Smiling Buddha' on 18 May 1974 at Pokhran, Rajasthan.",
      explanationMr: "भारताने पहिली अणुचाचणी 'स्माइलिंग बुद्धा' या नावाने १८ मे १९७४ ला पोखरण (राजस्थान) येथे केली.",
      options: [
        { label: "A", textEn: "Pokhran, Rajasthan - 1974", textMr: "पोखरण, राजस्थान - १९७४", isCorrect: true },
        { label: "B", textEn: "Leh, Ladakh - 1971", textMr: "लेह, लडाख - १९७१", isCorrect: false },
        { label: "C", textEn: "Chandrapur, Maharashtra - 1975", textMr: "चंद्रपूर, महाराष्ट्र - १९७५", isCorrect: false },
        { label: "D", textEn: "BARC - 1978", textMr: "भाभा अणु संशोधन केंद्र - १९७८", isCorrect: false },
      ],
    },
    {
      textEn: "In which year was National Emergency imposed in India?",
      textMr: "राष्ट्रीय आणीबाणी (Emergency) कोणत्या वर्षी लागू करण्यात आली?",
      explanationEn: "Prime Minister Indira Gandhi imposed National Emergency from June 25, 1975 to March 21, 1977.",
      explanationMr: "पंतप्रधान इंदिरा गांधी यांनी २५ जून १९७५ ते २१ मार्च १९७७ या काळात राष्ट्रीय आणीबाणी लागू केली.",
      options: [
        { label: "A", textEn: "1971", textMr: "१९७१", isCorrect: false },
        { label: "B", textEn: "1973", textMr: "१९७३", isCorrect: false },
        { label: "C", textEn: "1975", textMr: "१९७५", isCorrect: true },
        { label: "D", textEn: "1977", textMr: "१९७७", isCorrect: false },
      ],
    },
    {
      textEn: "In which year did India's economic liberalisation begin?",
      textMr: "भारतात 'आर्थिक उदारीकरण' (Liberalisation) कोणत्या वर्षी सुरू झाले?",
      explanationEn: "PM P.V. Narasimha Rao and Finance Minister Dr. Manmohan Singh introduced economic liberalisation (LPG) in 1991.",
      explanationMr: "पंतप्रधान पी.व्ही. नरसिंह राव व अर्थमंत्री डॉ. मनमोहन सिंग यांनी १९९१ मध्ये आर्थिक उदारीकरण (LPG) सुरू केले.",
      options: [
        { label: "A", textEn: "1985", textMr: "१९८५", isCorrect: false },
        { label: "B", textEn: "1991", textMr: "१९९१", isCorrect: true },
        { label: "C", textEn: "1995", textMr: "१९९५", isCorrect: false },
        { label: "D", textEn: "2000", textMr: "२०००", isCorrect: false },
      ],
    },
    {
      textEn: "Where was 'Operation Blue Star' carried out?",
      textMr: "'ऑपरेशन ब्लू स्टार' कोठे करण्यात आले?",
      explanationEn: "Operation Blue Star was carried out in June 1984 at the Golden Temple in Amritsar to evict terrorists hiding there.",
      explanationMr: "ऑपरेशन ब्लू स्टार जून १९८४ मध्ये अमृतसरच्या सुवर्ण मंदिरात लपलेल्या अतिरेक्यांना हटवण्यासाठी करण्यात आले.",
      options: [
        { label: "A", textEn: "Ayodhya", textMr: "अयोध्या", isCorrect: false },
        { label: "B", textEn: "Amritsar (Golden Temple)", textMr: "अमृतसर (सुवर्ण मंदिर)", isCorrect: true },
        { label: "C", textEn: "Srinagar", textMr: "श्रीनगर", isCorrect: false },
        { label: "D", textEn: "Hyderabad", textMr: "हैद्राबाद", isCorrect: false },
      ],
    },
    {
      textEn: "Where did Naxalism first originate?",
      textMr: "नक्षलवाद प्रथम कोठे सुरू झाला?",
      explanationEn: "Naxalism originated in 1967 in Naxalbari village of West Bengal as an armed movement of peasants and tribals.",
      explanationMr: "नक्षलवाद १९६७ मध्ये पश्चिम बंगालच्या नक्षलबारी गावातून सुरू झाला. हे शेतकरी व आदिवासींचे सशस्त्र आंदोलन होते.",
      options: [
        { label: "A", textEn: "Bihar", textMr: "बिहार", isCorrect: false },
        { label: "B", textEn: "West Bengal (Naxalbari)", textMr: "पश्चिम बंगाल (नक्षलबारी)", isCorrect: true },
        { label: "C", textEn: "Odisha", textMr: "ओडिशा", isCorrect: false },
        { label: "D", textEn: "Jharkhand", textMr: "झारखंड", isCorrect: false },
      ],
    },
    {
      textEn: "ULFA (United Liberation Front of Assam) is related to which state?",
      textMr: "ULFA संघटना कोणत्या राज्याशी संबंधित आहे?",
      explanationEn: "ULFA (United Liberation Front of Assam) is an armed separatist organization that was active in northeast India.",
      explanationMr: "ULFA (United Liberation Front of Assam) आसाममधील एक सशस्त्र फुटीरतावादी संघटना आहे जी ईशान्य भारतात सक्रिय होती.",
      options: [
        { label: "A", textEn: "Manipur", textMr: "मणिपूर", isCorrect: false },
        { label: "B", textEn: "Meghalaya", textMr: "मेघालय", isCorrect: false },
        { label: "C", textEn: "Assam", textMr: "आसाम", isCorrect: true },
        { label: "D", textEn: "Mizoram", textMr: "मिझोरम", isCorrect: false },
      ],
    },
    {
      textEn: "The Anandpur Sahib Resolution was passed in which year?",
      textMr: "आनंदपूर साहिब ठराव कोणत्या वर्षी संमत झाला?",
      explanationEn: "The Anandpur Sahib Resolution was passed by the Akali Dal in 1973, demanding Chandigarh for Punjab among other issues.",
      explanationMr: "आनंदपूर साहिब ठराव अकाली दलाने १९७३ मध्ये संमत केला. यात चंदीगड पंजाबला द्यावे यासह विविध मागण्या होत्या.",
      options: [
        { label: "A", textEn: "1967", textMr: "१९६७", isCorrect: false },
        { label: "B", textEn: "1970", textMr: "१९७०", isCorrect: false },
        { label: "C", textEn: "1973", textMr: "१९७३", isCorrect: true },
        { label: "D", textEn: "1980", textMr: "१९८०", isCorrect: false },
      ],
    },
    {
      textEn: "When did India's First Five Year Plan start?",
      textMr: "भारताचा पहिला पंचवार्षिक योजना कोणत्या वर्षी सुरू झाली?",
      explanationEn: "India's First Five Year Plan started in 1951. It focused on agricultural development.",
      explanationMr: "भारताची पहिली पंचवार्षिक योजना १९५१ मध्ये सुरू झाली. या योजनेत शेती विकासावर भर होता.",
      options: [
        { label: "A", textEn: "1947", textMr: "१९४७", isCorrect: false },
        { label: "B", textEn: "1951", textMr: "१९५१", isCorrect: true },
        { label: "C", textEn: "1956", textMr: "१९५६", isCorrect: false },
        { label: "D", textEn: "1961", textMr: "१९६१", isCorrect: false },
      ],
    },
    {
      textEn: "Who is known as the father of the Green Revolution in India?",
      textMr: "हरित क्रांतीचे जनक म्हणून कोणाला ओळखले जाते?",
      explanationEn: "Dr. M.S. Swaminathan is known as the father of India's Green Revolution for developing hybrid seeds that increased food grain production.",
      explanationMr: "डॉ. एम. एस. स्वामीनाथन यांना भारतातील हरित क्रांतीचे जनक मानले जाते. त्यांनी नवीन संकरित बियाण्यांच्या वापरामुळे अन्नधान्य उत्पादन वाढवले.",
      options: [
        { label: "A", textEn: "Dr. Homi Bhabha", textMr: "डॉ. होमी भाभा", isCorrect: false },
        { label: "B", textEn: "Dr. M.S. Swaminathan", textMr: "डॉ. एम. एस. स्वामीनाथन", isCorrect: true },
        { label: "C", textEn: "Dr. Vikram Sarabhai", textMr: "डॉ. विक्रम साराभाई", isCorrect: false },
        { label: "D", textEn: "Dr. Raja Ramanna", textMr: "डॉ. राजा रामण्णा", isCorrect: false },
      ],
    },
    {
      textEn: "The White Revolution is associated with?",
      textMr: "श्वेत क्रांती (White Revolution) कशाशी संबंधित आहे?",
      explanationEn: "The White Revolution (Operation Flood) is associated with milk production. Dr. Verghese Kurien led it through the Amul cooperative.",
      explanationMr: "श्वेत क्रांती (ऑपरेशन फ्लड) दूध उत्पादन वाढीशी संबंधित आहे. डॉ. वर्गीस कुरियन यांनी अमूल सहकारी दूध संस्थेद्वारे ही क्रांती घडवली.",
      options: [
        { label: "A", textEn: "Food grain production", textMr: "अन्नधान्य उत्पादन", isCorrect: false },
        { label: "B", textEn: "Milk production", textMr: "दूध उत्पादन", isCorrect: true },
        { label: "C", textEn: "Fish production", textMr: "मत्स्य उत्पादन", isCorrect: false },
        { label: "D", textEn: "Sugar production", textMr: "साखर उत्पादन", isCorrect: false },
      ],
    },
    {
      textEn: "What does LPG policy stand for?",
      textMr: "LPG धोरण म्हणजे काय?",
      explanationEn: "LPG stands for Liberalisation, Privatisation, Globalisation. This policy was implemented in India in 1991.",
      explanationMr: "LPG म्हणजे उदारीकरण (Liberalisation), खाजगीकरण (Privatisation), जागतिकीकरण (Globalisation). भारतात हे धोरण १९९१ मध्ये लागू झाले.",
      options: [
        { label: "A", textEn: "Liquid Petroleum Gas", textMr: "Liquid Petroleum Gas", isCorrect: false },
        { label: "B", textEn: "Liberalisation, Privatisation, Globalisation", textMr: "Liberalisation, Privatisation, Globalisation", isCorrect: true },
        { label: "C", textEn: "Large Public Growth", textMr: "Large Public Growth", isCorrect: false },
        { label: "D", textEn: "Labour, Planning, Growth", textMr: "Labour, Planning, Growth", isCorrect: false },
      ],
    },
    {
      textEn: "In which year did the Right to Education Act come into force in India?",
      textMr: "भारतात 'शिक्षणाचा अधिकार' कायदा कोणत्या वर्षी लागू झाला?",
      explanationEn: "The Right to Education (RTE) Act came into force on 1 April 2010, giving children aged 6-14 the right to free and compulsory education.",
      explanationMr: "शिक्षणाचा अधिकार (RTE) कायदा १ एप्रिल २०१० ला लागू झाला. यामुळे ६-१४ वयोगटातील मुलांना मोफत व सक्तीचे शिक्षण मिळण्याचा अधिकार मिळाला.",
      options: [
        { label: "A", textEn: "2005", textMr: "२००५", isCorrect: false },
        { label: "B", textEn: "2009", textMr: "२००९", isCorrect: false },
        { label: "C", textEn: "2010", textMr: "२०१०", isCorrect: true },
        { label: "D", textEn: "2012", textMr: "२०१२", isCorrect: false },
      ],
    },
    {
      textEn: "Where was the first IIT established?",
      textMr: "IIT (Indian Institute of Technology) पहिले कोठे स्थापन झाले?",
      explanationEn: "The first IIT in India was established at Kharagpur (West Bengal) in 1951.",
      explanationMr: "भारतातील पहिले IIT खरगपूर (पश्चिम बंगाल) येथे १९५१ साली स्थापन झाले.",
      options: [
        { label: "A", textEn: "Mumbai", textMr: "मुंबई", isCorrect: false },
        { label: "B", textEn: "Delhi", textMr: "दिल्ली", isCorrect: false },
        { label: "C", textEn: "Kharagpur", textMr: "खरगपूर", isCorrect: true },
        { label: "D", textEn: "Chennai", textMr: "चेन्नई", isCorrect: false },
      ],
    },
    {
      textEn: "When was Sarva Shiksha Abhiyan (SSA) launched?",
      textMr: "सर्व शिक्षा अभियान (SSA) कधी सुरू झाला?",
      explanationEn: "Sarva Shiksha Abhiyan (SSA) was launched in 2000-01 to provide elementary education to all children.",
      explanationMr: "सर्व शिक्षा अभियान (SSA) २०००-०१ मध्ये सुरू झाला. सर्व मुलांना प्राथमिक शिक्षण मिळवून देणे हे त्याचे उद्दिष्ट आहे.",
      options: [
        { label: "A", textEn: "1995", textMr: "१९९५", isCorrect: false },
        { label: "B", textEn: "2000-2001", textMr: "२०००-२००१", isCorrect: true },
        { label: "C", textEn: "2005", textMr: "२००५", isCorrect: false },
        { label: "D", textEn: "2010", textMr: "२०१०", isCorrect: false },
      ],
    },
    {
      textEn: "In which year was the Dowry Prohibition Act enacted in India?",
      textMr: "हुंडाबंदी कायदा भारतात कोणत्या वर्षी लागू झाला?",
      explanationEn: "The Dowry Prohibition Act was enacted in India in 1961, making giving and taking of dowry a criminal offense.",
      explanationMr: "हुंडाबंदी कायदा (Dowry Prohibition Act) १९६१ मध्ये भारतात लागू झाला. हुंडा घेणे व देणे हे कायद्याने गुन्हा ठरवण्यात आले.",
      options: [
        { label: "A", textEn: "1955", textMr: "१९५५", isCorrect: false },
        { label: "B", textEn: "1961", textMr: "१९६१", isCorrect: true },
        { label: "C", textEn: "1970", textMr: "१९७०", isCorrect: false },
        { label: "D", textEn: "1980", textMr: "१९८०", isCorrect: false },
      ],
    },
    {
      textEn: "Which Prime Minister implemented the Mandal Commission recommendations?",
      textMr: "मंडल आयोगाच्या शिफारशी कोणत्या पंतप्रधानांनी लागू केल्या?",
      explanationEn: "PM V.P. Singh implemented the Mandal Commission recommendations in 1990, announcing 27% reservation for OBC.",
      explanationMr: "पंतप्रधान विश्वनाथ प्रताप सिंग यांनी १९९० मध्ये मंडल आयोगाच्या शिफारशी लागू केल्या आणि OBC साठी २७% आरक्षण जाहीर केले.",
      options: [
        { label: "A", textEn: "Rajiv Gandhi", textMr: "राजीव गांधी", isCorrect: false },
        { label: "B", textEn: "V. P. Singh", textMr: "विश्वनाथ प्रताप सिंग", isCorrect: true },
        { label: "C", textEn: "A.B. Vajpayee", textMr: "अटल बिहारी वाजपेयी", isCorrect: false },
        { label: "D", textEn: "Narasimha Rao", textMr: "नरसिंह राव", isCorrect: false },
      ],
    },
    {
      textEn: "The Kaka Saheb Kalelkar Commission was set up for?",
      textMr: "काकसाहेब कालेलकर आयोग कशासाठी स्थापन केला होता?",
      explanationEn: "The Kaka Saheb Kalelkar Commission was set up in 1953 to study the problems of Other Backward Classes (OBC).",
      explanationMr: "काकसाहेब कालेलकर आयोग १९५३ मध्ये इतर मागासवर्गीयांच्या (OBC) समस्यांचा अभ्यास करण्यासाठी स्थापन झाला.",
      options: [
        { label: "A", textEn: "Education reform", textMr: "शिक्षण सुधारणेसाठी", isCorrect: false },
        { label: "B", textEn: "Welfare of Other Backward Classes", textMr: "इतर मागासवर्गीयांच्या (OBC) सुधारणेसाठी", isCorrect: true },
        { label: "C", textEn: "For Scheduled Tribes", textMr: "अनुसूचित जमातींसाठी", isCorrect: false },
        { label: "D", textEn: "Women empowerment", textMr: "महिला सशक्तीकरणासाठी", isCorrect: false },
      ],
    },
    {
      textEn: "What was India's first artificial satellite?",
      textMr: "भारताचे पहिले कृत्रिम उपग्रह कोणते?",
      explanationEn: "India's first satellite 'Aryabhata' was launched on 19 April 1975 with Soviet assistance.",
      explanationMr: "भारताचा पहिला कृत्रिम उपग्रह 'आर्यभट्ट' १९ एप्रिल १९७५ ला सोव्हिएत रशियाच्या मदतीने प्रक्षेपित करण्यात आला.",
      options: [
        { label: "A", textEn: "Bhaskar", textMr: "भास्कर", isCorrect: false },
        { label: "B", textEn: "Aryabhata", textMr: "आर्यभट्ट", isCorrect: true },
        { label: "C", textEn: "Rohini", textMr: "रोहिणी", isCorrect: false },
        { label: "D", textEn: "INSAT-1A", textMr: "INSAT-1A", isCorrect: false },
      ],
    },
    {
      textEn: "Dr. Homi Bhabha is considered the father of?",
      textMr: "डॉ. होमी भाभा यांना कशाचे जनक मानले जाते?",
      explanationEn: "Dr. Homi Jehangir Bhabha is considered the father of India's nuclear energy programme. He founded BARC.",
      explanationMr: "डॉ. होमी जहांगीर भाभा यांना भारताच्या अणुऊर्जा कार्यक्रमाचे जनक मानले जाते. त्यांनी BARC ची स्थापना केली.",
      options: [
        { label: "A", textEn: "Green Revolution", textMr: "हरित क्रांती", isCorrect: false },
        { label: "B", textEn: "India's Nuclear Energy Programme", textMr: "भारताचा अणुऊर्जा कार्यक्रम", isCorrect: true },
        { label: "C", textEn: "India's Space Programme", textMr: "भारताचा अंतराळ कार्यक्रम", isCorrect: false },
        { label: "D", textEn: "Internet", textMr: "इंटरनेट", isCorrect: false },
      ],
    },
    {
      textEn: "Who is the father of the Indian space programme?",
      textMr: "भारतीय अंतराळ कार्यक्रमाचे जनक कोण आहेत?",
      explanationEn: "Dr. Vikram Sarabhai is considered the father of the Indian Space Research Programme. He founded ISRO.",
      explanationMr: "डॉ. विक्रम साराभाई यांना भारतीय अंतराळ संशोधन कार्यक्रमाचे जनक मानले जाते. त्यांनी ISRO ची स्थापना केली.",
      options: [
        { label: "A", textEn: "Dr. APJ Abdul Kalam", textMr: "डॉ. एपीजे अब्दुल कलाम", isCorrect: false },
        { label: "B", textEn: "Dr. Vikram Sarabhai", textMr: "डॉ. विक्रम साराभाई", isCorrect: true },
        { label: "C", textEn: "Dr. K. Kasturirangan", textMr: "डॉ. के. कस्तुरीरंगन", isCorrect: false },
        { label: "D", textEn: "Dr. Homi Bhabha", textMr: "डॉ. होमी भाभा", isCorrect: false },
      ],
    },
    {
      textEn: "Who is called the 'Missile Man' of India?",
      textMr: "भारताचे 'क्षेपणास्त्र पुरुष' (Missile Man) कोणाला म्हणतात?",
      explanationEn: "Dr. APJ Abdul Kalam is called the 'Missile Man' of India. He was the 11th President of India.",
      explanationMr: "डॉ. एपीजे अब्दुल कलाम यांना भारताचे 'क्षेपणास्त्र पुरुष' म्हणतात. ते भारताचे ११वे राष्ट्रपती होते.",
      options: [
        { label: "A", textEn: "Dr. Vikram Sarabhai", textMr: "डॉ. विक्रम साराभाई", isCorrect: false },
        { label: "B", textEn: "Dr. Homi Bhabha", textMr: "डॉ. होमी भाभा", isCorrect: false },
        { label: "C", textEn: "Dr. APJ Abdul Kalam", textMr: "डॉ. एपीजे अब्दुल कलाम", isCorrect: true },
        { label: "D", textEn: "Dr. K. Sivan", textMr: "डॉ. के. सिवन", isCorrect: false },
      ],
    },
    {
      textEn: "Where was India's first modern cotton textile mill established?",
      textMr: "भारतातील पहिला आधुनिक कापड गिरणी कोठे स्थापन झाला?",
      explanationEn: "India's first modern cotton textile mill (Bombay Spinning and Weaving Company) was established in Mumbai in 1854.",
      explanationMr: "भारतातील पहिला आधुनिक कापड गिरणी (Bombay Spinning and Weaving Company) मुंबईत १८५४ मध्ये स्थापन झाला.",
      options: [
        { label: "A", textEn: "Surat", textMr: "सुरत", isCorrect: false },
        { label: "B", textEn: "Mumbai", textMr: "मुंबई", isCorrect: true },
        { label: "C", textEn: "Ahmedabad", textMr: "अहमदाबाद", isCorrect: false },
        { label: "D", textEn: "Kolkata", textMr: "कोलकाता", isCorrect: false },
      ],
    },
    {
      textEn: "Which city of India is called the 'Silicon Valley'?",
      textMr: "भारतातील 'सिलिकॉन व्हॅली' कोणत्या शहराला म्हणतात?",
      explanationEn: "Bengaluru (Bangalore) is called India's 'Silicon Valley' due to its large concentration of IT industries.",
      explanationMr: "बेंगलोर (बेंगळुरू) ला भारताची 'सिलिकॉन व्हॅली' म्हणतात. येथे माहिती तंत्रज्ञान उद्योग मोठ्या प्रमाणात आहे.",
      options: [
        { label: "A", textEn: "Mumbai", textMr: "मुंबई", isCorrect: false },
        { label: "B", textEn: "Hyderabad", textMr: "हैद्राबाद", isCorrect: false },
        { label: "C", textEn: "Bangalore", textMr: "बेंगलोर", isCorrect: true },
        { label: "D", textEn: "Pune", textMr: "पुणे", isCorrect: false },
      ],
    },
    {
      textEn: "The Bhilai Steel Plant was set up with the help of which country?",
      textMr: "भिलाई पोलाद कारखाना कोणत्या देशाच्या मदतीने उभारला गेला?",
      explanationEn: "Bhilai Steel Plant (Chhattisgarh) was set up with Soviet Russian assistance. It is one of India's major steel plants.",
      explanationMr: "भिलाई पोलाद कारखाना (छत्तीसगड) सोव्हिएत रशियाच्या मदतीने उभारला गेला. हे भारतातील मोठ्या पोलाद कारखान्यांपैकी एक आहे.",
      options: [
        { label: "A", textEn: "USA", textMr: "अमेरिका", isCorrect: false },
        { label: "B", textEn: "Soviet Union (USSR)", textMr: "सोव्हिएत रशिया (USSR)", isCorrect: true },
        { label: "C", textEn: "Germany", textMr: "जर्मनी", isCorrect: false },
        { label: "D", textEn: "Britain", textMr: "ब्रिटन", isCorrect: false },
      ],
    },
    {
      textEn: "When did Doordarshan (national TV) start in India?",
      textMr: "भारतात दूरदर्शन (Doordarshan) कधी सुरू झाले?",
      explanationEn: "Doordarshan started in India on 15 September 1959 in Delhi. It was India's first television broadcast.",
      explanationMr: "भारतात दूरदर्शन (DD) १५ सप्टेंबर १९५९ रोजी दिल्लीत सुरू झाले. हे भारतातील पहिले टेलिव्हिजन प्रसारण होते.",
      options: [
        { label: "A", textEn: "1950", textMr: "१९५०", isCorrect: false },
        { label: "B", textEn: "1959", textMr: "१९५९", isCorrect: true },
        { label: "C", textEn: "1965", textMr: "१९६५", isCorrect: false },
        { label: "D", textEn: "1975", textMr: "१९७५", isCorrect: false },
      ],
    },
    {
      textEn: "Where is the FTII (Film and Television Institute of India) located?",
      textMr: "FTII (Film and Television Institute of India) कोठे आहे?",
      explanationEn: "FTII (Film and Television Institute of India) is located in Pune. It was established by the Government of India in 1960.",
      explanationMr: "FTII (चित्रपट व दूरदर्शन संस्था) पुणे येथे आहे. ती भारत सरकारने १९६० मध्ये स्थापन केली.",
      options: [
        { label: "A", textEn: "Mumbai", textMr: "मुंबई", isCorrect: false },
        { label: "B", textEn: "Delhi", textMr: "दिल्ली", isCorrect: false },
        { label: "C", textEn: "Pune", textMr: "पुणे", isCorrect: true },
        { label: "D", textEn: "Hyderabad", textMr: "हैद्राबाद", isCorrect: false },
      ],
    },
    {
      textEn: "When did mobile phone service start in India?",
      textMr: "भारतात मोबाईल फोन सेवा कधी सुरू झाली?",
      explanationEn: "India's first mobile phone service was launched on 31 July 1995 in Kolkata.",
      explanationMr: "भारतात पहिली मोबाईल फोन सेवा ३१ जुलै १९९५ रोजी कोलकाता येथे सुरू झाली.",
      options: [
        { label: "A", textEn: "1985", textMr: "१९८५", isCorrect: false },
        { label: "B", textEn: "1995", textMr: "१९९५", isCorrect: true },
        { label: "C", textEn: "2000", textMr: "२०००", isCorrect: false },
        { label: "D", textEn: "2005", textMr: "२००५", isCorrect: false },
      ],
    },
    {
      textEn: "In which year did internet service become available to the general public in India?",
      textMr: "भारतात इंटरनेट सेवा सर्वसामान्यांसाठी कोणत्या वर्षी उपलब्ध झाली?",
      explanationEn: "VSNL (Videsh Sanchar Nigam Limited) launched internet services for the general public in India on 15 August 1995.",
      explanationMr: "भारतात VSNL (Videsh Sanchar Nigam Limited) ने १५ ऑगस्ट १९९५ ला सर्वसामान्यांसाठी इंटरनेट सेवा सुरू केली.",
      options: [
        { label: "A", textEn: "1991", textMr: "१९९१", isCorrect: false },
        { label: "B", textEn: "1995", textMr: "१९९५", isCorrect: true },
        { label: "C", textEn: "2000", textMr: "२०००", isCorrect: false },
        { label: "D", textEn: "2005", textMr: "२००५", isCorrect: false },
      ],
    },
    {
      textEn: "In which year did India's 'Aadhaar Card' programme start?",
      textMr: "भारतात 'आधार कार्ड' कार्यक्रम कोणत्या वर्षी सुरू झाला?",
      explanationEn: "UIDAI (Unique Identification Authority of India) and the Aadhaar card scheme were launched in January 2009.",
      explanationMr: "UIDAI (Unique Identification Authority of India) ची स्थापना व आधार कार्ड योजना जानेवारी २००९ मध्ये सुरू झाली.",
      options: [
        { label: "A", textEn: "2005", textMr: "२००५", isCorrect: false },
        { label: "B", textEn: "2009", textMr: "२००९", isCorrect: true },
        { label: "C", textEn: "2012", textMr: "२०१२", isCorrect: false },
        { label: "D", textEn: "2015", textMr: "२०१५", isCorrect: false },
      ],
    },
    {
      textEn: "Political Science is the study of?",
      textMr: "राज्यशास्त्र (Political Science) कशाचा अभ्यास करते?",
      explanationEn: "Political Science is the study of state, government, political systems, rights, duties, and international relations.",
      explanationMr: "राज्यशास्त्र हे राज्य, सरकार, राजकीय व्यवस्था, अधिकार, कर्तव्ये व आंतरराष्ट्रीय संबंधांचा अभ्यास करते.",
      options: [
        { label: "A", textEn: "Geography", textMr: "भूगोल", isCorrect: false },
        { label: "B", textEn: "State, government and political systems", textMr: "राज्य, सरकार व राजकीय व्यवस्था", isCorrect: true },
        { label: "C", textEn: "Economy", textMr: "अर्थव्यवस्था", isCorrect: false },
        { label: "D", textEn: "Sociology", textMr: "समाजशास्त्र", isCorrect: false },
      ],
    },
    {
      textEn: "India's foreign policy is based on which principle?",
      textMr: "भारताचे परराष्ट्र धोरण कोणत्या तत्त्वावर आधारित आहे?",
      explanationEn: "India's foreign policy is based on Non-Alignment. India does not join any military bloc.",
      explanationMr: "भारताचे परराष्ट्र धोरण अलिप्तता (Non-Alignment) तत्त्वावर आधारित आहे. भारत कोणत्याही लष्करी गटात सामील नाही.",
      options: [
        { label: "A", textEn: "Military Alliance", textMr: "सैनिक आघाडी", isCorrect: false },
        { label: "B", textEn: "Non-Alignment", textMr: "अलिप्तता (Non-Alignment)", isCorrect: true },
        { label: "C", textEn: "Expansionism", textMr: "विस्तारवाद", isCorrect: false },
        { label: "D", textEn: "Imperialism", textMr: "साम्राज्यवाद", isCorrect: false },
      ],
    },
    {
      textEn: "In which year was the United Nations Organization (UNO) established?",
      textMr: "संयुक्त राष्ट्रे (UNO) ची स्थापना कोणत्या वर्षी झाली?",
      explanationEn: "The United Nations Organization (UNO) was established on 24 October 1945. It currently has 193 member countries.",
      explanationMr: "संयुक्त राष्ट्रे (UNO) ची स्थापना २४ ऑक्टोबर १९४५ रोजी झाली. सध्या त्यात १९३ सदस्य देश आहेत.",
      options: [
        { label: "A", textEn: "1945", textMr: "१९४५", isCorrect: true },
        { label: "B", textEn: "1947", textMr: "१९४७", isCorrect: false },
        { label: "C", textEn: "1950", textMr: "१९५०", isCorrect: false },
        { label: "D", textEn: "1955", textMr: "१९५५", isCorrect: false },
      ],
    },
    {
      textEn: "Where is the headquarters of the UNO?",
      textMr: "UNO चे मुख्यालय कोठे आहे?",
      explanationEn: "UNO headquarters is in New York, USA. It also has important offices in Geneva and Vienna.",
      explanationMr: "UNO चे मुख्यालय न्यूयॉर्क, अमेरिका येथे आहे. संयुक्त राष्ट्राचे अनेक कार्यालये जिनिव्हा, व्हिएन्ना येथेही आहेत.",
      options: [
        { label: "A", textEn: "London", textMr: "लंडन", isCorrect: false },
        { label: "B", textEn: "Geneva", textMr: "जिनिव्हा", isCorrect: false },
        { label: "C", textEn: "New York", textMr: "न्यूयॉर्क", isCorrect: true },
        { label: "D", textEn: "Paris", textMr: "पॅरिस", isCorrect: false },
      ],
    },
    {
      textEn: "How many permanent members does the UN Security Council have?",
      textMr: "संयुक्त राष्ट्र सुरक्षा परिषदेचे स्थायी सदस्य किती आहेत?",
      explanationEn: "The UN Security Council has 5 permanent members: USA, Russia, China, UK, France. All have veto power.",
      explanationMr: "UN सुरक्षा परिषदेचे ५ स्थायी सदस्य आहेत: अमेरिका, रशिया, चीन, ब्रिटन, फ्रान्स. या सर्वांना नकाराधिकार (Veto) आहे.",
      options: [
        { label: "A", textEn: "Three", textMr: "३", isCorrect: false },
        { label: "B", textEn: "Four", textMr: "४", isCorrect: false },
        { label: "C", textEn: "Five", textMr: "५", isCorrect: true },
        { label: "D", textEn: "Seven", textMr: "७", isCorrect: false },
      ],
    },
    {
      textEn: "What does UNICEF work for?",
      textMr: "UNICEF कशासाठी काम करते?",
      explanationEn: "UNICEF (United Nations Children's Fund) works for the rights, education, health and welfare of children.",
      explanationMr: "UNICEF (United Nations Children's Fund) बालकांचे हक्क, शिक्षण, आरोग्य व कल्याणासाठी काम करते.",
      options: [
        { label: "A", textEn: "For environmental protection", textMr: "पर्यावरण संरक्षणासाठी", isCorrect: false },
        { label: "B", textEn: "For rights and development of children", textMr: "बालकांच्या हक्कांसाठी व विकासासाठी", isCorrect: true },
        { label: "C", textEn: "For trade regulation", textMr: "व्यापार नियमनासाठी", isCorrect: false },
        { label: "D", textEn: "For peacekeeping operations", textMr: "शांती मोहिमांसाठी", isCorrect: false },
      ],
    },
    {
      textEn: "Who formulated the Panchsheel principles?",
      textMr: "पंचशील तत्त्वे कोणी मांडली?",
      explanationEn: "The Panchsheel principles (1954) were formulated by PM Nehru and Chinese PM Chou En-lai, containing five principles of peaceful coexistence.",
      explanationMr: "पंचशील तत्त्वे (१९५४) पंतप्रधान पं. नेहरू आणि चीनचे पंतप्रधान चाऊ एन-लाय यांनी मांडली. यात शांततापूर्ण सहअस्तित्वाची पाच तत्त्वे होती.",
      options: [
        { label: "A", textEn: "Mahatma Gandhi", textMr: "गांधीजी", isCorrect: false },
        { label: "B", textEn: "Pt. Nehru and Chinese PM Chou En-lai", textMr: "पं. नेहरू व चीनचे पंतप्रधान", isCorrect: true },
        { label: "C", textEn: "Dr. B.R. Ambedkar", textMr: "बाबासाहेब आंबेडकर", isCorrect: false },
        { label: "D", textEn: "Sardar Patel", textMr: "सरदार पटेल", isCorrect: false },
      ],
    },
    {
      textEn: "Where was the Non-Aligned Movement (NAM) founded?",
      textMr: "NAM (Non-Aligned Movement) ची स्थापना कोठे झाली?",
      explanationEn: "The first NAM conference was held in Belgrade (Yugoslavia) in September 1961. India, Yugoslavia and Egypt were founding members.",
      explanationMr: "NAM (अलिप्त राष्ट्र चळवळ) ची पहिली परिषद सप्टेंबर १९६१ मध्ये बेलग्रेड (युगोस्लाव्हिया) येथे झाली. भारत, युगोस्लाव्हिया व इजिप्त हे संस्थापक देश होते.",
      options: [
        { label: "A", textEn: "Jakarta", textMr: "जकार्ता", isCorrect: false },
        { label: "B", textEn: "Belgrade", textMr: "बेलग्रेड", isCorrect: true },
        { label: "C", textEn: "Delhi", textMr: "दिल्ली", isCorrect: false },
        { label: "D", textEn: "Cairo", textMr: "काहिरा", isCorrect: false },
      ],
    },
    {
      textEn: "How has India contributed to UN peacekeeping missions?",
      textMr: "भारताने UNO च्या शांती मोहिमांमध्ये कसे योगदान दिले आहे?",
      explanationEn: "India is one of the largest troop contributors to UN peacekeeping missions, having participated in missions in Korea, Congo, Somalia and others.",
      explanationMr: "भारत UN शांती मोहिमांमध्ये सर्वाधिक सैनिक पुरवणाऱ्या देशांपैकी एक आहे. भारताने कोरिया, काँगो, सोमालिया येथे शांती मोहिमांत भाग घेतला आहे.",
      options: [
        { label: "A", textEn: "By providing financial aid only", textMr: "आर्थिक मदत देऊन", isCorrect: false },
        { label: "B", textEn: "By deploying peacekeeping troops", textMr: "शांती रक्षकांची (Peacekeepers) तैनाती करून", isCorrect: true },
        { label: "C", textEn: "By providing weapons", textMr: "शस्त्रास्त्रे देऊन", isCorrect: false },
        { label: "D", textEn: "By providing scientific assistance", textMr: "वैज्ञानिक मदत देऊन", isCorrect: false },
      ],
    },
    {
      textEn: "How many countries are in SAARC?",
      textMr: "SAARC (दक्षिण आशियाई प्रादेशिक सहकार्य संघटना) मध्ये किती देश आहेत?",
      explanationEn: "SAARC has 8 member countries: India, Pakistan, Bangladesh, Sri Lanka, Nepal, Bhutan, Maldives and Afghanistan. Founded in 1985.",
      explanationMr: "SAARC मध्ये ८ देश आहेत: भारत, पाकिस्तान, बांगलादेश, श्रीलंका, नेपाळ, भूतान, मालदीव आणि अफगाणिस्तान. त्याची स्थापना १९८५ मध्ये झाली.",
      options: [
        { label: "A", textEn: "Five", textMr: "५", isCorrect: false },
        { label: "B", textEn: "Six", textMr: "६", isCorrect: false },
        { label: "C", textEn: "Seven", textMr: "७", isCorrect: false },
        { label: "D", textEn: "Eight", textMr: "८", isCorrect: true },
      ],
    },
    {
      textEn: "Why has India not signed the Nuclear Non-Proliferation Treaty (NPT)?",
      textMr: "भारताने 'परमाणु अस्त्र अप्रसार करार' (NPT) वर स्वाक्षरी का केली नाही?",
      explanationEn: "India has not signed the NPT as it considers it discriminatory — existing nuclear powers can keep their weapons while others are prohibited.",
      explanationMr: "भारताने NPT वर स्वाक्षरी केली नाही कारण हा करार भेदभावपूर्ण असून, पूर्वीचे अणुशक्ती देश आपली शस्त्रे ठेवतात पण इतरांना मनाई करतात.",
      options: [
        { label: "A", textEn: "Because India does not have nuclear bombs", textMr: "भारताकडे अणुबॉम्ब नाही म्हणून", isCorrect: false },
        { label: "B", textEn: "India considers NPT discriminatory", textMr: "NPT भेदभावकारक आहे असे भारताचे म्हणणे आहे", isCorrect: true },
        { label: "C", textEn: "UN did not give permission", textMr: "UN ने परवानगी नाही दिली", isCorrect: false },
        { label: "D", textEn: "Due to US pressure", textMr: "यूएस दबावामुळे", isCorrect: false },
      ],
    },
  ],
};

export default data;
